### ISSUE TITLE
Animated album art

### ISSUE THREAD

**Issue by Radical4ever** [z-huang/InnerTune#1001]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So in spotify, tidal wave and apple music there's this feature where certain albums have a gif as their album image instead of a plain image, so is it possible to set gifs on our saved music on the library or be set automatically by the app

### Why do you want this feature?

Looks awesome, and in this app could be awesome too

### Additional information

Maybe using spotify api to get this could be a way to implement it and make it automatically, i dont know if that can be provided

**Comment by xmha97** [comment]
+1

**Comment by z-huang** [comment]
It seems that there isn't an API to get the animated album art, so it's impossible.

**Comment by radical4ever** [comment]
> It seems that there isn't an API to get the animated album art, so it's impossible.

But what about manually adding it when we save our songs locally?, like a custom cover, that cant be a feature either?

**Comment by z-huang** [comment]
Custom song cover is not planned. Every YT song already has the cover.
