### ISSUE TITLE
Implement Spotify-lyrics-api

### ISSUE THREAD

**Issue by anxiouslelimo** [z-huang/InnerTune#1002]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Request to implement https://github.com/akashrchandran/spotify-lyrics-api. 

### Why do you want this feature?

The sync feature currently implemented through kugou fetches entirely different lyrics for certain songs. The above mentioned is "A Rest API for fetching lyrics from Spotify which is powered by Musixmatch". Musixmatch supports Line synced and Word synced type of timed lyrics. Line Synced is the timetag is given till which the line is sang and the word synced lyrics time specifed when the word comes up in the song.

**Comment by owencz1998** [comment]
Seen this on other apps and its pretty good mate 👍

**Comment by zerobun** [comment]
Please implement this 🙏❤️
