### ISSUE TITLE
show unavailable songs in playlist

### ISSUE THREAD

**Issue by Nonanne** [z-huang/InnerTune#1005]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

show unavailable songs in playlist (global and local playlists)

### Why do you want this feature?

to show which song is unavailable and easy to find/replace with new one.

### Additional information

For example:

InnerTune 0.5.2
![Screenshot_20230828-013226](https://github.com/z-huang/InnerTune/assets/94383254/eb159564-0186-46c2-a468-b724ad62ebc7)

YT music
![Screenshot_20230828-013244_YT_Music_ReVanced](https://github.com/z-huang/InnerTune/assets/94383254/2ae35752-62e1-40db-ad18-9c7a732d3453)

**Comment by z-huang** [comment]
This would make the InnerTube library and user interaction more complex, so it's not being considered.
