### ISSUE TITLE
Make it possible to play videos instead of album art like in YT Music

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#1006]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Make it possible to play videos instead of album art like in YT Music

### Why do you want this feature?

I think this is a cool feature.  For example, it often happens to me that when you take out your phone to switch the track, but you start watching the video for the song and you just get stuck and you don’t want to switch :) Especially if it’s your favorite music video.  If it's not hard to implement.  Thank you!

### Additional information

For videos, you could make a toggle or button to switch between album cover and video.

**Comment by z-huang** [comment]
Playing video streams adds complexity to the current app architecture. The app will stay audio-focused for now.
