### ISSUE TITLE
Crash whenever play any song

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/InnerTune#1009]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. open the app
2. play any sound
3.  it crash

### Expected behavior

It should play normally

### Actual behavior

it crashed.

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/75346987/0a364c8b-4361-431f-a9c6-8896da7df996

### Logs

Log file contains crash message
[error.txt](https://github.com/z-huang/InnerTune/files/12452729/error.txt)

### InnerTune version

0.5.2 Full

### Android version

Android 12/HarmonyOS4.0.0.112 beta

### Additional information

I cleared all dowloadds, song cache, image cache. Then updated the app to the newest version. Same bug occurs. But in the old version, when the app crashed, but it can still play the song in the backlground for some seconds.

The app was usable in the system when i last used it.

**Comment by z-huang** [comment]
The bug may have something to do with HarmonyOS. In the Android emulators, everything works well. Try clearing app data and using the app from scratch.

**Comment by smarttommyau** [comment]
ok if this is not the app's problem i will report it to Huawei and hope they can fix it. Thanks
