### ISSUE TITLE
Fdroid (Izzi) is not on the latest version. it says 5.0

### ISSUE THREAD

**Issue by darkza** [z-huang/InnerTune#1010]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Fdroid (Izzi) is not on the latest version. it says 5.0

### Why do you want this feature?

easy er to update alle device's

**Comment by z-huang** [comment]
The build is successful in F-Droid: https://monitor.f-droid.org/builds/log/com.zionhuang.music/18#site-footer
I have no idea why it's not updated to 0.5.2. @IzzySoft Do you know why?

**Comment by IzzySoft** [comment]
Is it not? A new index was just published a few hours ago. And the website [shows v0.5.2](https://f-droid.org/packages/com.zionhuang.music/). Last cycle just took a bit longer with the signing part, which happens on an air-gapped server involving [Sneakernet](https://en.wikipedia.org/wiki/Sneakernet)…

**Comment by z-huang** [comment]
Okay, it turns out we should be patient. 😄

**Comment by IzzySoft** [comment]
Yeah, sometimes the manual step takes a bit longer. Ciaran is a human, too – and humans sometimes need a break ("things" usually do not "need a break" but "do break", unfortunately :speak_no_evil: :dash:)

That said: better a warning when it's not needed, than a "broken thing" going unnoticed :wink:
