### ISSUE TITLE
build FOSS debug apk in actions

### ISSUE THREAD

**Issue by NeeRaj-2401** [z-huang/InnerTune#1011]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As title suggests, build foss debug apk as well in actions tab

### Why do you want this feature?

The debug builds only full version which has lots of analytics proprietary libraries,
It would be nice to have foss debug builds as well.

**Comment by z-huang** [comment]
It is essential to clarify that debug builds are primarily intended for the purpose of identifying and testing potential bugs. Consequently, it is imperative to generate the "full" version as it encompasses features that are absent in the foss variant. It is not advisable to rely on the debug version for primary usage.
