### ISSUE TITLE
Songs section on artist page 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#1013]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to an artist then go on songs 

### Expected behavior

Show songs covers properly and also show all songs when clicking on songs.

### Actual behavior

Bad album art and songs section don't show 

### Screenshots/Screen recordings

![Screenshot_20230830_153003_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/96526481/bf09d6b9-bc3a-4d4f-ba17-f80e77d8d809)
![Screenshot_20230830_153006_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/96526481/68331171-5b32-4d4a-9723-227eb6bcaaa3)

### InnerTune version

New debug version 

### Android version

13 one ui 5.1

**Comment by z-huang** [comment]
This issue is related to #982. Unfortunately, I can't solve it completely because I don't know what your response looks like. YouTube probably gives different response in different regions. Only If you provide logs or debug yourself will we have the chance to solve it.
