### ISSUE TITLE
Home page upgrade and account improvement

### ISSUE THREAD

**Issue by Omkar-Dahal** [z-huang/InnerTune#1019]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The innertune homepage kinda sucks 
The old version had better one
Please try to make like yt music home page
I mean add button and options like ytm
Also make the account feature interactive cause that just dont work.
Add option to like and dislike and add playlist direct to account.
You always inspire me do to app development and i hope you can do that possible

### Why do you want this feature?

Just to listen peacefully

### Additional information

The old feature of exporting mp3 was good too

**Comment by z-huang** [comment]
> This issue contains only one feature request.

Please follow the rule and be nice. There's no accounting for taste. You're welcome to make PRs or write your own app that matches your taste.
