### ISSUE TITLE
Spotify playlist to yt music conversion as seen in spotube. 

### ISSUE THREAD

**Issue by zerobun** [z-huang/InnerTune#1078]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Inner tune will connect to your Spotify account and retrieve the playlist info from the profile and display them in inner tune in a Spotify playlist section. When a playlist is clicked it starts converting the Spotify songs to yt music songs. And displays them. 

### Why do you want this feature?

Spotify has made lyrics a paid feature now and their main app is slow as hell, they even added a reel like feature (imo its the worst thing). So I would rather like many other people, would move to an open source yt music Client. And having this feature will mean u can still get ur Spotify playlists and play them in yt music client (inner tune).
It also will help those who have collaborative playlists, they won't have to use the main Spotify app to listen to songs jus gotta add and that's it. They can freely enjoy their collaborated music peaceful without being in Spotify. 

### Additional information

https://github.com/KRTirtho/spotube
This project utilises this feature to fetch and display the playlists. Really unique.
Idk if it will but I'm jus leaving it here.
A screenshot of how it looks:
![Screenshot_2023_0921_060051](https://github.com/z-huang/InnerTune/assets/127630316/befec85b-d4e9-491e-98e7-931fcb17e399)

**Comment by siggi1984** [comment]
would be a cool feature.

**Comment by Yonle** [comment]
> When a playlist is clicked it starts converting the Spotify songs to yt music songs. And displays them.
Does not that means we need to fetch every YT links (and then fetch the metadatas) from Spotify titles from playlist? Won't that also drain more user data bandwidth? Noting that majority of mobile users are mostly Mobile Data at some countries.

**Comment by z-huang** [comment]
This app focuses on YT only and won't involve connection to Spotify for simplicity. If you want to import a Spotify playlist, you can convert it to a YT playlist using [tunemymusic.com](https://www.tunemymusic.com/), and make the YT playlist public. Then you can search and import the playlist in InnerTune.
