### ISSUE TITLE
Ability to import m3u playlists from storage. 

### ISSUE THREAD

**Issue by zerobun** [z-huang/InnerTune#1081]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Jus like [Symphony](https://github.com/zyrouge/symphony), where it has the ability to scan and find m3u files on ur phone/sd card storage and u just have to click and import.

### Why do you want this feature?

Having something like this would be a major help for people who already migrating from a different app or already have playlists and just wanna import.
Rather than slowly adding 1 song each in a new playlist to create theit old playlist.

**Comment by z-huang** [comment]
InnerTune doesn't support playing local media files. Therefore, it's impossible for you to import m3u files.

**Comment by zerobun** [comment]
> InnerTune doesn't support playing local media files. Therefore, it's impossible for you to import m3u files.

Any plans on adding local media support in the future?

**Comment by z-huang** [comment]
Not planned.
