### ISSUE TITLE
Casting 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#111]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Able to cast my Music to alexa google (ect) 

### Why do you want this feature?

To be able to listen to my music on my sound systems.

**Comment by Mateus109** [comment]
Essential feature, definitely a shame audio casting is currently not available. Almost a deal-breaker. But perhaps it's not a simple feature to all.

**Comment by owencz1998** [comment]
It's a shame it's a contribution only I think this would be a very handy feature and hopefully we can have this one day.

**Comment by Mateus109** [comment]
Ok, so I assume that, because Innertune is (illegally?) bypassing the YouTube Music subscription, the cast audio stream would have to do the same and would therefore reveal to Google how this is achieved. So casting will never be an option. Only bluetooth audio streaming will work.

**Comment by owencz1998** [comment]
Well I'm sure theres away to add casting for example the same way piped API would work but what about illegal movie apps that have casting to TV wouldn't that work the same way

**Comment by DarkCrypt** [comment]
No plans for tv...

I found an old Spotify tv mod that's working on Android TV 10 if anyone wants to try it out.

**Comment by z-huang** [comment]
It seems that the app needs to be available in Google Play to enable Google Assistant, so it's impossible.

**Comment by timkgh** [comment]
> It seems that the app needs to be available in Google Play to enable Google Assistant, so it's impossible.

I do not think this is true, sideloaded apps are able to _cast_. It _may_ be true for Google Assistant, but _casting audio_ to a Chromecast enabled device is different.

**Comment by eifr** [comment]
maybe using fcast could be a possibility?
