### ISSUE TITLE
Enable Android Auto integration 

### ISSUE THREAD

**Issue by urmomsangus** [z-huang/InnerTune#125]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to see this app have full Android Auto integration.

I enabled developer options in Android Auto (on my device) which allows your app, Music, to show up on Android Auto (in my vehicle), but songs do not display and music does not play.

Thanks for your awesome app 

### Why do you want this feature?

This feature would allow me to remove Spotify from my device. I am unaware of any FOSS music apps that correctly work with Android Auto.

**Comment by ThatOneCalculator** [comment]
Android Auto uses a closed-source API iirc.

**Comment by urmomsangus** [comment]
I believe @ThatOneCalculator is correct. I did a lot of research and I believe that at the minimum the app has to appear on Play Store too for Android Auto.

I'm going to close this issue since I think it's unable to be achieved. The Dev can reopen if needed

**Comment by z-huang** [comment]
If you enable developer mode in Android Auto, you can see my app. What the developer has to do is implement the `MediaBrowserService` class. I think it's possible. I'll keep this issue open.

**Comment by urmomsangus** [comment]
Related issue from ViMusic which also contains a link to a Newpipe issue with good info:

https://github.com/vfsfitvnm/ViMusic/issues/47

**Comment by z-huang** [comment]
Implemented.

**Comment by urmomsangus** [comment]
Thanks for doing this. I was able to test the latest F-Droid build from Izzy and it's great.

The only thing I can't figure out is if shuffle is an option? If I go to my "songs" and play, they play in order.

**Comment by z-huang** [comment]
Implemented.
