### ISSUE TITLE
[FEATURES REQUEST] Bring Spotify Client.

### ISSUE THREAD

**Issue by 1YuvrajS** [z-huang/InnerTune#1255]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

- [ ] Most users who wanted to Spotify Client for exploring music and listen. 
- [ ] In Home Screen, use Spotify Home like what we explore and different categories
- [ ] I don't want to Current location Genre if I changed Content Location to eg: United States. Only cover genre when changing to different Content Location.
- [ ] I don't want see New Releases current location content, when I changed to another Country. It is totally mess.

### Why do you want this feature?

1. I uses Spotify the most. What I want to listen New released song and Popular Pick generated by Spotify. I never used YouTube Music before.
2. Showing Current Location Content look mess when I changed to Content to United States.

**Comment by okgamr** [comment]
@z-huang yes this guy knows what he's talking about. I've used [Spotube](https://play.google.com/store/apps/details?id=oss.krtirtho.spotube) for this (it also uses YT music, besides Spotify) but the UI is just 🤮. So we can make **Outtertune** (on the spot invention). Hope you'll try to make it! Also, @1YuvrajS you can use Spotube until this guy makes Outtertune

**Comment by z-huang** [comment]
Sorry, this app is intended for "YouTube" only. As far as I know, there're apps for Spotify. You can try them out!
