### ISSUE TITLE
Duplications in playlist 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#156]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A message that tells you that the song is already in your playlist with a option to click don't add or continue.

### Why do you want this feature?

So you don't accidentally add the same songs in your playlist :)

**Comment by owencz1998** [comment]
Hey @z-huang whiles you've added like undo when deleting a song in playlist ect could u possible add this as this would be very helpful for me haha 😄

**Comment by anxiouslelimo** [comment]
@z-huang Thanks for your wonderful app. This is one feature that I would also like implemented.

**Comment by owencz1998** [comment]
@z-huang can we have this before releasing please 🙏

**Comment by z-huang** [comment]
There's no enough time to do it before the release, sorry.

**Comment by owencz1998** [comment]
No worried buddy 😁

**Comment by z-huang** [comment]
Added in 80e1ed7637f9fb18668bae65e849a7bf6f354551
