### ISSUE TITLE
Dynamic theme 

### ISSUE THREAD

**Issue by jerryop** [z-huang/InnerTune#159]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add dynamic theme support

### Why do you want this feature?

It looks good and minimal

**Comment by z-huang** [comment]
Do you mean adjusting theme color according to the color of the playing song artwork?

**Comment by jerryop** [comment]
Yess

**Comment by owencz1998** [comment]
Will there still be an option to have the navigation bar to be able to have its own color and the dynamic

**Comment by z-huang** [comment]
The navigation bar follows the theme color.

**Comment by owencz1998** [comment]
Awsome will make the app look stunning

**Comment by Black-StellarSpectrum** [comment]
> Do you mean adjusting theme color according to the color of the playing song artwork?

Please also add the Amoled Black theme in the app.

**Comment by owencz1998** [comment]
Hi @z-huang not sure if this is relevant or completely wrong but I found this dude 

https://codelabs.developers.google.com/codelabs/apply-dynamic-color#3

**Comment by z-huang** [comment]
The dynamic theme there means dynamic according to your wallpaper, not to the album art.

**Comment by owencz1998** [comment]
Ahh ok no worries dude

**Comment by z-huang** [comment]
By the way, Jetpack Compose is the trend in Android development and may be easier to build the application. If the app becomes stable, I'll migrate to Compose sooner or later.

**Comment by owencz1998** [comment]
Ahh nice one man can't wait 😄

**Comment by nikhilCad** [comment]
Can static theme and old static accent colours be added as optional?
