### ISSUE TITLE
App shortcuts

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#194]
### Checklist

- [X] I've checked that there is no other issue with this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

https://developer.android.com/develop/ui/views/launch/shortcuts

### Why do you want this feature?

Create shortcuts for different parts of the app for faster access.

<img width=200 src="https://user-images.githubusercontent.com/23485114/191183859-eff1bc48-ddf1-452d-b065-1ad2058f1e77.png" />

**Comment by z-huang** [comment]
Which shortcuts would you like to have?

**Comment by xmha97** [comment]
1. Search (9 apps)
SoundCloud, Spotify, Anghami, Pandora, iHeartRadio, YT Music, Mi Music, Deezer, TIDAL

2. Likes (4 apps)
SoundCloud: *Play Likes*, Anghami: *Likes*, Spotify: *Liked Songs*, Samsung Music: *Favorite tracks*

Other
TIDAL: *My collection*, iHeartRadio: *Your Library*, Mi Music: *Local songs*, Samsung Music: *Recently added*, Retro Music: *Last added*, Mi Music: *Recently played*, Samsung Music: *Play*, Retro Music: *Shuffle all*, Retro Music: *Most played*, Anghami: *My Playlists*, VLC: *Playlists*

**Comment by xmha97** [comment]
1. Search (9 apps)
SoundCloud, Spotify, Anghami, Pandora, iHeartRadio, YT Music, Mi Music, Deezer, TIDAL

2. Likes (4 apps)
SoundCloud: *Play Likes*, Anghami: *Likes*, Spotify: *Liked Songs*, Samsung Music: *Favorite tracks*

Other
TIDAL: *My collection*, iHeartRadio: *Your Library*, Mi Music: *Local songs*, Samsung Music: *Recently added*, Retro Music: *Last added*, Mi Music: *Recently played*, Samsung Music: *Play*, Retro Music: *Shuffle all*, Retro Music: *Most played*, Anghami: *My Playlists*, VLC: *Playlists*

**Comment by xmha97** [comment]
> Which shortcuts would you like to have?

# 1. Search (9 apps)
`SoundCloud` | `Spotify` | `Anghami` | `Pandora` | `iHeartRadio` | `YT Music` | `Mi Music` | `Deezer` | `TIDAL`

# 2. Likes (4 apps)
`SoundCloud` **Play Likes** | `Anghami` **Likes** | `Spotify` **Liked Songs** | `Samsung Music` **Favorite tracks**

# Other
`TIDAL` **My collection** | `iHeartRadio` **Your Library** | `Mi Music` **Local songs** | `Samsung Music` **Recently added** | `Retro Music` **Last added** | `Mi Music` **Recently played** | `Samsung Music` **Play** | `Retro Music` **Shuffle all** | `Retro Music` **Most played** | `Anghami` **My Playlists** | `VLC` **Playlists**

**Comment by xmha97** [comment]
> Which shortcuts would you like to have?

# 1. Search (9 apps)
`SoundCloud` | `Spotify` | `Anghami` | `Pandora` | `iHeartRadio` | `YT Music` | `Mi Music` | `Deezer` | `TIDAL`

# 2. Likes (4 apps)
`SoundCloud` **Play Likes** | `Anghami` **Likes** | `Spotify` **Liked Songs** | `Samsung Music` **Favorite tracks**

# Other
`TIDAL` **My collection** | `iHeartRadio` **Your Library** | `Mi Music` **Local songs** | `Samsung Music` **Recently added** | `Retro Music` **Last added** | `Mi Music` **Recently played** | `Samsung Music` **Play** | `Retro Music` **Shuffle all** | `Retro Music` **Most played** | `Anghami` **My Playlists** | `VLC` **Playlists**

**Comment by z-huang** [comment]
Wow, thanks for your research!
