### ISSUE TITLE
Sync "Your likes" from YouTube Music

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/InnerTune#206]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Keep sync the your likes playlist as an option. 
Currently using a js script to auto export the like playlist(as you cannot import directly), then import the playlist,but this take times and not stable, and cannot keep sync.
You can take reference of this repo https://github.com/pepershukov/ytm-yld .
Maybe use a webview to get the cookie and then fetch the platlist.

### Why do you want this feature?

The like function is really useful as when you like music video on youtube it can directly add to the Your likes playlist, so it will be a really handy if it can be sync and easily import it.

**Comment by z-huang** [comment]
> Maybe use a webview to get the cookie and then fetch the platlist.

So, this feature has #88 as the prerequisite. I'll mark `low priority` as well.

**Comment by z-huang** [comment]
#88 is done. You can sync "Your likes" just like other playlists.
