### ISSUE TITLE
Proxy for downloading and streaming

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#221]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. I open the app
2. I set a proxy (because YouTube is blocked in my country)
3. Content will load (but not stream or download)

### Expected behavior

Apply proxy for streaming and downloading

### Actual behavior

Proxy is not applied for streaming and downloading

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/192096469-62e3947a-4e66-4ff8-bcfc-76c7588b507b.mp4

### Music version

0.4.1-stable

### Android version

Android 12

**Comment by xmha97** [comment]
Is it difficult to implement?

**Comment by xmha97** [comment]
@z-huang Is it difficult to implement?

**Comment by z-huang** [comment]
Proxy for the player isn't too hard, but proxy for downloading is a bit tricky because Android DownloadManager doesn't have such option. I have to create a custom downloader. However, it also fixes #13.

**Comment by z-huang** [comment]
9ed1d5051cb5484dc0d01281cd76b2c2aef38147 should fix proxy for streaming.

**Comment by xmha97** [comment]
> 9ed1d5051cb5484dc0d01281cd76b2c2aef38147 should fix proxy for streaming.

Thanks.
