### ISSUE TITLE
Blank App icon in Realme Ui 3.0

### ISSUE THREAD

**Issue by YouSummoner** [z-huang/InnerTune#230]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Install the app
2. Go to phone's app drawer 

### Expected behavior

The app's icon should be shown.

### Actual behavior

Just a white box is seen in place of the app's real icon.

### Music version

0.4.1

### Android version

Android 12, Realme Ui 3.0

### Additional information

After installing the app, the icon isn't automatically added to the phone's home screen (like even other app is after installing) , instead a blank white box appears in the app drawer. Other than that, the app works normally.

**Comment by z-huang** [comment]
Can you provide the screenshot? Does this happen in 0.4.0?

**Comment by YouSummoner** [comment]
> Can you provide the screenshot? Does this happen in 0.4.0?

![Screenshot_2022-09-26-00-04-19-02_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/107224555/192159691-57bc3e3b-58a5-47c7-b5e3-36c7e5a08dd1.jpg)

**Comment by z-huang** [comment]
Does this happen in 0.4.0?

**Comment by YouSummoner** [comment]
> Does this happen in 0.4.0?

Yess in that too

**Comment by z-huang** [comment]
This doesn't happen in Android emulator, OneUI, MIUI, and I don't have the device to test. Help needed.

**Comment by YouSummoner** [comment]
> This doesn't happen in Android emulator, OneUI, MIUI, and I don't have the device to test. Help needed.

Help like what?

**Comment by z-huang** [comment]
Help by developers who can solve the bug.

**Comment by shravankumaruk** [comment]
I Have a realme UI 2.0 Android 11 Happened with me too so I restarted device and installed apk again as an update it worked that time properly try to delete any other music apps and disable equalizer.Chinese firmware always have issues with open sources dont know why Even vanced youtube my freinds Xiaomi had issues.

**Comment by z-huang** [comment]
Does his method work for other people?

**Comment by anujithpp** [comment]
> Does his method work for other people?

Nop

**Comment by anujithpp** [comment]
When I changed my default launcher to another one lawnchair the problem is fixed

**Comment by shravankumaruk** [comment]
Nice  looks like people need to change launcher or clear data/cache
