### ISSUE TITLE
Move and hide tabs

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#243]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

<img width=200 src="https://user-images.githubusercontent.com/23485114/192652103-31d30fab-4dc5-46a6-b456-497e12f0e979.jpg" />

### Why do you want this feature?

I want to move "Home" tab to the end
And hide "Playlists" tab

**Comment by Bnyro** [comment]
Very good example, indeed

**Comment by Bnyro** [comment]
I could re-implement  my code from LibreTube here if @z-huang wants me to, at least I would love to be able to get rid of some bottom navigation menu items

**Comment by z-huang** [comment]
Thanks, but I can do it myself. Which menu items do you want to hide?

**Comment by Bnyro** [comment]
I personally don't use the albums and playlist tab, would be cool to be able to hide them :)

**Comment by xmha97** [comment]
> Which menu items do you want to hide?

I want to hide Albums, Playlists and Artists tabs.

**Comment by z-huang** [comment]
> Thanks, but I can do it myself.

@Bnyro Since I may not be able to handle this issue recently, it will be great if you make a PR.😀

**Comment by Bnyro** [comment]
> > Thanks, but I can do it myself.
> 
> @Bnyro Since I may not be able to handle this issue recently, it will be great if you make a PR.😀

Sure, I'll have a look soon :)

**Comment by z-huang** [comment]
Reopen the issue because "move" feature isn't implemented.

**Comment by Bnyro** [comment]
Well, I think an option for moving them is not really needed since you can just set a default tab if you want to open a different tab when starting the app.
The code of my implementation at LibreTube is really ugly, at least I don't think it's a good idea to do it the same way here.

**Comment by z-huang** [comment]
> The code of my implementation at LibreTube is really ugly, at least I don't think it's a good idea to do it the same way here.

I've seen your code, and I think it's the only way to do so. True, it's a bit ugly, so I may not implement it right now.

**Comment by Bnyro** [comment]
> > The code of my implementation at LibreTube is really ugly, at least I don't think it's a good idea to do it the same way here.
> 
> I've seen your code, and I think it's the only way to do so. True, it's a bit ugly, so I may not implement it right now.

I can add that too if you want me too, I just didn't want to mess up your code ;)

**Comment by z-huang** [comment]
Sorry, I decide not to implement this. I think it will be fine to keep those tabs even if you don't use them.
