### ISSUE TITLE
Increase music control thumbnail resolution

### ISSUE THREAD

**Issue by pkrh39** [z-huang/InnerTune#244]
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Increase music player control's thumbnail resolution.

### Why do you want this feature?

Starting from android 13, music control thumbnail has become bigger, so current thumbnail looks too pixelated.

<img width=200 src="https://user-images.githubusercontent.com/17289367/192665642-05257ff5-c6f5-4bff-8179-33f4f1dc3eee.png" />
Music

<img width=200 src="https://user-images.githubusercontent.com/17289367/192665710-1fe3629c-d4f1-4897-ba4a-12c32f293068.png" />
Youtube

**Comment by xmha97** [comment]
I can also point to this problem:

![IMG_20220928_051124.jpg](https://user-images.githubusercontent.com/23485114/192668139-ae780c13-f67d-45cb-a66b-5a519a1bc00a.jpg)

**Comment by electr1fy0** [comment]
Some forks of Retro Music Player have this fixed I guess.
Maybe take something from there?

**Comment by electr1fy0** [comment]
Also, none of these screenshots depict how it actually looks on Android 13. These are custom ROMs enforcing the A13 media player UI. On a normal phone such as a Pixel which requires app support, it's gonna look like the old design instead of what the screenshots show.
I built the app by updating the target SDK to 33 and that seemed to fix this but the album art is still pixelated.

**Comment by z-huang** [comment]
> Some forks of Retro Music Player have this fixed I guess.
> Maybe take something from there?

Can you share the link?

**Comment by electr1fy0** [comment]
**This one:**
https://github.com/RetroMusicPlayer/RetroMusicPlayer/compare/dev...michaellee123:RetroMusicPlayer:dev

<br> 

_I'm not sure if it actually fixes it as I had a lot of trouble building the Retro with random stuff failing._

**Comment by z-huang** [comment]
I don't think it fixes the thumbnail resolution. Nothing special is seen.
I'll go back on it after I finish the work on 0.5.0.

**Comment by z-huang** [comment]
Fixed by migrating to media3.

**Comment by eglenelid-gamaliel** [comment]
![Screenshot_20230620-193516](https://github.com/z-huang/InnerTune/assets/44361826/e506f9a1-b8a6-4900-91b6-5c28959d135f)
Looks perfect, thank you so much!
