### ISSUE TITLE
Buttons in YouTube playlist and album page

### ISSUE THREAD

**Issue by Black-StellarSpectrum** [z-huang/InnerTune#260]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently I can only see my YT playlist by sharing it to the app but I want the app to be able to save that playlist in the playlist section so I can visit it anytime I want.
Something like the screenshot below:
![Screenshot_20221002-193259_Music](https://user-images.githubusercontent.com/79910450/193458848-68142dde-2789-439f-bc7d-374e6b8e86f1.png)

### Why do you want this feature?

I've been YT music for a while now and I've created many playlist there and want to add them in the app to use the app, I mostly listen to the music in my playlist so please add this option

**Comment by owencz1998** [comment]
U can search your name or u think the playlist name and the playlist will show and let's u import like that that's how I did it mate

**Comment by Black-StellarSpectrum** [comment]
> U can search your name or u think the playlist name and the playlist will show and let's u import like that that's how I did it mate 

Currently using v0.4.1 but I don't see anyway to import the playlist, I can see the playlist by sharing it from YT app but can't save it in the music app(playlist section), can you please share screenshot of where the import option might be.
Thanks

**Comment by owencz1998** [comment]
When I search for my name in the search bar is shows me my playlist 

![Screenshot_20221002_162655_Music Debug.jpg](https://user-images.githubusercontent.com/96526481/193462116-93059113-2faf-41fc-9002-c98777f9b962.jpg)

**Comment by owencz1998** [comment]
Also @z-huang is the navigation bar meant to look like that or is there a issue with it dude

**Comment by z-huang** [comment]
It shouldn't be like that. However, it's not happening in my phone and Android emulator. 🤔

**Comment by owencz1998** [comment]
Ahh ok I'm on a samsung z fold 3 only happened when I used debug version again it looks like the navigation bar is transparent almost haha

**Comment by owencz1998** [comment]
https://user-images.githubusercontent.com/96526481/193462790-a84f2d99-698d-4213-9ba0-57510128efed.mp4

**Comment by Black-StellarSpectrum** [comment]
> When I search for my name in the search bar is shows me my playlist 
> 
> ![Screenshot_20221002_162655_Music Debug.jpg](https://user-images.githubusercontent.com/96526481/193462116-93059113-2faf-41fc-9002-c98777f9b962.jpg)

I tried just searching the name of both by playlist name and the name of the person who made it but no luck can't find it via normal search it's just much easier to share the playlist from YT app to the Music app and then import the playlist!

**Comment by owencz1998** [comment]
I agree or able or copy the url link of the playlists and using the search bar also to be able find the link haha what does the playlist look like on yt music make sure that it's set to open to everyone not private then give that ago

**Comment by owencz1998** [comment]
![Screenshot_20221002_165240.jpg](https://user-images.githubusercontent.com/96526481/193463298-5a4b2a74-088b-43f1-81f2-c2444afe0060.jpg)

**Comment by z-huang** [comment]
I will add buttons in playlist and album page.

**Comment by Black-StellarSpectrum** [comment]
> I will add buttons in playlist and album page.

Thanks

**Comment by z-huang** [comment]
> Screen_Recording_20221002_164127_Music.Debug.mp4

Can you try the latest debug? Is it fixed?

**Comment by owencz1998** [comment]
There's no buttons showing when sharing playlist from yt music

![Screenshot_20221010_133740_Music Debug.jpg](https://user-images.githubusercontent.com/96526481/194868337-734e1685-cacf-47ed-bf5d-d20ba6966181.jpg)

**Comment by owencz1998** [comment]
Oh yes haha that's working perfect again

**Comment by eightyy8** [comment]
> I will add buttons in playlist and album page.

Any updates? Thanks

**Comment by z-huang** [comment]
0.5.0 will bring this update.
