### ISSUE TITLE
View albums when offline

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#276]
- Clean install of latest debug apk
- Album 100% downloaded to offline cache
- Network disconnected 
- Launching playback of cached album : network error

Network error shouldn't happen in offline mode

![Screenshot_2022-10-07-09-14-42-752_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/194495749-380d084b-ee6d-41a6-876c-6cfd3a907ccf.jpg)

**Comment by JPGuillemin** [comment]
Note : when no network (ie plane mode) : 
- Home and Artist tabs should be hidden or disabled.
- Songs tab should show only cached songs
- Albums tab should show only fully cached albums

**Comment by xmha97** [comment]
+1

**Comment by thornySoap** [comment]
Is viewing albums offline implemented now? I still get an error
