### ISSUE TITLE
Proxy authentication

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#278]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add more proxy fields (like "Port", "Username" and "Password")
# InnerTune app
![Screenshot_2022-10-08-02-18-47-741_com zionhuang music](https://user-images.githubusercontent.com/23485114/194672899-b5cd0220-dddd-40a7-9aba-5fb4ba138d93.jpg)
# Telegram app
![Screenshot_2022-10-08-02-19-31-371_org telegram messenger web](https://user-images.githubusercontent.com/23485114/194672914-300a735e-ee72-4714-be12-b5a483809d70.jpg)

### Why do you want this feature?

Because some proxies require username and password.

### Additional information

Thank you for adding my requests. 🧡

**Comment by z-huang** [comment]
Closed for being an "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)" feature.
