### ISSUE TITLE
Display albums as a grid (instead of list)

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#279]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_2022-10-08-03-41-27-420_code name monkey retromusic](https://user-images.githubusercontent.com/23485114/194677570-affed261-885a-4a99-80b2-bdf5b0f40a69.jpg)
https://github.com/RetroMusicPlayer/RetroMusicPlayer

### Why do you want this feature?

In my opinion, albums should be displayed as a table, although this is a matter of taste and you may prefer to display them as a list.

**Comment by JPGuillemin** [comment]
+1 

Yes !! 

Artists also

**Comment by mattcarter11** [comment]
Yes, that would be amazing!!!

I would have a grid selector what like Oto Music does, which would enable both the current layout and the grid layout.

<p float="left">
<img src="https://user-images.githubusercontent.com/38189440/200683543-a28517cc-1476-4011-b188-a93c3fae8a30.jpeg" width="250">
<img src="https://user-images.githubusercontent.com/38189440/200683548-f26e4361-24b4-4d81-b40c-ecf37746c3ad.jpeg" width="250">
</p>

**Comment by z-huang** [comment]
I'll do it after migrating to Compose.

**Comment by TheTrashCrafter** [comment]
Is this still going to be added? The compose version is great btw.
