### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by Pentaphon** [z-huang/InnerTune#305]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The dev graciously went with Innertune for the name of this app! Innertune needs a new icon and the dev should ask people with icon skills if they want to help him with making a new one! If you have any icon creation skills and want to contribute to this project, submit it here and maybe the dev will accept your icon!

### Why do you want this feature?

Because the [current icon](https://raw.githubusercontent.com/z-huang/music/dev/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png) is way too generic!

**Comment by airon90** [comment]
To be honest I love the actual one

**Comment by Pentaphon** [comment]
> To be honest I love the actual one

I think the community can come up with something better.

**Comment by NeeRaj-2401** [comment]
@z-huang can u please pin this thread.. so that community can easily find and come up with their ideas

**Comment by Radical4ever** [comment]
I mean the icon is good maybe the only thing that would make it great is that if it is a  color dynamic one

**Comment by Pentaphon** [comment]
> I mean the icon is good

It's really not. It's actually below average in terms of icons that you see on most projects. It's just the material icon for a music note. Nothing more. That's why somebody needs to come up with something nicer and more unique.

**Comment by Radical4ever** [comment]
This one could be a start.It reminds me to the classic android music player. And i think with a redesign of material you and dynamic color icon would make it fine and originial

![Bokehlicia-Captiva-Multimedia-audio-player-1](https://user-images.githubusercontent.com/83252104/197000359-8c6fd329-12c6-4815-89f6-be66426d9e84.png)

**Comment by Pentaphon** [comment]
> This one could be a start.It reminds me to the classic android music player.

The icon is ok but this is not a record or oldies player. I was thinking more of something with a big, bold I for Innertune combined with things like headphone-shaped icon or a play button.

**Comment by Gi-R** [comment]
This is what I think is a suitable icon for the app, the dot on the i has headphones on it, like suggested by @Pentaphon, the first one is more basic, only has the i, the second also have the T on the background with a different color. These colors are just for reference to show shapes and can be changed. I think this icon can be a good fit for Material You dynamic icon. Shape is also not final since every OEM or user can decide the shape of the icons.
![innertune no T](https://user-images.githubusercontent.com/117234693/199598077-d1a2fc54-2395-4af9-9acb-3036ea6c2d9b.png)
![innerTune](https://user-images.githubusercontent.com/117234693/199598080-e95be38e-3bb0-40bc-8116-a0e4785dcb92.png)

**Comment by Pentaphon** [comment]
> This is what I think is a suitable icon for the app, the dot on the i has headphones on it, like suggested by @Pentaphon, the first one is more basic, only has the i

I like the first one better, but I do think we need some color to make the icon really stand out. The Youtube red might be a good starting point but I don't know if the dev wants his app to be too Youtube-y.

**Comment by owencz1998** [comment]
What about the 1st one and add a red ring inside the black part

**Comment by Gi-R** [comment]
I think that to keep the icon cohererent to the rest of the app, a good choice could be the standard nav bar color. Youtube red make sense because it's an alternative YT Music client, but don't match the vibe of the app since it's made with a different design in mind

**Comment by Pentaphon** [comment]
> Youtube red make sense because it's an alternative YT Music client, but don't match the vibe of the app since it's made with a different design in mind

I totally understand and I would be fine with using Youtube's red color for the icon but I just wasn't sure if the dev would be fine with it. I think @z-huang should let this thread know what kind of icon he would like (if he has any in mind) and then somebody with some graphics skills can bring it to life.

**Comment by Gi-R** [comment]
Yesterday, talking with a friend, we had an idea, it's a prototype but I think it's too good to not be shared. Colors are from the navigation bar with no custom color applied and with Material You turned off
![Rounded](https://user-images.githubusercontent.com/117234693/199955859-625089b2-892f-43d5-a72c-cc202d0751e0.png)![No shape](https://user-images.githubusercontent.com/117234693/199955887-5aa48e84-eadf-405e-94cb-864391b8e238.png)
First one: rounded icon, how it should look like on a device like a Pixel, Second one background fully coloured to allow adaptive icon and avoid the circle inside squircle effect

**Comment by z-huang** [comment]
Actually, I don't want red, but I like the idea of showing "i" implicitly in the icon. @Gi-R The design is great! The tilted dot at the top of "i" makes it easier to know it's a person listening to music. It would be better if all corners can be rounded. This will be a possible candidate.

**Comment by Gi-R** [comment]
With the help of a friend I did the vectorized icon and I tested it on my phone both as circular icon and with the icon adapting to the "Samsung squircle".
![Screenshot Circle](https://user-images.githubusercontent.com/117234693/200185069-1de70ae1-9546-448a-bcff-6f2cc8092cce.jpg)
![Screenshot OneUI](https://user-images.githubusercontent.com/117234693/200185078-344764c2-710c-41de-8c7b-9147bd4f30ea.jpg)
I improved the icon using material design icons since the app use Material You and doubled the dimension of icons and text because they were too small.

**Comment by owencz1998** [comment]
I think only the middle should be used as the icon

**Comment by Radical4ever** [comment]
> I think only the middle should be used as the icon

yeah i think i would look better like that.

**Comment by airon90** [comment]
Once the icon is chosen, a monochrome version for Android 13+ should be added too.
See https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by owencz1998** [comment]
I think once it's been sharpened up and redone probably as this is just a sample I think this looks good enough obviously this is just my preference :)

![Photo_1667764325618.png](https://user-images.githubusercontent.com/96526481/200191927-041f28ef-f9e1-499f-8123-7398338f70c9.png)

**Comment by owencz1998** [comment]
Or with a little of the the color around 

![Polish_20221106_200026672.png](https://user-images.githubusercontent.com/96526481/200192266-ec8be816-13bc-4da9-a791-ba6d59d521ab.png)

**Comment by owencz1998** [comment]
![Screenshot_20221106_201836_One UI Home.jpg](https://user-images.githubusercontent.com/96526481/200193054-c8091860-df06-4f9c-a23e-6642437a666f.jpg)

**Comment by Radical4ever** [comment]
> I'd say one of these 2 I'd probably go with the left as my preference but everyone has there's:)
> 
> ![Screenshot_20221106_201836_One UI Home.jpg](https://user-images.githubusercontent.com/96526481/200193054-c8091860-df06-4f9c-a23e-6642437a666f.jpg)

Left one looks good i like this!

**Comment by Gi-R** [comment]
![Musicman Round](https://user-images.githubusercontent.com/117234693/200414230-550fe029-3f07-4d07-8e95-de58581b567a.png)Rounded Icon
![Musicman Adaptive](https://user-images.githubusercontent.com/117234693/200415069-b8dd87ee-ed15-45a4-afc5-e7ec36e94aa9.png)Adaptive Icon
![Musicman Android 13](https://user-images.githubusercontent.com/117234693/200414783-72705aee-7c92-4447-a871-4b577e831a65.png)Monochrome for Android 13+

**Comment by Gi-R** [comment]
![Musicman Round Rounded](https://user-images.githubusercontent.com/117234693/200638593-f3bb36db-868a-4282-9736-00b73b4c9a32.png) ![Musicman Adaptive Rounded](https://user-images.githubusercontent.com/117234693/200638631-77d23663-430a-41a9-99b4-64b30586b555.png) ![Musicman Android 13 Rounded](https://user-images.githubusercontent.com/117234693/200638644-0e88fafc-42f2-4aec-a338-ead91f69704d.png)
An alternative version more rounded

**Comment by Radical4ever** [comment]
> ![Musicman Round Rounded](https://user-images.githubusercontent.com/117234693/200638593-f3bb36db-868a-4282-9736-00b73b4c9a32.png) ![Musicman Adaptive Rounded](https://user-images.githubusercontent.com/117234693/200638631-77d23663-430a-41a9-99b4-64b30586b555.png) ![Musicman Android 13 Rounded](https://user-images.githubusercontent.com/117234693/200638644-0e88fafc-42f2-4aec-a338-ead91f69704d.png) An alternative version with rounded corners

Forget what i said this one is better!

**Comment by Gi-R** [comment]
I just noticed I forgot to tilt the dot...

**Comment by owencz1998** [comment]
Top one is the best one in my opinion the rounded one

**Comment by Gi-R** [comment]
> Top one is the best one in my opinion the rounded one

From what I understood reading the android guidelines, these 3 type of icons are required, the rounded one for the launchers and devices that uses rounded icons, the second one allow to keep the design of the rounded icon but the shape of the icon can be different from a circle, the user can use for example a pebble shaped icon theme, the design of the icon will stay the same, the last one is required for theming with Material You (Android 13+)

**Comment by z-huang** [comment]
Firstly, @Gi-R thanks for your work!

![Musicman Adaptive Rounded](https://user-images.githubusercontent.com/117234693/200638631-77d23663-430a-41a9-99b4-64b30586b555.png)
1. This wastes some space, so I think we should remove the circle background and let the launcher decide the background shape.
2. Also, since we have no background, the adaptive color should apply to the "i"

However, since the background is removed, is the border of the bottom of the "i" going to stay the same (I mean the arc)? The bottom can be flat, and when the launcher uses rounded icons, it will have the arc border.

**Comment by VelocityDesign** [comment]
I don't like this icon as much. Can we add the option to keep the classic icon?

**Comment by Pentaphon** [comment]
> I don't like this icon as much. Can we add the option to keep the classic icon?

This isn't necessarily going to be the final icon. Somebody out there could come up with something better and z-huang could go with that instead. This thread could end up going on for months before deciding on a final icon and it's totally up to the dev.

**Comment by VelocityDesign** [comment]
> > I don't like this icon as much. Can we add the option to keep the classic icon?
> 
> This isn't necessarily going to be the final icon. Somebody out there could come up with something better and z-huang could go with that instead. This thread could end up going on for months before deciding on a final icon and it's totally up to the dev. 
> 
> You have the word "design" in your username. Can you design something better?

Possibly

**Comment by Gi-R** [comment]
Sorry guys if I'm not active as before, I'm a bit busy right now, anyway I'm still working on improving the icon but slowly, I'll post here any relevant update when possible.
@VelocityDesign it would be great if you can share your ideas for the icon, even if they are sketches or not perfect, I'm not a professional designer (I think my designs shows that are made from who treat this more like an hobby and have a lot to learn) but i discovered this project and i decided to share my idea for the icon, maybe your idea is way better than mine or we can be inspired by each other ideas and arrive to the perfect icon :)

**Comment by Pentaphon** [comment]
> Possibly

Then I highly suggest you give it a shot. This thread is meant to attract designers who wish to donate an icon to the project by letting them showcase their ideas.

**Comment by Gi-R** [comment]
Guys I'm back, I did some testing on the icon
![Screenshot_20221118_185440](https://user-images.githubusercontent.com/117234693/202770824-cd30a566-f4a3-483a-9a7d-cb99c49a1e1b.png) adaptive shape
![Screenshot_20221118_184308](https://user-images.githubusercontent.com/117234693/202770846-b6d91c3b-22a3-495e-a5d4-ceeddcb12723.png) adaptive color with dark mode
![Screenshot_20221118_184035](https://user-images.githubusercontent.com/117234693/202770861-867c0843-9de2-4bfd-8a36-26bdca21bb23.png) adaptive color with light mode
![Screenshot_20221118_185704](https://user-images.githubusercontent.com/117234693/202771357-d7576529-0386-4260-b6b4-7bcb461a42bc.png) round icon

**Comment by Gi-R** [comment]
>
> 2. Also, since we have no background, the adaptive color should apply to the "i"
> 
I tried, but it seems that Android chooses where to apply the color based on dark or light mode

**Comment by z-huang** [comment]
Okay, can you make the head tilted?

**Comment by Gi-R** [comment]
Already working on it, I'm tryng different versions to pick the best one

**Comment by Gi-R** [comment]
![Screenshot_20221119_180151](https://user-images.githubusercontent.com/117234693/202862983-cc2f39e5-2c50-4fe5-94ca-02990cbe18a6.png)
![Screenshot_20221119_180210](https://user-images.githubusercontent.com/117234693/202863000-74863fa5-0524-422a-b02d-f1717e87f1b1.png)
![Screenshot_20221119_180225](https://user-images.githubusercontent.com/117234693/202863012-12f1c00a-af5f-45a6-9278-26aeb620dfee.png)
![Screenshot_20221119_180244](https://user-images.githubusercontent.com/117234693/202863089-79ec314e-4d89-49e5-9bab-75459ca30860.png)
![Screenshot_20221119_180329](https://user-images.githubusercontent.com/117234693/202863123-2e39399c-41eb-4110-91b9-393b15c087bc.png)

**Comment by eightyy8** [comment]
Looks like chess with hair

**Comment by Gi-R** [comment]
Hi all, a lot of time have passed and I don't have any update on my idea of icon for the app, today reorganizing files on my pc I found the final icon files, since I don't plan to work on it for now, and I'm storing all the files, I'm uploading everything I used to create the final icons like in the latest tests. Feel free to use if needed
[InnerTune.zip](https://github.com/z-huang/InnerTune/files/10366457/InnerTune.zip)
Thanks everyone who took part in this thread

**Comment by EisregenHoho** [comment]
Honestly nah, just keep it. I love how simplistic it currently is. I'd even be fine with just text saying innertune under the music note.

**Comment by n-ce** [comment]
![Project 6_2](https://user-images.githubusercontent.com/69345507/216246714-a7c88251-5bb2-4124-8820-20f29b712e0f.png)

**Comment by eightyy8** [comment]
> ![Project 6_2](https://user-images.githubusercontent.com/69345507/216246714-a7c88251-5bb2-4124-8820-20f29b712e0f.png)
> 

Looks great up close, but it needs to be perceivable from a small icon on a home screen. Maybe simplify, more? Otherwise it still looks nice 👌

**Comment by n-ce** [comment]
<img width=150 src="https://user-images.githubusercontent.com/69345507/216388215-c55af706-f0d6-406b-8867-d47dc25282b6.png">

**Comment by z-huang** [comment]
@n-ce First of all, thanks for your contribution. But, what's your idea for this icon? How is it related to InnerTune?

**Comment by n-ce** [comment]
> @n-ce First of all, thanks for your contribution. But, what's your idea for this icon? How is it related to InnerTune?

@z-huang , inner Tune => tune inside my mind => so my idea is to have an icon displaying a simple face impressed by a tune inside.

**Comment by eightyy8** [comment]
![677925b2-b4db-4787-8911-ce05807d9396.png](https://user-images.githubusercontent.com/64216434/216650570-8849a6da-5160-4a99-a026-fc8b2d7c26b3.png)

here is mine, pls don judge.

**Comment by EisregenHoho** [comment]
Amogus

**Comment by Pentaphon** [comment]
> inner Tune => tune inside my mind => so my idea is to have an icon displaying a simple face impressed by a tune inside.

Inner = refer to innertube, the software that connects to Youtube music
Tune = music but sounding close to "tube" since this is a Youtube music player

Basically, your icon should have something to do with music (like headphones on a head) or Youtube (some symbol that relates to the original Youtube type in some way like being red.

**Comment by EisregenHoho** [comment]
> ![677925b2-b4db-4787-8911-ce05807d9396.png](https://user-images.githubusercontent.com/64216434/216650570-8849a6da-5160-4a99-a026-fc8b2d7c26b3.png)
> 
> here is mine, pls don judge.

Again amogus

**Comment by n-ce** [comment]
@Pentaphon I think ghost's icon comes closest with that set of ideas, maybe we need to continue to improve on that?


<img width=100 src="https://user-images.githubusercontent.com/69345507/216673536-04911193-63b6-4dc3-b3c9-72a5d6f6408b.png">
With that being said here's my final attempt.

**Comment by Pentaphon** [comment]
> maybe we need to continue to improve on that?

I think people should just keep submitting icons until the dev sees one he wants to use.

**Comment by eightyy8** [comment]
> <img width=100 src="https://user-images.githubusercontent.com/69345507/216673536-04911193-63b6-4dc3-b3c9-72a5d6f6408b.png">
>

InnerToilet

**Comment by quazar-omega** [comment]
Here's my _stab_ <sup>ඞ</sup> at it
|              | Flat | Flat (note) | Perspective | Perspective (note) |
|--------------|------|-------------|-------------|--------------------|
| Red YouTube  | <img alt="innertune-logo" src="https://user-images.githubusercontent.com/56311398/216730223-b6e4c82f-4013-4079-a26e-2ca4a653dc95.svg" height="100px">|   <img alt="innertune-logo-note" src="https://user-images.githubusercontent.com/56311398/216730293-b4d7345c-8dc7-4c9e-a4ce-b39a894f6b64.svg" height="100px"> |    <img alt="innertune-logo" src="https://user-images.githubusercontent.com/56311398/216730361-2a5181de-9b9e-41f0-ac3f-092b6c33c6e1.svg" height="100px">     |     <img alt="innertune-logo-note" src="https://user-images.githubusercontent.com/56311398/216730486-0be7419a-6d2e-4fa7-941d-c7ee7a69c225.svg" height="100px">        |
| Random color |  <img alt="innertune-logo" src="https://user-images.githubusercontent.com/56311398/216731490-f53ccfa5-1e15-4a0e-a3f5-4a9e10c161bd.svg" height="100px">   |   <img alt="innertune-logo-note" src="https://user-images.githubusercontent.com/56311398/216731868-6f3f5b9d-301b-4c8a-a4c0-ba209c8656b5.svg" height="100px">    |   <img alt="innertune-logo" src="https://user-images.githubusercontent.com/56311398/216732148-33bf4d33-bccd-40fc-83c6-16640d2c4913.svg" height="100px">     |  <img alt="innertune-logo-note" src="https://user-images.githubusercontent.com/56311398/216732428-d2a964db-c6a3-4593-a303-caf50949c711.svg" height="100px">  |

**Comment by VelocityDesign** [comment]
The person in circle concept looks too much like https://opensourcedesign.net/

**Comment by quazar-omega** [comment]
@VelocityDesign Oh, that was supposed to be an "i" actually

**Comment by VelocityDesign** [comment]
> @VelocityDesign Oh, that was supposed to be an "i" actually

Ah, okay. The concept by [ghost] was also similar.

**Comment by Radical4ever** [comment]
> 

Love the flat one!

**Comment by quazar-omega** [comment]
Glad you like it, that version was the first that came to mind in fact, it has
- a stack of disks (music)
- i (app initial)
- the disks overlapping form something like a wave, could be interpreted as sound or signal since it uses an online platform

Though now that I look at all of them, I really don't like them anymore, they look amateurish (.. well, I am an amateur), maybe the idea is good for someone else's rendition.

Ghost's icon is actually pretty solid technically, though I don't think the symbols are very representative themselves

**Comment by cat3na** [comment]
I actually really like @quazar-omega's design (particularly the flat note version), it feels very appropriate for a music app. 

A while ago I sketched a sort of life-ring design with a play button in the center ("inner tube")... I don't think it's anywhere near high-quality enough to post, but that was one of my design ideas. The CD design is an interesting one too. I like the idea of having the icon be based around a circle - I feel like that's pretty typical for music apps (Spotify, YT Music, etc).

**Comment by quazar-omega** [comment]
Oh thanks! Anyway I think you should post your idea as well, even if you plan to reiterate on the design it would still be valuable to share the rough idea with everyone, it sounds interesting

**Comment by amrmrni** [comment]
Ghost's icon looks good but I think it's better that the "person" doesn't touch the icon borders like pretty much every themed icon.

Maybe a youtube music like icon would be nice? Youtube music has a pretty nice icon especially as a themed icon. Maybe something like that?

**Comment by n-ce** [comment]
@amrmrni 

|xxMainx|Themed|xB&Wxx
|:-:|:-:|:-:|
|  ![IMG_20230301_233641](https://user-images.githubusercontent.com/69345507/222224909-c923e027-896e-422f-b72f-61c648462aaa.png) | ![IMG_20230301_233351](https://user-images.githubusercontent.com/69345507/222224741-6db7be77-6a73-4e78-9886-ccef36c17660.png) | ![IMG_20230301_233259](https://user-images.githubusercontent.com/69345507/222225081-aa9a58d7-6867-44c5-bd81-0f38d58e0c9b.png)|

**Comment by amrmrni** [comment]
> @amrmrni 
> 
> |xxMainx|Themed|xB&Wxx
> |:-:|:-:|:-:|
> |  ![IMG_20230301_233641](https://user-images.githubusercontent.com/69345507/222224909-c923e027-896e-422f-b72f-61c648462aaa.png) | ![IMG_20230301_233351](https://user-images.githubusercontent.com/69345507/222224741-6db7be77-6a73-4e78-9886-ccef36c17660.png) | ![IMG_20230301_233259](https://user-images.githubusercontent.com/69345507/222225081-aa9a58d7-6867-44c5-bd81-0f38d58e0c9b.png)|
> 

Looks nice, how would the themed icon look like?

**Comment by n-ce** [comment]
> Looks nice, how would the themed icon look like?

Had to make a different variant for the Material You icons

|Main|Light|Dark-|
|:-:|:-:|:-:|
|![IMG_20230302_130718](https://user-images.githubusercontent.com/69345507/222363615-fcb1f391-b84e-47b2-8ba8-ea253a52a171.png)| ![IMG_20230302_130930](https://user-images.githubusercontent.com/69345507/222363756-b9bf0f06-f7f9-404c-ae1f-295f6354ae14.png)|![IMG_20230302_131019](https://user-images.githubusercontent.com/69345507/222363820-b8018c87-7839-4aec-ba11-61be74ea4e08.png)|

**Comment by dortlanders** [comment]
> > Looks nice, how would the themed icon look like?
> 
> Had to make a different variant for the Material You icons, this one uses the same technique as default ytmusic icon.
> 
> Main	Light	Dark-
> ![IMG_20230302_130718](https://user-images.githubusercontent.com/69345507/222363615-fcb1f391-b84e-47b2-8ba8-ea253a52a171.png)	![IMG_20230302_130930](https://user-images.githubusercontent.com/69345507/222363756-b9bf0f06-f7f9-404c-ae1f-295f6354ae14.png)	![IMG_20230302_131019](https://user-images.githubusercontent.com/69345507/222363820-b8018c87-7839-4aec-ba11-61be74ea4e08.png)

I really like this design! Resembles that it uses ytm, but its still original

**Comment by eightyy8** [comment]
> |Main|Light|Dark-|
> |:-:|:-:|:-:|
> |![IMG_20230302_130718](https://user-images.githubusercontent.com/69345507/222363615-fcb1f391-b84e-47b2-8ba8-ea253a52a171.png)| ![IMG_20230302_130930](https://user-images.githubusercontent.com/69345507/222363756-b9bf0f06-f7f9-404c-ae1f-295f6354ae14.png)|![IMG_20230302_131019](https://user-images.githubusercontent.com/69345507/222363820-b8018c87-7839-4aec-ba11-61be74ea4e08.png)|
> 

Simple yet identifiable. This should be great a icon for InnerTune.

**Comment by Pentaphon** [comment]
> Simple yet identifiable. This should be great a icon for InnerTune.

Agreed but the main icon should lose the gradient. People should vote on different colors since I don't think the current colors work well.

**Comment by amrmrni** [comment]
> > Looks nice, how would the themed icon look like?
> 
> Had to make a different variant for the Material You icons, this one uses the same technique as default ytmusic icon. 
> 
> |Main|Light|Dark-|
> |:-:|:-:|:-:|
> |![IMG_20230302_130718](https://user-images.githubusercontent.com/69345507/222363615-fcb1f391-b84e-47b2-8ba8-ea253a52a171.png)| ![IMG_20230302_130930](https://user-images.githubusercontent.com/69345507/222363756-b9bf0f06-f7f9-404c-ae1f-295f6354ae14.png)|![IMG_20230302_131019](https://user-images.githubusercontent.com/69345507/222363820-b8018c87-7839-4aec-ba11-61be74ea4e08.png)|
> 

Listen, I LOVE IT! It's amazing.  I actually  love the light/dark versions. For the gradient one we could maybe choose a different  colour? I think innertube needs a default colour for non material you.

**Comment by n-ce** [comment]
> Agreed but the main icon should lose the gradient. People should vote on different colors since I don't think the current colors work well.

I agree about the color, i just put it randomly. I personally think it could be anything but not blue (a lot of apps are blue) and red (well yt). I'm not too sure about loosing the gradient because that is also a factor which makes it look less generic, it does need some more refinements though.
![App store icons are so cool](https://www.apple.com/v/app-store/b/images/developers/hero__fpyktigxzia2_large_2x.jpg)

**Comment by n-ce** [comment]
|MonoColor|TwoColors|GradientFG|GradientBG|
|:-:|:-:|:-:|:-:|
|![Project 14_1](https://user-images.githubusercontent.com/69345507/222882151-c0bd8ed3-9a12-49e3-9c10-ebe8dac310df.png)|![Project 14_2](https://user-images.githubusercontent.com/69345507/222882176-835f9553-b4b4-4ba3-b118-99fdb418f767.png)|![Project 13](https://user-images.githubusercontent.com/69345507/222882186-8627cd2d-fb7b-464f-8afd-2ea65329cc01.png)|![Project 14](https://user-images.githubusercontent.com/69345507/222882214-ec55f224-7e8f-45b9-8177-6494012a4ff9.png)|

**Comment by eightyy8** [comment]
> |MonoColor|TwoColors|GradientFG|GradientBG|3rdVariant|
> |:-:|:-:|:-:|:-:|:-:|
> |![Project 14_1](https://user-images.githubusercontent.com/69345507/222882151-c0bd8ed3-9a12-49e3-9c10-ebe8dac310df.png)|![Project 14_2](https://user-images.githubusercontent.com/69345507/222882176-835f9553-b4b4-4ba3-b118-99fdb418f767.png)|![Project 13](https://user-images.githubusercontent.com/69345507/222882186-8627cd2d-fb7b-464f-8afd-2ea65329cc01.png)|![Project 14](https://user-images.githubusercontent.com/69345507/222882214-ec55f224-7e8f-45b9-8177-6494012a4ff9.png)|![IMG_20230304_151832](https://user-images.githubusercontent.com/69345507/222892599-2ecf3757-d879-43ce-a7bf-5a31c02a54cc.png)
> 
>

Perfect! Especially the 3rd variant, it doesn't have to be complex.

@z-huang opinions?

**Comment by Pentaphon** [comment]
> Perfect! Especially the 3rd variant, it doesn't have to be complex.

The 3rd one is definitely going in the right direction. The off center gradient is much better and more eye catching.

**Comment by VelocityDesign** [comment]
Maybe round those corners a little bit more to help match material you better?

**Comment by n-ce** [comment]
> Maybe round those corners a little bit more to help match material you better?

<img width="200" src="https://user-images.githubusercontent.com/69345507/223338215-c0c81209-1469-48ab-982e-95995245838e.png">

**Comment by VelocityDesign** [comment]
Awesome. Could you upload some SVGs?

**Comment by ctntt** [comment]
I've attempted making SVGs. 
![InnerTune 1](https://user-images.githubusercontent.com/115667885/229612518-87de6945-3716-48e9-b80a-bdb552103d48.svg)
![InnerTune](https://user-images.githubusercontent.com/115667885/229612541-36e72586-9e91-497a-a125-73e0f2560b27.svg)

**Comment by itsmmt305** [comment]
![ic_launcher_round](https://user-images.githubusercontent.com/94820934/229873045-be353e1d-a91c-4ce2-b464-5f9741a131e3.png)
id recommend going with something like this.. or maybe building something upon this. the yt music colors and a hint of its icon.

**Comment by MariusKr** [comment]
I had an idea, so I quickly tried it out:

Monochrome | Material You example | Material You example (night)
------ | ------ | ------
![monochrome](https://github.com/z-huang/InnerTune/assets/23560668/68fd4d4c-3055-44d3-b1f0-fd778f3087c8) | ![blue](https://github.com/z-huang/InnerTune/assets/23560668/d70a2d25-7536-4b64-ade4-5fd611918101) | ![blue_night](https://github.com/z-huang/InnerTune/assets/23560668/b068c3a3-270f-4e9f-a215-a9bc97ab318d)

It's close enough to the current icon and other music players to be quickly recognizable (and maybe satisfy the people who don't want a new icon?), but it has a certain uniqueness to not look too generic.
The "idea" was actually to represent the letters I and T (**I**nner**T**ube) as a musical note. To me the T looks more like a volume slider now, but that works as well, I guess.

Android XML file: [innertune_monochrome.zip](https://github.com/z-huang/InnerTune/files/11614120/innertune_monochrome.zip)

**Comment by itsmmt305** [comment]
> I had an idea, so I quickly tried it out:
> 
> Monochrome	Material You example	Material You example (night)
> ![monochrome](https://user-images.githubusercontent.com/23560668/242274797-68fd4d4c-3055-44d3-b1f0-fd778f3087c8.png)	![blue](https://user-images.githubusercontent.com/23560668/242274800-d70a2d25-7536-4b64-ade4-5fd611918101.png)	![blue_night](https://user-images.githubusercontent.com/23560668/242274801-b068c3a3-270f-4e9f-a215-a9bc97ab318d.png)
> It's close enough to the current icon and other music players to be quickly recognizable (and maybe satisfy the people who don't want a new icon?), but it has a certain uniqueness to not look too generic. The "idea" was actually to represent the letters I and T (**I**nner**T**ube) as a musical note. To me the T looks more like a volume slider now, but that works as well, I guess.
> 
> Android XML file: [innertune_monochrome.zip](https://github.com/z-huang/InnerTune/files/11614120/innertune_monochrome.zip)

that looks dope!! also, fitting

**Comment by z-huang** [comment]
Thanks for everyone's proposal and comments. I'm grateful that you have come up with so many ideas. Finally, I have to make a choice, and I'll use @MariusKr's icon because it's really simple and have "IT" on it.

**Comment by EisregenHoho** [comment]
> Thanks for everyone's proposal and comments. I'm grateful that you have come up with so many ideas. Finally, I have to make a choice, and I'll use @MariusKr's icon because it's really simple and have "IT" on it.

Great choice! I wouldve done the same the icon is really cool

**Comment by quazar-omega** [comment]
Agreed, it's on point

**Comment by itsmmt305** [comment]
> Thanks for everyone's proposal and comments. I'm grateful that you have come up with so many ideas. Finally, I have to make a choice, and I'll use @MariusKr's icon because it's really simple and have "IT" on it.

yayyyyy grreat
