### ISSUE TITLE
Player notification shows without any queued song

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#307]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Run the app

### Expected behavior

The player notification doesn't show

### Actual behavior

The player notification shows without any queued song

### Screenshots/Screen recordings

![Screenshot_20221015-203704_InnerTune_Debug](https://user-images.githubusercontent.com/50188628/195986863-615283f3-d85b-4e53-b4e3-4194e5205004.png)

### Music version

0.4.1-Debug

### Android version

Android 10

**Comment by Sdarfeesh** [comment]
Btw, it won't happen if the persistent queue is disabled

**Comment by z-huang** [comment]
Does it happen everytime if persistent queue is enabled?

**Comment by Sdarfeesh** [comment]
> Does it happen everytime if persistent queue is enabled?

Yes

**Comment by z-huang** [comment]
Well, in my phone, it just happens sometimes. Let's see if other users have the same problem.

**Comment by owencz1998** [comment]
Nothing from my side mate seems to work fine for me
