### ISSUE TITLE
Download from YouTube item menu

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#317]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search a artist
2. Download top music from artist
3. Crash

### Expected behavior

Download music

### Actual behavior

Crash app

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/196036573-c4094ef7-cf21-42ff-9bfc-176adf2032ec.mp4

### Music version

0.4.2

### Android version

Android 12

**Comment by z-huang** [comment]
Ah, download from YouTube items isn't implemented.
