### ISSUE TITLE
Song downloaded twice

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#320]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

download one or more Songs from an Album
then go to the Album : add the Album to collection
all Songs from Album are downloaded, including Songs previously downloaded

### Expected behavior

Songs shouldn't be downloaded twice

### Actual behavior

Songs are downloaded twice

### Music version

0.4.2

### Android version

12

**Comment by z-huang** [comment]
Is auto-download enabled in your settings?

**Comment by owencz1998** [comment]
@z-huang wouldn't the duplication issue I posted a while ago help with this issue so if any duplications are added or about to download your promoted with a message with the option to delete duplicate.

**Comment by JPGuillemin** [comment]
auto-download is enabled for library addition
auto-download is NOT enabled for song complete playback

Anyway (as a developer, but not an Android dev) I would suggest that it's related to not using a strong qualifier as the index of downloads (song UID)

**Comment by z-huang** [comment]
Can you provide screen record?

**Comment by JPGuillemin** [comment]
It's even worst than what I thought , seems that songs are downloaded 3 times.
![Uploading Screenshot_2022-10-17-07-25-58-829_com.zionhuang.music.debug.jpg…]()

**Comment by JPGuillemin** [comment]
![Screenshot_2022-10-17-07-31-27-452_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/196096707-15434b5c-38e9-4959-ba68-5cf5a867d4d4.jpg)
![Screenshot_2022-10-17-07-32-07-714_com google android documentsui](https://user-images.githubusercontent.com/55490396/196096722-b9e2077a-62be-4d41-8135-1669ae65c2e6.jpg)

**Comment by z-huang** [comment]
Okay, I think the solution requires a new downloader (#13). I keep this issue for so long because I think it's a lot of work and also because MIUI EU has an accelerator in the built-in downloader that makes downloads fast. 😉

**Comment by lovelilke** [comment]
How about this library
https://github.com/lingochamp/FileDownloader
