### ISSUE TITLE
Improve UI in split-screen mode

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#328]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the app
2. Play music
3. Activate split-screen mode

### Expected behavior

See the next track button.

### Actual behavior

The next track button will not appear.

### Screenshots/Screen recordings

![Screenshot_2022-10-18-09-14-53-233_com zionhuang music](https://user-images.githubusercontent.com/23485114/196346440-642b637a-72b3-45c4-9030-fba55c6adf2a.jpg)

### Music version

0.4.2

### Android version

Android 12

**Comment by z-huang** [comment]
I won't support split screen mode. I think there's no need to use split screen mode for this app. Just find something you want to listen, and leave it in the background. Also, the space isn't enough to show all media control buttons.
