### ISSUE TITLE
Add Lyrics

### ISSUE THREAD

**Issue by mjain234** [z-huang/InnerTune#331]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Btw first, got to heard about this app recently and loved this app.
Also, if you can add lyrics feature in this app, then it will be great

### Why do you want this feature?

Just a needful feature, so thought of sharing it.

**Comment by z-huang** [comment]
Duplicate of #76
