### ISSUE TITLE
Now Playing notification: Improvements

### ISSUE THREAD

**Issue by ItamiWasTaken** [z-huang/InnerTune#333]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The Now Playing notification should have a more minimal look, taking full advantage of all available space in a neat way, see provided example
![YouTube-Music-Android-13-player-3](https://user-images.githubusercontent.com/99271684/196554414-463cf515-7deb-48a7-9a1d-eedf3f9294a9.jpg)
the loop and shuffle buttons in provided example could be customizable in the settings

### Why do you want this feature?

currently, everything just seems so cluttered,
![Screenshot_20221018-180238](https://user-images.githubusercontent.com/99271684/196553820-2ccaeb04-4642-4c20-94ee-9c94997c3cf9.png)

**Comment by z-huang** [comment]
In my view, notification buttons exist for "quick and frequent action". If you hear a song you like, you just swipe down the screen, click the "add to library" or "like" button, done. But shuffle and repeat buttons aren't used that frequently. You may not use these two buttons over and over when hearing a song. Play/pause, skip previous and skip next are the three must for notification buttons, and there are at most 5 buttons that can show in the notification, so there are two left to customize. Without shuffle and repeat buttons, all I can think of and all I need it add to library and like buttons. If you want other buttons, you can propose.
I don't know how to add a play/pause button like YT Music and how to make the skip previous button display at left. At least I don't see that in ExoPlayer's PlayerNotification API.

**Comment by z-huang** [comment]
Fast-forward and rewind can be achieved by the notification seek bar, or double tap in the artwork in the player view #96 (not implemented), so they don't need buttons. Therefore, I think the notification is good enough now. If you have any idea, comment below.

**Comment by urmomsangus** [comment]
In my opinion, the add-and-remove from library button should be moved, removed, or have the option to disable, in the notification area.

It's to the right of "next track" which poses the possibility that people that use their right thumb will accidentally press it. 

Please consider at least adding a huge space buffer between the controls most likely to be used frequently and those you don't want to have unintended touches.

**Comment by urmomsangus** [comment]
@z-huang a toggle in settings for the user to disable would be nice, if possible.

I'm more worried about accidentally removing something from the library than adding. But I'm just one user and everyone has different uses and needs. 

I appreciate all you've done with the app. I can finally get rid of a big name app I was using.

**Comment by ItamiWasTaken** [comment]
If you look at ViMusic, that now has the notification player I am referring to

**Comment by ItamiWasTaken** [comment]
Ahh alright, thank you for looking @z-huang

**Comment by z-huang** [comment]
@urmomsangus Added the option to hide buttons in player notification in a5b37e61cbed56f5b7ac734046f1e73dec86ec7c.

**Comment by urmomsangus** [comment]
@z-huang you're the best. Thanks.
