### ISSUE TITLE
An Option to Toggle "Kill player service"

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#335]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add an option to toggle "Kill player service when app is removed from recent apps"

### Why do you want this feature?

I want to play the music in the background

**Comment by z-huang** [comment]
If it's playing, removing the app from recent apps kills the player service.
You can play music in the background, can't you?

**Comment by Sdarfeesh** [comment]
> If it's playing, removing the app from recent apps kills the player service. You can play music in the background, can't you?

How can i play music if the player service have killed

**Comment by z-huang** [comment]
Ah, I know what you mean. Let me clarify the correct use. For music to keep playing in the background, you have to leave the app in the recent apps. To stop the music, kill the app from recent apps, or stop it from the notification.
You want the music to keep playing even if the app is removed from recent apps, but for two reasons this shouldn't be:
1. Persistent queue will broke, I've tried before.
2. It's not the case for YouTube Music, Spotify, and other official music apps. Kill the app means kill everything of the app, including the player. It's kind of weird that you have to remove the app from recent apps AND stop the player to completely end the app.
