### ISSUE TITLE
iOS application

### ISSUE THREAD

**Issue by AloneWOLFx4** [z-huang/InnerTune#337]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Are there any plans to bring the app on iOS platforms or keep it only on android ? 

### Why do you want this feature?

It would provide better accessibility to other users as well

**Comment by z-huang** [comment]
Not planned.
