### ISSUE TITLE
Songs duration displaying incorrectly

### ISSUE THREAD

**Issue by mjain234** [z-huang/InnerTune#348]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Song displaying in the notification is showing in an incorrect manner. In the app its showing around 30 minutes duration but the notification get stucked at 3 min only.

### Expected behavior

nil

### Actual behavior

nil

### Screenshots/Screen recordings

Check this video:
https://user-images.githubusercontent.com/70900505/197362635-68c45cab-fefa-412d-9975-1acbd0c8d28f.mp4

### Logs

nil

### Music version

0.4.2

### Android version

Android 10

### Additional information

Device - Realme 2 Pro
ROM - Stock (Realme UI)

**Comment by z-huang** [comment]
Is it happening every time for you?

**Comment by mjain234** [comment]
Nope, it happens very rare.

**Comment by z-huang** [comment]
> Nope, it happens very rare.

Therefore, I won't fix it because notification is handled by ExoPlayer's `PlayerNotificationManager`.
