### ISSUE TITLE
Lyrics colors 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#350]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add a option to change the lyrics colors.

### Why do you want this feature?

As I can't see the current dark lyrics.

### Additional information

![Screenshot_20221023_095600_InnerTune Debug](https://user-images.githubusercontent.com/96526481/197383473-ed7c752b-3140-4e7b-91dc-9857d5e4235e.jpg)

**Comment by z-huang** [comment]
Thanks for the spot. It should look normal now.
Also, from the screenshot, it seems that your screen is too narrow for the five buttons to show. I should fix the layout.

**Comment by z-huang** [comment]
Would you try aad1d49a6fc91c93311f7a5dae1074e63338c7aa and see if it's better?

**Comment by owencz1998** [comment]
Much better thank you that's the thing with samsung z fold phones 🤣


![Screenshot_20221023_111924_InnerTune Debug.jpg](https://user-images.githubusercontent.com/96526481/197386732-16d40365-8468-444d-a5e6-32e94b437c64.jpg)
