### ISSUE TITLE
The lyric cannot follow the song progress after coming back from background playing

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#353]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Go to an another app
3. Come back to InnerTune
4. Expand the music player

### Expected behavior

Song and lyric sync

### Actual behavior

Song and lyric out of sync

### Screenshots/Screen recordings

![Screenshot_20221023-214741747](https://user-images.githubusercontent.com/50188628/197396093-c9c72761-c29e-4d64-b889-5f171bb2c26b.jpg)

### Music version

0.4.2-Debug

### Android version

Android 10

**Comment by owencz1998** [comment]
Don't think it even has sync feature yet or he may not able to do it

**Comment by z-huang** [comment]
Synced lyrics is supported, but not every song has synced lyrics.

**Comment by Sdarfeesh** [comment]
> Synced lyrics is supported, but not every song has synced lyrics.

The lyrics of this song can sync, but it stopped after coming back from background playing

**Comment by Sdarfeesh** [comment]
> Synced lyrics is supported, but not every song has synced lyrics.


https://user-images.githubusercontent.com/50188628/197447714-fb89b738-e7d6-46a1-80fa-df96a1e7f75c.mp4

**Comment by z-huang** [comment]
Thanks for the spot!
