### ISSUE TITLE
Add comments for videos

### ISSUE THREAD

**Issue by jacksongoode** [z-huang/InnerTune#354]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It would be nice as an option for videos to include their comments as well. This would be a great feature for those who often search for music to discover what others have said about the song. I imagine the video's description would also be nice as well.

### Why do you want this feature?

Useful and interesting information about a track is include in the comments.

**Comment by z-huang** [comment]
Nope. This is a music player, not NewPipe.
