### ISSUE TITLE
Add title

### ISSUE THREAD

**Issue by Iam-Eshwar** [z-huang/InnerTune#355]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Only the Add the Title of your app is too AiMusic.
Innertune to AiMusic.

### Why do you want this feature?

Only the Add the Title of your app is too AiMusic.
Innertune to AiMusic...

**Comment by z-huang** [comment]
Can you elaborate more? I don't really know what you mean.

**Comment by Iam-Eshwar** [comment]
Innertune is your app title right?
Please rename your app title to a new app title .
I'm suggesting u sir it's AiMusic

**Comment by z-huang** [comment]
I've decided the name InnerTune and won't change again.

**Comment by Iam-Eshwar** [comment]
Bro AiMusic is the best title please make it

**Comment by xmha97** [comment]
> Bro AiMusic is the best title please make it 

InnerTune is a unique name.
