### ISSUE TITLE
Debug link not working 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#356]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to download a debug apk said its loading but doesn't download.

### Expected behavior

Click and then download as normal.

### Actual behavior

Click and it only loads then stops 

### Music version

Debug

### Android version

12

**Comment by z-huang** [comment]
I found other repositories with the same issue. It's handled by GitHub and I can't do anything, sorry. Maybe it's a temporary issue.

**Comment by owencz1998** [comment]
No worries dude 👌

**Comment by owencz1998** [comment]
Found a work around I just changed from using mobile page to desktop page and it worked 🤣
