### ISSUE TITLE
Songs can't be removed from library

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#357]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

In the Artist tab : you find an Artist that you don't want to keep in your library (a song was automatically added during a playlist playback)
From the Artist tab : go into the artist to find the song that was added
It is in the library, but it can't be removed.
To remove it : you would have to search inside the Songs tab between hundreds of songs to find the same song and remove it : it could be impossible depending on the number of Songs you have 
There's no easy way to manage the library

### Expected behavior

Select the Artist -» "Remove Artist from library"
Or at least go into the artist to find the song that was added -» "Remove Song from library"

### Actual behavior

No easy way to clean the library

### Screenshots/Screen recordings

![Screenshot_2022-10-25-18-31-33-692_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/197833161-2974a6d2-bbd5-4d38-a676-54a51d806f74.jpg)

![Screenshot_2022-10-25-18-31-43-668_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/197833220-89377a29-0f48-41cf-a2ab-9ba3049bdb40.jpg)

### Music version

latest debug

### Android version

12

**Comment by xmha97** [comment]
https://user-images.githubusercontent.com/23485114/197837349-54017618-7fff-4934-95a5-5385e0b157d5.mp4

**Comment by z-huang** [comment]
Album songs can't be deleted unless you delete the album.

**Comment by z-huang** [comment]
@JPGuillemin You should navigate in "From your library". There you can delete songs.
