### ISSUE TITLE
Enhance Music Player 

### ISSUE THREAD

**Issue by MrConqueror** [z-huang/InnerTune#359]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Cool design Music Player Clean and neat.

### Why do you want this feature?

Current Player looks bad

### Additional information

![Screenshot_2022-10-26-08-17-39-693_app revanced android apps youtube music](https://user-images.githubusercontent.com/102837820/197905615-4eba3041-1fa1-432a-a353-dd0420a46ff7.jpg)

**Comment by z-huang** [comment]
> Current Player looks bad

Just saying the player looks bad doesn't tell me anything. Please elaborate why.

**Comment by MrConqueror** [comment]
> > Current Player looks bad
> 
> Just saying the player looks bad doesn't tell me anything. Please elaborate why.

I am referring to The Design there should be Dislike/Like Button and 
UP NEXT   LYRICS    RELATED

**Comment by MrConqueror** [comment]
![Screenshot_2022-10-26-08-24-13-893_app revanced android apps youtube music](https://user-images.githubusercontent.com/102837820/197906702-3dbc96b3-474c-436f-8d57-add731404fcd.jpg)
And download Songs/Playlist should look like this so we feel like we're really using premium app
![Screenshot_2022-10-26-08-32-24-647_app revanced android apps youtube music](https://user-images.githubusercontent.com/102837820/197906906-c85acadb-ba40-4701-8488-6c2029d2d61f.jpg)

**Comment by z-huang** [comment]
There's already a like button, and I won't add the dislike button.
Lyrics is developing, see #76.
Up next is implemented and looks like YTM. You can swipe up the bottom to see it.
Related isn't implemented and may not appear in the player view.

> And download Songs/Playlist should look like this so we feel like we're really using premium app

It's just a different layout and I don't really like it. The header is too big and people have to scroll down to view more songs.
