### ISSUE TITLE
"View downloaded files in SAF" doesn't work

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#368]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to settings
2. Click "View downloaded files in SAF"

### Expected behavior

The app opens Document UI

### Actual behavior

The app doesn't open it

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/50188628/198793509-2dd8c124-17a8-417d-8e3a-77b2835efaf9.mp4

### Logs

10-29 14:39:02.340 W/System.err(21744): 	at com.zionhuang.music.ui.fragments.settings.StorageSettingsFragment.onCreatePreferences$lambda-1(StorageSettingsFragment.kt:44)
10-29 14:39:02.340 W/System.err(21744): 	at com.zionhuang.music.ui.fragments.settings.StorageSettingsFragment.$r8$lambda$UWbrpu-pxP7VJfcaft_vnxTAawg(Unknown Source:0)
10-29 14:39:02.340 W/System.err(21744): 	at com.zionhuang.music.ui.fragments.settings.StorageSettingsFragment$$ExternalSyntheticLambda0.onPreferenceClick(Unknown Source:2)

### Music version

0.4.2-Debug

### Android version

Android 10

**Comment by z-huang** [comment]
Can you provide log?

**Comment by Sdarfeesh** [comment]
> Can you provide log?

How to

**Comment by z-huang** [comment]
Is there more information around the provided logs? I'm expecting something like `ActivityNotFoundException`.

**Comment by Sdarfeesh** [comment]
> Is there more information around the provided logs? I'm expecting something like `ActivityNotFoundException`.

![Screenshot_20221029-144715675](https://user-images.githubusercontent.com/50188628/198818118-803acdeb-b61c-443d-8f9c-6c5c1ac7850d.jpg)

**Comment by z-huang** [comment]
Actually, there isn't such a official method to open the native file manager. So, I expect that my approach won't work on all devices. I'll add a hint to let user know this button may have no effect in their phones.
