### ISSUE TITLE
Album not centered

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#369]
Not a big issue just a little to far to the right for a z fold 3 screen

<img src="https://user-images.githubusercontent.com/96526481/198825519-f0e69cd8-bef5-4f11-bc66-e40def15b8e9.jpg" width="200" />

**Comment by z-huang** [comment]
I'm sure I put the album at center.

**Comment by owencz1998** [comment]
Ahh iv just restarted the app and that seemed to work unless my phone glitched out lol
