### ISSUE TITLE
Piped Support

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#374]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add Piped support to access YouTube through instances

### Why do you want this feature?

YouTube is blocked by GFW in China, it would be nice to add Piped support so that people can use this app through instances without using VPN

**Comment by z-huang** [comment]
Piped doesn't support YouTube Music.

**Comment by Sdarfeesh** [comment]
> Piped doesn't support YouTube Music.

https://codeberg.org/Hyperpipe/Hyperpipe
This one support YTM

**Comment by z-huang** [comment]
I saw that it's very experimental. BeatBump is a better choice, but I don't plan to do it right now.
