### ISSUE TITLE
Seach suggestions 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#375]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Home page search for what u like.

### Expected behavior

When typing a song or artists it should automatically show the suggestions.

### Actual behavior

Nothing happens when searching.

### Music version

0.4.2 and debug version

### Android version

12

**Comment by z-huang** [comment]
It turns out that the visitorData generator isn't working well.

**Comment by owencz1998** [comment]
Ahh 😔

**Comment by z-huang** [comment]
I found it not working now, do you have the same issue?

**Comment by z-huang** [comment]
Unfortunately, when you search in YouTube Music web without login, there isn't any suggestion. Looks like YouTube disables the feature intentionally.🙁

**Comment by owencz1998** [comment]
No worries man that's strange from yt side haha

**Comment by z-huang** [comment]
Beside login, another fallback is to use suggestions from YouTube (not YTM), but the suggestions may not be focused on music only and there won't be suggested songs, artists, or albums.

**Comment by owencz1998** [comment]
Oh no 😢 so it's basically if yt music add it back or someone manages to make a api or something that can do this

**Comment by z-huang** [comment]
YouTube Music provides search suggestions without login again!

**Comment by owencz1998** [comment]
Nice maybe it was a issue in there side haha
