### ISSUE TITLE
Let us choose a folder to download songs.

### ISSUE THREAD

**Issue by mosestyle** [z-huang/InnerTune#383]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I've noticed that when we download songs to make it available offline, we can't really find that audio file in our storage to play it on our local music player. Please make it possible for us to choose a download folder to we can save the music :)

### Why do you want this feature?

Better feature for the app!

**Comment by z-huang** [comment]
See #117. There's a way to find downloaded songs.

**Comment by mosestyle** [comment]
I tried to download "Innertune Debug" but my phone won't let me install in due to i get s popup it might contain virus. I even tried older version of "Innertune Debug" still same :(

Is it possible to implement that SAF features to the original release?

**Comment by mosestyle** [comment]
@z-huang I tried to download "Innertune Debug" but my phone won't let me install in due to i get s popup it might contain virus. I even tried older version of "Innertune Debug" still same :(

Is it possible to implement that SAF features to the original release?

**Comment by z-huang** [comment]
Oh, Avast again! I'll report to them. :(
