### ISSUE TITLE
Artist Page "Albums" link broken

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#386]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to an Artist, ie Christopher O'Riley
Click on "Albums" to see all albums in a page
It's broken : you get a list of previously downloaded songs.

### Expected behavior

Get the Albums page

### Actual behavior

Albums page broken 

### Screenshots/Screen recordings

![Screenshot_2022-11-01-13-12-15-602_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/199229917-b88fc3da-1efc-4950-8cf6-2256192105a4.jpg)
![Screenshot_2022-11-01-13-12-28-805_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/199229940-9ba6e68a-ee92-4dd4-8b35-721c80e924ab.jpg)
![Screenshot_2022-11-01-13-12-33-696_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/199229952-2ab5f009-124c-452d-96f0-3f5bd09f016e.jpg)

### Music version

latest débug post 0.4.3

### Android version

12

**Comment by z-huang** [comment]
Oh, I got what you mean now.

**Comment by JPGuillemin** [comment]
![Screenshot_2022-11-01-17-09-07-821_com zionhuang music debug](https://user-images.githubusercontent.com/55490396/199281348-c117a202-2e86-4bc7-9077-40f899f4254f.jpg)

**Comment by z-huang** [comment]
Can't reproduce.
