### ISSUE TITLE
Customize navigation bar label style

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#387]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add navigation bar label (like Google Play Store and Google Phone)

![IMG_20221101_163807](https://user-images.githubusercontent.com/23485114/199240624-f0074f21-cf10-49aa-88ad-fe9e08ae906a.jpg)

Of course, this does not mean that the labels are always displayed, if the tabs become too many, the labels should be hidden:

https://user-images.githubusercontent.com/23485114/199242303-bd20bcbc-6c08-4ed4-abdb-68fd15f0889c.mp4

As you can see there are only two tabs in InnerTune but the labels are not displayed:

![Screenshot_2022-11-01-16-48-19-844_com zionhuang music debug](https://user-images.githubusercontent.com/23485114/199242402-d82f28c7-6979-4d5f-b036-db3c3fa38e99.jpg)

### Why do you want this feature?

- The existence of labels helps to select the tabs faster
- A material UI similar to Google apps

**Comment by z-huang** [comment]
Recognizing the tab by icons should be faster. I just want the UI to be clean. However, I can add an option in settings for you to choose which style you want.

**Comment by z-huang** [comment]
In 0.5.0, the default style of bottom navigation bar has all items with icons, so I'll close this issue.
