### ISSUE TITLE
Add animation to navigation bar

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#388]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi, please add animation to navigation bar:

# M3 Catalog

https://user-images.githubusercontent.com/23485114/199244638-e315ce70-930f-4393-a4e0-48f1d55ecc5f.mp4

https://github.com/material-components/material-components-android

# Retro Music

https://user-images.githubusercontent.com/23485114/199244668-00e74918-24d7-475a-a19b-1c8c8a50ddbb.mp4

https://github.com/RetroMusicPlayer/RetroMusicPlayer

### Why do you want this feature?

- Better user experience

**Comment by z-huang** [comment]
Animation looks great, but it requires much effort to create an animation.

**Comment by z-huang** [comment]
After review, I think it's not necessary and it consumes more resources.
