### ISSUE TITLE
Playlist songs shouldn't be related to library songs

### ISSUE THREAD

**Issue by DaniAndTheWeb** [z-huang/InnerTune#391]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When you add a song to a playlist it gets added to the main library. This behaviour is ok when you're adding just single songs to a playlist but when you decide to "subscribe" to a public playlist the music library gets invaded by all the songs inside the playlist.
An easy solution could be separating the playlist from the library so that both of them work indipendently.

### Why do you want this feature?

To be able to add any playlist i want without filling up the music library with music i may not be interested in.

**Comment by z-huang** [comment]
Then you should use "Add to library", not "import playlist".
