### ISSUE TITLE
Songs wont load automatically

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#392]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a song and wait to the next song  to start.

### Expected behavior

Next song plays automatically.

### Actual behavior

When the next song goes to play I have to click pause and then play for it to work.

### Music version

0.4.3

### Android version

12

**Comment by owencz1998** [comment]
https://user-images.githubusercontent.com/96526481/199707383-442af9e2-2924-408d-812c-b4f89c5698e2.mp4

**Comment by owencz1998** [comment]
Ahh only does it on the debug version I thought I was using the main version my bad

**Comment by z-huang** [comment]
Ok, can you provide log? Find if there's an error with ExoPlayer.

**Comment by owencz1998** [comment]
Can do once finished work dude

**Comment by noClaps** [comment]
This happens on 0.4.3 main too

**Comment by z-huang** [comment]
> Ok, can you provide log? Find if there's an error with ExoPlayer.

@owencz1998 any progress?

**Comment by owencz1998** [comment]
If nothing on here helps let me know iv been going through it for ages 😂


![Screenshot_7.png](https://user-images.githubusercontent.com/96526481/200690689-2086ecf2-707e-43ac-bbd7-a984fc591606.png)

![Screenshot_6.png](https://user-images.githubusercontent.com/96526481/200690696-098c536f-05fa-49fc-bc3d-1260dd353fb1.png)

![Screenshot_5.png](https://user-images.githubusercontent.com/96526481/200690708-77833783-6fa5-4f8a-9e23-a3b7967436b1.png)

**Comment by owencz1998** [comment]
Only thing I could really see is its saying no data this is after I keep clicking pause and play as the song wouldn't play by doing that

**Comment by z-huang** [comment]
Hmm, the log doesn't contain anything helpful, and I still cannot reproduce. Is this happening every time?

**Comment by owencz1998** [comment]
Yeah the song is not even downloaded to some songs sometimes work without issues but sometimes I have to skip the song and then go back as play and pause doesn't do anything and sometimes a song sounds like the app has completely crashed and makes a horrible sound but that happens on and off

**Comment by owencz1998** [comment]
Skip silence is the issue just turned it off and now the start of the new songs work! 😱

**Comment by z-huang** [comment]
So weird!

**Comment by owencz1998** [comment]
Still working after disabling

**Comment by owencz1998** [comment]
Little update the issue isn't happenings as much but some songs now and then doesn't go to the next song once finishing instead tried to look into the logs but I'm not seeing anything not sure if it's just the player issue.
