### ISSUE TITLE
Add option to customize player buttons

### ISSUE THREAD

**Issue by mariotejk** [z-huang/InnerTune#393]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_20221103-011953_InnerTune](https://user-images.githubusercontent.com/117345819/199674468-e29d057d-3cd5-4606-b30a-799dfcebb3ba.png) 

Buttons such as the heart button the repeat button the bar at the bottem and etc should be able to have a option to turn them on and off from showing

### Why do you want this feature?

(in my opinion) The player looks very cultured with to many buttons i would like to be able to customize it to how i would like.

**Comment by z-huang** [comment]
I won't provide such option. The arrangement of buttons now is good enough. If you don't need some buttons, just don't use them. Or you can try to find them useful.
