### ISSUE TITLE
ID3 editor

### ISSUE THREAD

**Issue by nutella09214** [z-huang/InnerTune#394]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hey great app love it
Would it be possible to add id3 editor for those webm files?
I was looking through the options, so for now we can use Material Files (which is another super app!!!) to debug which is great.
I can't seem to find a suitable app to edit id3 info for webm though
If someone could suggest me an app or or better if this feature could be available on InnerTune

### Why do you want this feature?

Since the app uses YTM & YT library, there will be certain audio that we download through YT and those audio do not have the correct id3 info. idk if it's just my ADHD kicking in but I get super annoyed when it displays some random info of the YT channel name or something lol

### Additional information

I mean it doesn't have to be a feature for now, if someone could just let me know which app can edit id3 tags for webm then I can just use the debug options for now through Material Files

**Comment by z-huang** [comment]
I couldn't find a library to edit webm tag, so I didn't make it.

**Comment by selurvedu** [comment]
Rrelevant: https://github.com/z-huang/InnerTune/issues/117#issuecomment-1533226300
