### ISSUE TITLE
UI bug on landscape mode

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#396]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to app on landscape mode

### Expected behavior

Like portrait mode without bug

### Actual behavior

See video below

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/23485114/199708878-1895f149-4bd5-4c79-b2f8-a89318e181fb.mp4

### Music version

https://github.com/z-huang/InnerTune/actions/runs/3375623868

### Android version

Android 12

**Comment by z-huang** [comment]
Oh, no! It's a nightmare to deal with system insets and bottom sheets. 😐

**Comment by z-huang** [comment]
You can fix it temporarily by using full screen gestures for system navigation.

**Comment by xmha97** [comment]
> You can fix it temporarily by using full screen gestures for system navigation.

Yes, thanks.
![IMG_20221104_040936.jpg](https://user-images.githubusercontent.com/23485114/199860962-ce0dfccc-a6bc-4c67-b031-cbcb2d537f0b.jpg)

**Comment by z-huang** [comment]
Since it won't be fixed in 0.4.x, and 0.5.0 won't have this problem, I'll close the issue.
