### ISSUE TITLE
Add tooltip for all buttons

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#398]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add tooltip for all buttons.

![IMG_20221103_151512](https://user-images.githubusercontent.com/23485114/199713366-2a2c5e2d-b503-4613-8258-e0f4cb8a3597.jpg)

### Why do you want this feature?

Although you prefer a simple UI, but I think this feature is useful for users.

**Comment by z-huang** [comment]
To keep the code simple, I don't plan to add this. I think the icons are self-descriptive.
