### ISSUE TITLE
Add support "manage space"

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#399]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Show InnerTune cache setting on Android settings. (Like Telegram app)

https://user-images.githubusercontent.com/23485114/199716955-281745bd-a2cf-4535-952f-e5dead0d4f24.mp4

### Why do you want this feature?

This option can help to access cache settings faster.

**Comment by z-huang** [comment]
I need to create a separate activity for this, which is not worthy.
