### ISSUE TITLE
Apostrophe-gate

### ISSUE THREAD

**Issue by Sameky** [z-huang/InnerTune#401]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any song in English
Check the lyrics
You'll find that all apostrophes are replaced with "&apos;" 

### Expected behavior

You should see words like "don't, can't, ain't" being displayed correctly on the lyrics tab

### Actual behavior

Those words will currently appear like this instead:
"Don&apos;t, can&apos;t, ain&apos;t"

### Screenshots/Screen recordings

![Screenshot_20221103-102154_InnerTune](https://user-images.githubusercontent.com/111753562/199733060-6a1f51d8-767f-4698-a471-26addb54b814.png)

### Music version

0.4.3

### Android version

Android 12

**Comment by Sameky** [comment]
Btw, for some reason, GitHub don't show this: &apos;

In the issue's discription, but happily, y'all will know what I'm talking about by just taking a look on the screenshot

**Comment by z-huang** [comment]
Thanks for reporting!
