### ISSUE TITLE
Reset to link song on orientation change

### ISSUE THREAD

**Issue by j-romchain** [z-huang/InnerTune#403]
### Checklist

- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Info: I am on a Samsung s9+, android 10
 1. Open a YouTube music link on the device
 2. Wait or skip to the next song in que
 3. Rotate device
 4. Orientation changes, but song stops and starts playing the song from the link you first opened.

### Expected behavior

Player should continue to play where it is in the song/que.

### Actual behavior

Player resets to the start of the first song in the que.

### Music version

0.4.3 fdroid

### Android version

Android 10

### Additional information

Doesn't happen when the app is not in focus.

**Comment by deejinng** [comment]
What kind of API do you use ?

Will appreciate your response

**Comment by z-huang** [comment]
> What kind of API do you use?

Use for what?

**Comment by deejinng** [comment]
For getting the results.

I mean when a user search for something and it brings out the results

**Comment by z-huang** [comment]
InnerTube API, YouTube's private API used in YT services such as YT, YTM, YT Studio, ...

**Comment by deejinng** [comment]
> InnerTube API, YouTube's private API used in YT services such as YT, YTM, YT Studio, ...

Oh alright thanks

My question sounds somehow at first because I'm just a Web Developer.

Thanks for your answer I just want to try something minimal out but as a Web application

**Comment by z-huang** [comment]
You can open a thread in discussions tab or send me an email: zionhuang1107@gmail.com. I'll see what I can help you.

**Comment by deejinng** [comment]
I'll leave mail.

Thank you so much :)

**Comment by deejinng** [comment]
I'll leave mail.

Thank you so much :)
