### ISSUE TITLE
Make Player Design Good

### ISSUE THREAD

**Issue by MrConqueror** [z-huang/InnerTune#405]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A Music Player that is clean and premium look

### Why do you want this feature?

Honestly App player doesn't look good

**Comment by MrConqueror** [comment]
Uploading Screenrecorder-2022-11-04-19-14-30-612.mp4…

**Comment by z-huang** [comment]
The screen recording isn't uploaded.

**Comment by MrConqueror** [comment]
> The screen recording isn't uploaded.


https://user-images.githubusercontent.com/102837820/199966548-1cb76d32-4dbd-4544-ba71-e5f75023fd50.mp4

**Comment by z-huang** [comment]
Actually, I don't like Spotify's player UI. We have to scroll down to see the lyrics, which is terrible. Also, buttons at the top of the screen are hard to reach if you're using the phone with only one hand. Honestly, I'm satisfied with current player design. Please elaborate more why you think InnerTune's player doesn't look good and why Spotify's player is good.
