### ISSUE TITLE
Notification or hint about new songs

### ISSUE THREAD

**Issue by siggi1984** [z-huang/InnerTune#408]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to implement some kind of notification or a hint when the artists in your own library post new songs.

### Why do you want this feature?

then you would always be up to date about the new songs of the artists you like or is that too problematic?

**Comment by z-huang** [comment]
We have to check every artist regularly, and that will cause more network consumption. Each query to an artist takes about 20KB. Not sure if this acceptable for users.

**Comment by Alliba** [comment]
Okay, I personally would have no problem with that

**Comment by airon90** [comment]
It may be added an option to choose whether to check for new releases and its time interval

**Comment by Alliba** [comment]
> It may be added an option to choose whether to check for new releases and its time interval

Yes, that is a very good idea. Then everyone can decide for themselves whether they want it or not.

**Comment by owencz1998** [comment]
I'd like this feature 🤘

**Comment by z-huang** [comment]
Not planned because it's too "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)".
