### ISSUE TITLE
Speed, Download and Thankyou

### ISSUE THREAD

**Issue by narinderkmaurya** [z-huang/InnerTune#409]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can change the path where the songs are downloaded, so local music can identify them and play locally, and please do something about the speed of downloads and a sincere thank-you for making this awesome app bruh💫

### Why do you want this feature?

It can make improvements and will be more recommendable to everyone!

**Comment by z-huang** [comment]
The download path is unchangeable, but you can access the files with SAF as said in README. There seems to be an answer to solve the slow download speed in #13, and I'll check it out when I'm available. Finally, thank you for using this app!
