### ISSUE TITLE
Match Now Playing Screen With AlbumArt/Thumbnail

### ISSUE THREAD

**Issue by max5354** [z-huang/InnerTune#410]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Match Now Playing Screen With AlbumArt/Thumbnail. That also available in YouTube music.

### Why do you want this feature?

It's useful to fast forward/backward songs.

**Comment by z-huang** [comment]
Duplicate of #159
