### ISSUE TITLE
Don't make lyrics button greyed out by default

### ISSUE THREAD

**Issue by jeffdumcum** [z-huang/InnerTune#412]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hello, currently when I tap on a song, even though there are lyrics for that song, the button is greyed out. This makes it look like there are no lyrics available, even though there are lyrics for that song. Please do not make button greyed out. Thank you!  

### Why do you want this feature?

.     

### Additional information

.

**Comment by z-huang** [comment]
Just click the lyrics button and the lyrics will show.
