### ISSUE TITLE
Lyrics not synced

### ISSUE THREAD

**Issue by jeffdumcum** [z-huang/InnerTune#413]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download InnerTune, the world's best music app
2. Search for a song and turn on lyrics
3. You can see they are not synced to the song

### Expected behavior

It should be synced

### Actual behavior

Its not synced

### Screenshots/Screen recordings

![Uploading Screenshot_20221105_120052_InnerTune.jpg…]()

### Music version

0.4.3

### Android version

Android 12

**Comment by owencz1998** [comment]
Not all songs are synced he's using  kugou and something else I believe its not something he can fix I think

**Comment by jeffdumcum** [comment]
> Not all songs are synced he's using kugou and something else I believe its not something he can fix I think

Ok thanks for telling me

**Comment by jeffdumcum** [comment]
Wait, he could set the default lyrics provider to YouTube Music

**Comment by owencz1998** [comment]
Yt music are not synced tho are they ?

**Comment by z-huang** [comment]
YouTube Music lyrics are not synced, but Kugou's are. Therefore, the default lyrics provider is Kugou. However, you can disable Kugou in the settings. Also, if you want other available lyrics, you can click the three dots menu in the right-bottom of the lyrics view and click "Choose other lyrics".
