### ISSUE TITLE
Add Spotify Support

### ISSUE THREAD

**Issue by jeffdumcum** [z-huang/InnerTune#414]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This allows playlists from spotify and podcasts only available on spotify to be played. 

### Why do you want this feature?

Because it would allow spotify exclusive podcasts + spotify playlists

**Comment by z-huang** [comment]
This app will only support YouTube Music.
