### ISSUE TITLE
Please add A log in function to get Libary to a new device 

### ISSUE THREAD

**Issue by PaLo6415** [z-huang/InnerTune#418]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add a log in function to get Libary to a new device

### Why do you want this feature?

To get Libary of Songs, Artists, Albums & Playlists

### Additional information

Please add it

**Comment by owencz1998** [comment]
He's added login on the debug for next release but he's still working on it as I know off

**Comment by z-huang** [comment]
Duplicate of #88

**Comment by PaLo6415** [comment]
Not the same as 88 i meant account for innertune not yt music Account

**Comment by z-huang** [comment]
> Not the same as 88 i meant account for innertune not yt music Account

Not possible.

**Comment by PaLo6415** [comment]
Okay
