### ISSUE TITLE
Lockscreen song/album art

### ISSUE THREAD

**Issue by mattcarter11** [z-huang/InnerTune#422]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add an option to enable the image of the song/album that's playing to be the lock screen background. (Oto music has something like this, for reference)

### Why do you want this feature?

Looks pretty sleek

**Comment by z-huang** [comment]
I think this is enabled by default.
