### ISSUE TITLE
Songs can't be played 

### ISSUE THREAD

**Issue by GET100PERCENT** [z-huang/InnerTune#428]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://music.youtube.com/watch?v=LyFkV0Fq7qg
Try to play the song.

### Expected behavior

It should play the song as usual.

### Actual behavior

It shows a screen with some errors.

### Screenshots/Screen recordings

![Screenshot_20221113-214134](https://user-images.githubusercontent.com/116144024/201532440-357c900b-fe3f-4744-b8b4-c8df34a8b063.jpg)

### Logs

java.lang.NullPointerException
	at x7.h.h(SourceFile:226)
	at x7.h$e.u(SourceFile)
	at va.a.m(SourceFile)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(SourceFile)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(SourceFile)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(SourceFile)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(SourceFile)
	at lb.o0.run(SourceFile)
	at qb.h.run(SourceFile)
	at rb.j.run(SourceFile)
	at rb.a$a.run(SourceFile:82)

### Music version

0.4.3

### Android version

Android 7.1 Nougat

**Comment by z-huang** [comment]
I can play the song successfully.

**Comment by GET100PERCENT** [comment]
Okay, then it may be some issue in my device or in the internet.

**Comment by GET100PERCENT** [comment]
And another question. Does innertune use new pipe extractor?
Or it uses some other extractor?

**Comment by z-huang** [comment]
> And another question. Does innertune use new pipe extractor?
> Or it uses some other extractor?

InnerTune uses its own extractor.

**Comment by z-huang** [comment]
> And what does the logs explain?

The logs show a NullPointerException because something needed is null.

**Comment by GET100PERCENT** [comment]
> > And what does the logs explain?
> 
> The logs show a NullPointerException because something needed is null.

Don't it require to be fixed?

**Comment by GET100PERCENT** [comment]
> > And another question. Does innertune use new pipe extractor?
> > Or it uses some other extractor?
> 
> InnerTune uses its own extractor.

Okay keep it up 👍👍👍

**Comment by z-huang** [comment]
> Don't it require to be fixed?

I think not. The data cannot be null in order to play songs.
