### ISSUE TITLE
Some songs do not reflect kugou lyrics

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#430]
For example,phony―Will Stetson
(kugou has lyrics)

**Comment by z-huang** [comment]
Open the three-dot menu at the right-bottom of the lyrics view. Click "choose other lyrics" and try editing the title and artist to find the lyrics.

**Comment by Denpun1** [comment]
Vimusic
![Screenshot_2022-11-16-22-50-09-905_it.vfsfitvnm.vimusic.jpg](https://user-images.githubusercontent.com/110000352/202198201-a684defa-15cc-4b86-bc6e-b5e5edf89ec4.jpg)

kugou
![Screenshot_2022-11-16-22-50-23-939_com.kugou.android.jpg](https://user-images.githubusercontent.com/110000352/202198260-71745cbd-6f31-417b-9006-8e8df30cd473.jpg)

innertune
![Screenshot_2022-11-16-22-51-39-022_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/110000352/202198431-2019fb6e-e0a6-41e4-a35e-87a27a7769d5.jpg)

I love this app!
Keep up the good work on development!
