### ISSUE TITLE
Rename artist

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#431]
![Screenshot_2022-11-16-18-04-57-485_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/110000352/202136963-4eb19c05-a6c1-4319-a422-1f118f303e5c.jpg)![Screenshot_2022-11-16-18-05-04-180_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/110000352/202137016-2f1154b6-4fc5-48fd-91a1-365e897b8cb3.jpg)

**Comment by z-huang** [comment]
Change content language to English and refetch the artist.
