### ISSUE TITLE
Provide settings toggle to disable receivers for Bluetooth, VPN, and download

### ISSUE THREAD

**Issue by BOB74j** [z-huang/InnerTune#433]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Requesting the addition of a toggle in the InnerTune settings which disables the behavior that respawns the player notification under certain seemingly unrelated conditions. Even with InnerTune apparently closed, the player notification has been observed respawning upon enabling device Bluetooth, connecting to a VPN, or initiating a download in a browser app.

The new settings toggle may be placed in the Player and audio settings with a name such as "Resume on connectivity change". The option may be grayed out if Persistent queue is set to Off, as the notification behavior described above has only been observed with Persistent queue On.

### Why do you want this feature?

With Persistent queue set to On and InnerTune seemingly closed, the player notification frequently reappears under certain conditions, such as enabling device Bluetooth (whether or not a Bluetooth device pairs as a result). This behavior has also been observed upon connecting to a VPN or initiating a download from certain unrelated apps such as Web browsers. A video demo is provided here, depicting InnerTune being closed, but its notification reappearing upon simply enabling Bluetooth with no device connected.

This behavior is inconsistent with that of many other media players on Android. I suggest an option to disable the behavior.

https://user-images.githubusercontent.com/43751378/202256675-c346f336-b739-46b1-9cf9-69386a3a0c5a.mp4

### Additional information

The player notification behavior described above may be related to the following receivers, as disabling these receivers via root access mostly eliminates the recurring notification. Unfortunately, these receivers may only be disabled by root or [Shizuku](https://github.com/RikkaApps/Shizuku), which many users cannot access.

androidx.media.session.MediaButtonReceiver - started by:
- android.intent.action.MEDIA_BUTTON
- android.media.AUDIO_BECOMING_NOISY

(InnerTune).download.DownloadBroadcastReceiver - started by:
- android.intent.action.DOWNLOAD_COMPLETE
- android.intent.action.DOWNLOAD_NOTIFICATION_CLICKED
- android.intent.action.VIEW_DOWNLOADS

androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver - started by:
- android.work.impl.background.systemalarm.UpdateProxies

**Comment by z-huang** [comment]
Is it fixed now?
