### ISSUE TITLE
Beatbump integration

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#438]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

[Beatbump](https://beatbump.ml) is a privacy-respecting alternative frontend for YouTube Music. Beatbump has a feature that allows users to sync playlists and favorites to other devices, and I believe this could be used within InnerTube as well. This way, the user can avoid logging in with a Google account (once that has rolled out) unless they want to.

I also think that Beatbump should be used when not using any account by default, as it is a more privacy respecting option rather than using YouTube Music, or at least provide that option in the settings as well as a way to specify a specific instance of Beatbump.

### Why do you want this feature?

Because it provides an alternative to signing in with a Google account, but still allows the user to sync music between devices and is more privacy respecting.

**Comment by z-huang** [comment]
Thanks for you detailed description. However, I won't use Beatbump because it doesn't support changing language. As for syncing, it's another thing that I haven't thought of a proper solution. Using [SyncThing](https://syncthing.net/) is a possible option.

**Comment by candroid-man** [comment]
@z-huang 

I actually just discovered another service that is the same thing, it is called [Hyperpipe](https://hyperpipe.surge.sh/), and it has support for many languages! It was also developed thanks to the Piped project, which is a YouTube frontend for videos. Hyperpipe also has the option for syncing music between devices using a Piped login for users already using Piped. Perhaps this would work?

**Comment by z-huang** [comment]
I mean content language, not interface language. Some songs display different title according to the content language. Also, HyperPipe is expirimental as said in their readme, so I don't consider it.
Actually, I don't want to include Piped or other similar things in this project.
