### ISSUE TITLE
wrong time

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#439]
<img width=200 src="https://user-images.githubusercontent.com/110000352/203517525-4240a9d4-dcea-4c5a-83d4-0dec922b0109.jpg" />
<img width=200 src="https://user-images.githubusercontent.com/110000352/203517505-e68cda21-195f-4b90-b274-c5ed3905672f.jpg" />
<img width=200 src="https://user-images.githubusercontent.com/110000352/203523084-2a62111e-bd0a-4296-8206-cbb3a43d93aa.jpg" />

**Comment by z-huang** [comment]
Sorry, I was wrong when converting `hh:mm:ss` to seconds.
