### ISSUE TITLE
My screen is always on

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#442]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Music version

0.4.3

### Android version

Android 12

### Additional information

When the lyrics is displayed, the screen does not turn off.
Please make an option that I can disable.

**Comment by z-huang** [comment]
Then turn off the lyrics if you aren't using it.
