### ISSUE TITLE
Invidious and/or Piped account support for saving and sharing playlists.

### ISSUE THREAD

**Issue by Wave6677** [z-huang/InnerTune#444]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

InnerTune should include a "Log In" feature to log into Invidious or Piped instances. When logged InnerTune can back up all the users playlists to Invidious or Piped, which would be an easy way to add Desktop support as the user can now listen to their music from an Invidious/Piped instance from their saved playlists. They also now have an automatic backup of their playlists just in case their phone gets run over by a semi-truck and the data isn't able to be recovered.

### Why do you want this feature?

I want this feature because I'd like to be able to share my playlists with my friends, which is a bit difficult when everything is stored locally. Adding Invidious or Piped support would make it so I can share the invidious playlist and not have to send screenshots of my 500+ song playlist, to which I usually get the response of "why can't you just send a link"
I'd hope that this would be as simple as calling to the Invidious API with "add /watch?v=abc123 to playlist xyz" but I'm not past the point of being a script kiddy, and am making a feature request instead of a pull request so I understand if I'm asking for a lot here lol

### Additional information

I appreciate you and the app <3

**Comment by z-huang** [comment]
I tried Piped with LibreTube and found it may be a good idea to deal with sharing/syncing issues. So, I may consider it. By the way, are you asking the feature just to solve the sharing problem, or you're already an Invidious/Piped user? I want to know are there really many user who use Invidious/Piped and never use YouTube.

**Comment by candroid-man** [comment]
I never use YouTube, I only use LibreTube

**Comment by rozari0** [comment]
> I tried Piped with LibreTube and found it may be a good idea to deal with sharing/syncing issues. So, I may consider it. By the way, are you asking the feature just to solve the sharing problem, or you're already an Invidious/Piped user? I want to know are there really many user who use Invidious/Piped and never use YouTube.

There is many people who use piped as default alternative frontend for YouTube.

**Comment by isaksh** [comment]
I do as well. I would love to see this as a feature!

**Comment by Linerly** [comment]
> InnerTune should include a "Log In" feature to log into Invidious or Piped instances. When logged InnerTune can back up all the users playlists to Invidious or Piped, which would be an easy way to add Desktop support as the user can now listen to their music from an Invidious/Piped instance from their saved playlists

On the desktop via a web browser, there is [Hyperpipe](https://codeberg.org/Hyperpipe/Hyperpipe) where you can log into your Piped account there, and play the playlists that are stored in the Piped account

**Comment by z-huang** [comment]
Not planned because it's too "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)".
