### ISSUE TITLE
home page and explore page not showing

### ISSUE THREAD

**Issue by dotmashrc** [z-huang/InnerTune#445]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

it just stopped working one day

### Expected behavior

it is supposed to be showing songs and trending playlists etc etc

### Actual behavior

nothing shows up

### Screenshots/Screen recordings

![home page](https://user-images.githubusercontent.com/90378831/204071960-0a729448-86b2-4804-8af0-00f51c44f6ff.jpg)
![explore page](https://user-images.githubusercontent.com/90378831/204071969-aeb5e477-42c1-4575-b596-9f91d1c08645.jpg)

### Music version

0.4.3

### Android version

12

**Comment by z-huang** [comment]
Is YouTube Music supported in your country?

**Comment by dotmashrc** [comment]
turns out it is not
