### ISSUE TITLE
Albums page not displaying anything via artists page.

### ISSUE THREAD

**Issue by Carter0108** [z-huang/InnerTune#446]
If I search for and select an artist and scroll down to albums, clicking on albums to display more shows a blank page. I'm almost certain this has already been noted by someone but I couldn't see it anywhere so posted just in case.

What a fantastic app! I'm looking forward to the 0.5.0 release!

![Screenshot_20221126-134027](https://user-images.githubusercontent.com/55948138/204091843-21bb1fd2-5800-4e6d-a6cd-c67c1e59b0f9.png)

**Comment by z-huang** [comment]
I think it's already solved. I can't reproduce. Can you tell me which artist has this issue?

**Comment by Carter0108** [comment]
> I think it's already solved. I can't reproduce. Can you tell me which artist has this issue?

How strange. As far as I can tell it's every artist.

**Comment by shravankumaruk** [comment]
uhm works well with me tho .Try VPN Connection or re installing

**Comment by Carter0108** [comment]
> uhm works well with me tho .Try VPN Connection or re installing

Strange. Neither fixed it. The same bug also happens when clicking on Singles but Songs loads fine.

**Comment by seasidesongs** [comment]
Hi I am still having the same issue

**Comment by z-huang** [comment]
0.5.0 will solve the issue.
