### ISSUE TITLE
Why F-Droid version signed by you?

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#449]
All F-Droid apps signing with F-Droid signature, for example:
![Screenshot_2022-12-01-14-51-45-036_io github muntashirakon AppManager](https://user-images.githubusercontent.com/23485114/205040271-ab112b81-6be9-4f9f-ac32-059be3bab2d9.jpg)

Why InnerTune signed by you?
![Screenshot_2022-12-01-14-51-32-479_io github muntashirakon AppManager](https://user-images.githubusercontent.com/23485114/205040292-18e38e7f-540e-401f-8e66-dc4362fc6023.jpg)

**Comment by z-huang** [comment]
I have no idea. That's all up to F-Droid. But it's good that you don't need to uninstall the app when installing GitHub apks.

**Comment by IzzySoft** [comment]
https://f-droid.org/docs/Reproducible_Builds/ maybe? If an app was built reproducible, F-Droid will ship 2 APKs for each version: 1 signed by F-Droid, 1 by the dev. Initial installs will get the one signed by the dev by default, unless the user explicitly picks the other one.

**Comment by xmha97** [comment]
Thanks for your description.
How can I install the APK file signed by F-Droid? @IzzySoft

**Comment by IzzySoft** [comment]
If there is no second entry in "Versions" (as your screenshot suggests), I have no idea, sorry. Why would you want to, as both builds are totally identical? Using the version signed by the resp. devs gives you the option to "switch rooms" – e.g. use an "urgent update" from here in case the update process at F-Droid gets stuck due to build problems, or is delayed for some reason. That's one of the points behind it.

**Comment by mon-jai** [comment]
Hi @xmha97. Can you share what app did you use to check the certificate of an APK?

It seems quite useful.

**Comment by licaon-kter** [comment]
@mon-jai https://f-droid.org/en/packages/io.github.muntashirakon.AppManager/

@IzzySoft @xmha97 when `Binaries:` or `binary:` is used, only the upstream APK is used, there's no F-Droid signed version.

The "two APKs" approach is used for detached signatures, eg. Bitcoin Wallet, NewPipe but that involves manual work from the dev to extract the signature, push a MR, etc.

**Comment by IzzySoft** [comment]
First part was already clear to me. Thanks for adding clarity on the second part – though I still do not get how it works with two APKs for the same release, unless each has  its dedicated `versionCode`.

**Comment by licaon-kter** [comment]
One apk is named `appid_versionCode.apk` and the other is `appid_versionCode_hash.apk` (hash or commit I forget, but it's something extra)
