### ISSUE TITLE
Prevent songs that are suggested in real-time from being added to library

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#451]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I really don't know if this is a big or a feature. 

Say I am listening to a single, and the song ends, it will automatically start playing songs similar to the other one. Well I did that today to find out every single song that played was added to my library

### Why do you want this feature?

I don't want the app to decide what goes in my library and what doesn't

**Comment by z-huang** [comment]
Disable auto add to library in the settings.
