### ISSUE TITLE
Allow being able to remove specific songs from an album that has been saved to the library

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#452]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently, when you add an album to your library, all of the songs show up in the library from that album, but that includes tracks that aren't real songs like intros and stuff. I want to be able to remove those from the songs section

### Why do you want this feature?

I want to be able to add albums and then remove the tracks I don't like later

**Comment by z-huang** [comment]
This is not possible. Album is a collection of songs. Adding an album is adding all the songs inside.

**Comment by candroid-man** [comment]
So currently, I would have to go through the album and add the individual songs I want to the library. Apple Music basically allows you to add the entire album to the library, and then delete specific songs from the library while still showing up in the albums page. Is it not possible simply due to the way YouTube music works or something else?

**Comment by z-huang** [comment]
YouTube Music doesn't let you do that. And it causes trouble to database design. A better approach would be letting user to hide songs, but it adds complexity.
