### ISSUE TITLE
Scroll through tracks with a swipe

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#457]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hello! Thanks for your wonderful app! I would like to ask you to add the ability to flip through the tracks with a swipe left or right on the cover. Thank you.

### Why do you want this feature?

It is very convenient and in my opinion is very lacking.

**Comment by candroid-man** [comment]
I agree, when I'm in the car I have to actually take my eyes off the road and press the next song button
