### ISSUE TITLE
No seek and backward button on lockscreen 

### ISSUE THREAD

**Issue by anujithpp** [z-huang/InnerTune#459]
![IMG_20221204_105122.jpg](https://user-images.githubusercontent.com/106502495/205475882-f2538ac9-a7c4-4a3f-bc49-1e29136f4d13.jpg)

**Comment by z-huang** [comment]
That's up to your phone vendor. I have the buttons.

**Comment by anujithpp** [comment]
![Screenshot_2022-12-04-13-34-29-76_92b64b2a7aa6eb3771ed6e18d0029815.jpg](https://user-images.githubusercontent.com/106502495/205480528-c4cc4b31-c6ed-4b13-a6e7-20a21acf0c8e.jpg) I have all the buttons but it is only visible when I swipe and hold the widget other music apps are not like this ![Screenshot_2022-12-04-13-33-59-43_92b64b2a7aa6eb3771ed6e18d0029815.jpg](https://user-images.githubusercontent.com/106502495/205480570-28e3312b-7fc1-4af8-a106-cdb4c5fe25da.jpg) look at this

**Comment by z-huang** [comment]
#377
