### ISSUE TITLE
Error when trying to download all songs in Liked Songs

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#460]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to the Playlists tab
2. Tap on the 3 dot menu next to Liked Songs
3. Download

### Expected behavior

It should have started downloading the songs within the Liked songs

### Actual behavior

Gave me an error:

java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.t.u(SourceFile:58)
	at va.a.m(Unknown Source:8)
	at lb.o0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

### Music version

0.4.3

### Android version

Android 13

**Comment by z-huang** [comment]
It's a todo. It'll be added in 0.5.0. (Hopefully)
