### ISSUE TITLE
Add shuffle toggle

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#461]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I'd like to be able to toggle shuffling all of the songs in a given playlist of album.

### Why do you want this feature?

Currently, you have to tap on the shuffle button in a playlist, and it will start playing random songs. However for me, I want to be able to tap on a specific song and then play a random song after.

**Comment by z-huang** [comment]
Swipe up the queue, and there's a shuffle button.

**Comment by candroid-man** [comment]
@z-huang Perhaps I should have been more clear. I was referring to having an actual toggle on the front of the player, as shown in this screenshot. I think shuffle is a feature that is used very regularly, and it would make more sense to have it next to the play button rather than in a submenu.
![image](https://user-images.githubusercontent.com/51019003/207220348-ec6248b0-93c0-465d-a500-2c9678ea2623.png)

**Comment by z-huang** [comment]
I put the shuffle button in the queue screen because I think people should see the queue after shuffled and may shuffle multiple times until they get a desirable order. After enabling shuffle mode, you probably don't need to use that button for that session. Also, there isn't enough space to add a button in the control screen. The like button is very important, so I won't remove it.

**Comment by candroid-man** [comment]
I don't think you would have to remove the like button, you could even move it next to the add to library button. If a user wants a specific order of songs to be played, they can go into the queue and move songs around manually. Every music player has the shuffle button on the front, and it is a toggle. Currently, the shuffle button isn't a toggle, so you can't revert to the normal sequence of songs without clicking on a song and redoing the queue. It is just weird to me specifically, I wonder if we can reopen this and get the input of other users?

**Comment by z-huang** [comment]
> Currently, the shuffle button isn't a toggle, so you can't revert to the normal sequence of songs without clicking on a song and redoing the queue.

The shuffle button is a toggle.
