### ISSUE TITLE
Pause playing when volume zero

### ISSUE THREAD

**Issue by Leetcodr** [z-huang/InnerTune#462]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Pause playing music when volume is reduced to zero, and continue playing when volume is increased to non-zero

### Why do you want this feature?

convenience

**Comment by z-huang** [comment]
I don't think that's necessary.
