### ISSUE TITLE
Open public playlist by url

### ISSUE THREAD

**Issue by danny-laa** [z-huang/InnerTune#463]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In NewPipe, we can open a playlist by searching its url.

It would be better if InnerTune supports that too. 

### Why do you want this feature?

It would be useful when a playlist's name is too common and buried in tons of search results. (like "R&B", "British Music", etc.)

**Comment by z-huang** [comment]
You can share the url and open it by InnerTune.
