### ISSUE TITLE
Update quick pick 

### ISSUE THREAD

**Issue by John189903** [z-huang/InnerTune#468]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Quick pick are not updating, it is showing sames songs,
Can we add a feature to update it based on the song we want or we listen the most

### Why do you want this feature?

User experience

**Comment by z-huang** [comment]
Discussion in #456.

**Comment by John189903** [comment]
👍👍
