### ISSUE TITLE
Release 0.4.4

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#469]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please release a stable 0.4.9 for current 0.4.x Master, which is .... Stable :)

### Why do you want this feature?

No stable release with latest improvements

**Comment by owencz1998** [comment]
He's busy working on 0.5.0 with a massive amount of work can't wait to test it out once he's added a debug version for us to try 😀

**Comment by z-huang** [comment]
It's okay to release a new version with bug fixes and translation update, but I won't include "login to YouTube" feature. The feature is not complete yet.

**Comment by ShareASmile** [comment]
Yes, that's good, I am waiting for my translations inclusions to be released.

**Comment by airon90** [comment]
@z-huang are there new keys since last release? I don't have time to check sorry

**Comment by z-huang** [comment]
Seems not.

**Comment by JPGuillemin** [comment]
No ?

**Comment by airon90** [comment]
@JPGuillemin:

1. It is not a shame he doesn't add that feature in the next release, at least it is a pity. Be respectful: we all are volunteer
2. Adding a feature not fully stable is not useful to people. It may be useful for pro users but not for basic ones and it could create many problems
3. Don't add useless comments. If he doesn't do anything it seems that he is busy (I may be wrong but he studies yet). Please wait and be pacient

Thank you

**Comment by z-huang** [comment]
Sorry for the late reply. I'm busy preparing the final exam.😅 Please be patient. I'll do that after I'm free.
As for the login feature, the biggest change is that your home tab becomes more personalized, but that is not intended (#88). Also, as stated in #456, I want to redesign the home tab. I'm concerned that people would ask for the "unintended feature" when I change the home tab content. Beside that, there's almost nothing different when you're logged in. After all, the most important feature of login - view/sync your online playlists/likes - isn't implemented. Therefore, I think I'll hide the login button in 0.4.4.

**Comment by JPGuillemin** [comment]
Yes, keep the personalized home tab. Imho it's what makes the yt login worth it.

**Comment by JPGuillemin** [comment]
> @JPGuillemin:
> 
>     1. It is not a shame he doesn't add that feature in the next release, at least it is a pity. Be respectful: we all are volunteer
> 
>     2. Adding a feature not fully stable is not useful to people. It may be useful for pro users but not for basic ones and it could create many problems
> 
>     3. Don't add useless comments. If he doesn't do anything it seems that he is busy (I may be wrong but he studies yet). Please wait and be pacient
> 
> 
> Thank you

"a shame" or "a pity" : means the same in english playing on words like this is childish. 

I'm myself an open-source developer since 1999 (Linux distribution main dev, between many other projects as leader or contributor) please don't try to teach me how I should submit a feature request : I have handled some thousands. 

Anyway : I should have written : "Too bad" : it's fixed.
