### ISSUE TITLE
Songs will not play!

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#470]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the app
2. Tap on a recomanded music

### Expected behavior

Play music

### Actual behavior

Music does not play

### Screenshots/Screen recordings

If the song is not downloaded:
![Screenshot_2022-12-08-05-12-10-592_com zionhuang music debug](https://user-images.githubusercontent.com/23485114/206335812-9b332213-7528-4937-8b93-d5c9f9e8c988.jpg)

If the song is downloaded:
![Screenshot_2022-12-08-05-12-18-614_com zionhuang music debug](https://user-images.githubusercontent.com/23485114/206335988-79b54bf5-950a-44ed-9fad-9a749100a247.jpg)

### Music version

0.4.3

### Android version

Android 12

### Additional information

Songs will not play unless they are downloaded first.

**Comment by z-huang** [comment]
Please provide logs.

**Comment by xmha97** [comment]
I don't know what the problem was, but it was solved.
