### ISSUE TITLE
Need an option to select regional language as it is youtube music 

### ISSUE THREAD

**Issue by sandeshkamboj** [z-huang/InnerTune#472]
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_2022-12-10-12-23-10-71_261cc69e159889934ed6f60143ee2161](https://user-images.githubusercontent.com/109149418/206836277-f6d4a828-5e23-4ac7-9426-f76a1972b0db.jpg)
Need an option to add specific languages, so that recommendations can be only of that chosen language

### Why do you want this feature?

This will make recommendations better.

**Comment by z-huang** [comment]
Not possible.
