### ISSUE TITLE
Loudness normalization from ViMusic

### ISSUE THREAD

**Issue by byREAI** [z-huang/InnerTune#474]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add [loudness normalization](https://github.com/vfsfitvnm/ViMusic/commit/a43b6f10e314a67ae63158feb4ddab33a9efcdea) from ViMusic app, instead of using volume reducing

https://imgur.com/a/JNxhf26

### Why do you want this feature?

Loudness change is better than volume reducing, especially with videos which may have even lower loudness

**Comment by rickdtc** [comment]
![Screenshot_20230628_003455_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/74096544/a361084a-f112-4d17-926a-ae693c1ba8e9)


I think this is added

**Comment by z-huang** [comment]
Temporarily not planned.
