### ISSUE TITLE
Option to Trim song before saving 

### ISSUE THREAD

**Issue by cleanerspam** [z-huang/InnerTune#477]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In advance section of settings a toggle can be added which on turning ON 
will give option to trim the song before saving it to phone for offline playback

### Why do you want this feature?

Some songs have empty and non-music section before or after the actual song .
This feature will ensure that we only listen to songs and not to annoying noises beforehand

### Additional information

Sponserblock for YouTube can be used to auto trim songs if user want

**Comment by z-huang** [comment]
Not planned. BTW, try turning on skip silence.
