### ISSUE TITLE
Broken / Interrupted downloads never finish

### ISSUE THREAD

**Issue by testandreport** [z-huang/InnerTune#478]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Download a song
- Interrupt download (app crash, restart mobile, stop downloadmanager or similar)
- after restarting the app the downloadmanager doesn't continue / restart the unfinished downloads and there is no option to redownload a song

### Expected behavior

- when a download is not active or finished it should continue / restart after the app is started again
- as an alternative there should be a "redownload" option

### Actual behavior

- after restarting the app the downloadmanager doesn't continue / restart the unfinished downloads and there is no option to redownload a song

### Music version

0.4.3

### Android version

Android 10

**Comment by z-huang** [comment]
Remove download first, and then download again.

**Comment by testandreport** [comment]
When a download is not finished, it cannot be removed. Only the whole song can be removed and added again, check your app for yourself.

**Comment by z-huang** [comment]
> app crash, restart mobile, stop downloadmanager

I can hardly encounter these situations. In a normal use case, it's working. You can remove download in the long click menu.

**Comment by testandreport** [comment]
Well, the app crashed 2 times in my first 2 days use, so it is not uncommon at this stage 🤔 But okay, it's your app and your decision.
