### ISSUE TITLE
Song deletion in one playlist deletes it in every other playlist as well

### ISSUE THREAD

**Issue by testandreport** [z-huang/InnerTune#479]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- create or import a playlist
- add a song from this playlist to another playlist
- delete the song from one playlist

### Expected behavior

- the song should only be deleted from the playlist you are currently in

### Actual behavior

- the song is deleted from every playlist

### Music version

0.4.3

### Android version

Android 10

**Comment by z-huang** [comment]
You should swipe left/right on the song to remove it from your playlist.

**Comment by testandreport** [comment]
This is a work around but the described bug is still present and a bug...

**Comment by testandreport** [comment]
Otherwise you should rename "delete" to "remove from library" to make clear, what this action does.
