### ISSUE TITLE
Deleting a playlist with downloaded files doesn't delete the downloaded files

### ISSUE THREAD

**Issue by testandreport** [z-huang/InnerTune#480]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- import or create a playlist and add some songs
- download the songs for offline use
- delete the playlist
- 

### Expected behavior

- the downloaded files (which are not in any other playlist) should be deleted as well
- at least there should be a question whether to keep downloaded files or not

### Actual behavior

- the downloaded files are kept and are only accessible via playlist "Downloaded songs"

### Music version

0.4.3

### Android version

Android 10

**Comment by z-huang** [comment]
I think I just need to give an option to delete all downloaded files in the playlist (#481).
