### ISSUE TITLE
Show a download icon next to a playlist when every song in that playlist is downloaded

### ISSUE THREAD

**Issue by testandreport** [z-huang/InnerTune#482]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to have a download icon displayed in front of the number of songs of a playlist, if every song in that playlist is downloaded. Currently there is only an icon displayed in the song details.

### Why do you want this feature?

Faster recognition, which playlists are available for offline use.

**Comment by z-huang** [comment]
The download icon is shown in the playlist screen, not in the playlist lists because it will take too much computation resources.
