### ISSUE TITLE
Android Auto explore, radio or other playlist?

### ISSUE THREAD

**Issue by Bwangster12** [z-huang/InnerTune#485]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I'm not clear if I'm missing something and this is already available, but in Android Auto, all I see are tabs for Songs, Artists, etc... things I've essentially already saved locally.  Is there no way to just explore a new playlist or play artist/song radios?  

### Why do you want this feature?

If I don't have songs favorited or downloaded and just want to listen to new music in the car.

**Comment by z-huang** [comment]
Android Auto doesn't have the interface to type and search online. You should find the music from the phone first and control playback by Android Auto.
