### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ArberTu474** [z-huang/InnerTune#487]
I tried to shuffle an album that I searched for and this happened![Screenshot_20221229-224534.png](https://user-images.githubusercontent.com/88089607/210013943-878b9c7f-36b3-4b34-ae9c-dc339467c7f2.png).

**Comment by jeffdumcum** [comment]
@z-huang would you know why this would be happening?

**Comment by z-huang** [comment]
Which album are you listening to?
