### ISSUE TITLE
"Sort by Albums" in songs tab

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#488]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

"Sort by Albums" in songs tab:

<img width=200 src="https://user-images.githubusercontent.com/23485114/210026535-23a497e4-b72f-4ac5-99e4-ee80b656acbd.jpg" />

### Why do you want this feature?

Show albums tracks one after the other (Like Windows Media Player):
🟠 Track 01 (from Album A)
🟠 Track 02 (from Album A)
🟠 Track 03 (from Album A)
🔴 Track 01 (from Album B)
🔴 Track 02 (from Album B)
🔴 Track 03 (from Album B)
🔵 Track 01 (from Album C)
🔵 Track 02 (from Album C)
🔵 Track 03 (from Album C)

**Comment by candroid-man** [comment]
Also it would be nice if when sorting by artist, it would put songs from the same album together automatically.

Artist album 1
* Song 1
* Song 2
* Song 3
Same Artist, album 2
*Song 1
* Song 2
* Song 3

Currently I think it is based on whichever order you added the songs in. I have mine set to Artist, and I added all of my songs in order so the songs from a given album are together in the songs category

**Comment by z-huang** [comment]
Not planned. You can create a playlist or add the album to your library instead.
