### ISSUE TITLE
Please add "Sleep Timer" option...

### ISSUE THREAD

**Issue by therajatshahare** [z-huang/InnerTune#490]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Sleep Timer - This option helps to set a perticular time so that player will automatically stopped.

### Why do you want this feature?

It's literally very useful option and I desperately need this option because I always listen music while sleeping and as there was no option for sleep timer (auto stop) audio player list didn't stopped. That's why I really want this Feature in this amazing app.

### Additional information

Thank you.

**Comment by z-huang** [comment]
Duplicate of #97
