### ISSUE TITLE
Please make able to play music during call

### ISSUE THREAD

**Issue by impin2rex** [z-huang/InnerTune#491]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As mentioned in the title please make able to play music during call like YT music and VLC.

### Why do you want this feature?

Sometimes lot of people used to attend their call, and like me they might wanted to play music too at that time. Hope I've just gave a clarification. Please develop this feature, Thanks.

**Comment by jeffdumcum** [comment]
Make it a toggle because sometimes you don't want it to play during a phone call

**Comment by z-huang** [comment]
Not planned. Your use case sounds weird to me.

**Comment by impin2rex** [comment]
It is possible to add this feature by tweaking `AUDIOFOCUS` on the exoplayer. Could you allow me to do this by creating a PR or it would be taken care by yourself.

Thanks! 🙏

The idea behind this feature:
When your girlfriend is too talkative and you want to ignore her silly talk, you need this feature.
