### ISSUE TITLE
When playing music, in Quick Settings the photo is low quality

### ISSUE THREAD

**Issue by jeffdumcum** [z-huang/InnerTune#492]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play music
Swipe down to get to quick Settings
Look at how low quality the image is

### Expected behavior

It should look high quality

### Actual behavior

It is low quality

### Screenshots/Screen recordings

![Screenshot_20221230-161551](https://user-images.githubusercontent.com/105110025/210117475-322a6ac8-bc33-4e7a-af7a-d0cd0a2cf411.png)

### Music version

0.4.4

### Android version

Android 13

**Comment by icewyvrn** [comment]
I have the same problem.

**Comment by xmha97** [comment]
I have the same problem.

**Comment by icewyvrn** [comment]
@z-huang

**Comment by z-huang** [comment]
Duplicate of #244
