### ISSUE TITLE
Sponsorblock

### ISSUE THREAD

**Issue by bakinazik** [z-huang/InnerTune#495]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Sponsorblock support! Is it possible to add this feature?

### Why do you want this feature?

Because the music never start the right time.

### Additional information

That is all..

**Comment by z-huang** [comment]
Not planned. I don't think it's necessary.

**Comment by airon90** [comment]
Why should you need SponsorBlock? Do you listen to music with ad inside?

**Comment by z-huang** [comment]
> why do you think this feature is unnecessary?

YouTube Music songs don't have non-music parts.
