### ISSUE TITLE
Will there be login function with Gmail account?

### ISSUE THREAD

**Issue by soymadip** [z-huang/InnerTune#496]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I was reading #88 , but i wanna ask dev (because 
i couldn't understand clearly), will there be support for login ?

### Why do you want this feature?

This is the only thing missing in this app.

Log in will make this app fully 3rd party yt music client and Foss replacement of official ytmusic app.

**Comment by z-huang** [comment]
Yes, after 0.5.0, and notice that not every feature from YouTube will be supported.

**Comment by soymadip** [comment]
> Yes, after 0.5.0, and notice that not every feature from YouTube will be supported.

Oh, thanks for reply.
