### ISSUE TITLE
Can't play video music's video

### ISSUE THREAD

**Issue by soymadip** [z-huang/InnerTune#497]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for any song and select any video **or** click any video music link and open it in Inner tube app(must open in app).

For example open this link through innertube app:-
https://music.youtube.com/watch?v=3jgH5weXYwA

2. App won't show any option to play video. It will just play the audio

### Expected behavior

App will play video with audio 

### Actual behavior

It just plays audio

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/84225810/210797280-ac52309d-4f4e-4d7f-beaa-db4e43abfa4c.mp4

### Logs

No crash

### Music version

0.0.4

### Android version

Android 12, realme ui 3

**Comment by z-huang** [comment]
InnerTune is a music player. It only plays audio.

**Comment by soyelmismo** [comment]
> InnerTune is a music player.

I thought it was a full featured material 3 youtube-music client
