### ISSUE TITLE
Import playlist from youtube/youtube music

### ISSUE THREAD

**Issue by altsst** [z-huang/InnerTune#499]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The ability to import youtube / youtube music playlists into the app

### Why do you want this feature?

I wan't to use innertune but keep my existing playlist

**Comment by z-huang** [comment]
Make your playlist public, and search it in InnerTune.

**Comment by altsst** [comment]
Thanks that works!

**Comment by altsst** [comment]
Thanks @z-huang, that works!

**Comment by tokenwizard** [comment]
That is a workaround that can be very tedious when there could be hundreds of other public playlists that come up when you search. 

I back this feature request as one more like what NewPipe and other apps offer to let you import xml/opml playlists.

**Comment by z-huang** [comment]
I think #260 will make it easier. Just share the playlist and open it in InnerTube.

**Comment by tokenwizard** [comment]
So, go to the YT Music app and share the playlist, selecting InnerTune to share to? Doesn't that kinda defeat the purpose? If you have the YT Music App on your phone, wouldn't you just use that to listen to music? 

My goal is to use InnerTune on a de-Googled device. Preferably without having to use a Google account.

**Comment by z-huang** [comment]
Well, if your previous playlist is in your Google account, then #88. If you want to import from NewPipe or other apps, you can create a separate issue.

**Comment by tokenwizard** [comment]
Just thinking we could export our playlists (Google Takeout) and then import into the app. Is that not what others' requests for "Import Playlist from Youtube" are referring to?
