### ISSUE TITLE
Share from other app to add to library immediately without jumping to the app

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/InnerTune#501]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To add an new share option, not open a song or playlist in Innertune, but to just simply add the song or playlist the library.
Maybe can use a toast to show if it was added successfully, and how many song are added successfully.
### Why do you want this feature?

This is because it is quite annoying to jump to the app then add the song to library, when watching video in yt.
It will be much convient to share then job done.

**Comment by z-huang** [comment]
It will now show a dialog when you share a song to InnerTune.
