### ISSUE TITLE
Odia language not showing in the list

### ISSUE THREAD

**Issue by GET100PERCENT** [z-huang/InnerTune#503]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

![Screenshot_20230107-090039](https://user-images.githubusercontent.com/116144024/211129444-57f0ff50-21f4-4c8d-ad70-e98e4a74e64e.jpg)
In this list I am unable to find the Odia (ଓଡ଼ିଆ) language.

### Expected behavior

It should show the Odia (ଓଡ଼ିଆ) language.

### Actual behavior

It doesn't show the Odia (ଓଡ଼ିଆ) language.

### Screenshots/Screen recordings

![Screenshot_20230107-090039](https://user-images.githubusercontent.com/116144024/211129532-821a97db-4a81-4954-8ded-ff15a19439d7.jpg)

### Music version

Latest Debug Version 

### Android version

Android 7.1 Nougat

**Comment by z-huang** [comment]
It's going to be fixed along with the 0.5.0 release.

**Comment by GET100PERCENT** [comment]
Okay 👍

**Comment by GET100PERCENT** [comment]
And what is the expected release date of version 0.5.0 ?

**Comment by z-huang** [comment]
There's no ETA.

**Comment by GET100PERCENT** [comment]
Hello in the recent debug build, odia(ଓଡ଼ିଆ) language is not been shown in the list.
