### ISSUE TITLE
Error while adding to a Playlist from downloads 

### ISSUE THREAD

**Issue by soumyabratabose** [z-huang/InnerTune#509]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download any song.
2. From downloads tab try to add all of the downloads to a Playlist 

### Expected behavior

All the downloaded songs should be added to that Playlist. 

### Actual behavior

Produces an error. 

### Logs

java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.m.u(SourceFile:77)
	at z8.m.q(Unknown Source:12)
	at z8.i.u(SourceFile:31)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

### Music version

0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
It's a todo.
