### ISSUE TITLE
Ui change

### ISSUE THREAD

**Issue by rishitraii** [z-huang/InnerTune#514]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can you make the accent colour black? Like this:
<img width=200 src="https://user-images.githubusercontent.com/109918393/211979798-e939bc05-6ccb-4ad9-af7c-cf6523edb792.jpg" />

### Why do you want this feature?

I think it looks really clean and premium.

**Comment by z-huang** [comment]
0.5.0 will introduce dynamic color, and I think it looks good, too. See #421.
