### ISSUE TITLE
Opus over M4A in low settings

### ISSUE THREAD

**Issue by n-ce** [z-huang/InnerTune#515]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_20230112-131706_InnerTune](https://user-images.githubusercontent.com/69345507/212008016-540fcdef-bc54-4ed3-aadf-40c205ba37d8.jpg)
Is it possible to play opus codecs over m4a?
The whole world knows opus is massively superior to aac.
The direct replacement to 139 itag is 600 or 249 when 600 is not available.

### Why do you want this feature?

Higher quality audio at the same size or even lower.

**Comment by z-huang** [comment]
InnerTune chooses format according to their bitrate. Itag 139 has lower bitrate and file size than itag 249. Also, I didn't find format with itag 600.

**Comment by n-ce** [comment]
Okay. So can there be an option [prefer opus: on] that will choose lowest opus bitrate available? in most cases this would be itag 249 which is also 50kbps.

**Comment by z-huang** [comment]
Well, now I agree your proposal. Choose opus formats first.

**Comment by Inspiredshadow** [comment]
> Well, now I agree your proposal. Choose opus formats first.

Quality of songs is very low all songs are playing at 50 kbps only even at high setting. Please provide higher quality like 128kbps or 256kbps

**Comment by z-huang** [comment]
@Inspiredshadow When audio quality is set to high, the app use the highest bitrate stream as possible . Therefore, if you just got 50kbps, it's probably the highest bitrate already. However, in my experience, I can always get bitrate of 100~150 kbps.

**Comment by Inspiredshadow** [comment]
> @Inspiredshadow When audio quality is set to high, the app use the highest bitrate stream as possible . Therefore, if you just got 50kbps, it's probably the highest bitrate already. However, in my experience, I can always get bitrate of 100~150 kbps.

But in the same song vimusic has the higher quality(256kbps)

**Comment by z-huang** [comment]
It's impossible to get 256 kbps in both InnerTune and ViMusic. If you're really sure about that, I'm interested to see a screenshot.

**Comment by Inspiredshadow** [comment]
> It's impossible to get 256 kbps in both InnerTune and ViMusic. If you're really sure about that, I'm interested to see a screenshot.

Sorry it wasn't 256kbps,  but i tested same song on both the apps at same bitrate(160kbps), vimusic produce smooth sound but innermusic has a distorted sound speaker behaves like a bad one. This happens with all songs. Why? You please check once yourself.

**Comment by Inspiredshadow** [comment]
> > It's impossible to get 256 kbps in both InnerTune and ViMusic. If you're really sure about that, I'm interested to see a screenshot.
> 
> Sorry it wasn't 256kbps, but i tested same song on both the apps at same bitrate(160kbps), vimusic produce smooth sound but innermusic has a distorted sound speaker behaves like a bad one. This happens with all songs. Why? You please check once yourself.

I figured out something if I turn off loudness normalization in vimusic it also gives the same bad audio as in innertune, means there's a need to improve loudness normalization in innertune.
