### ISSUE TITLE
Incorrect playback -- changing playing speed

### ISSUE THREAD

**Issue by muxina-credo** [z-huang/InnerTune#517]
**Expected behavior**

Every song should playback normally, that is following the time progression of a typical clock.

**Actual behavior**

Some songs jumps between time frames and don't follow a constant time progression.

For example when you play Echoes, Pink Floyd you can see that the playback bar moves very quickly. While, for example, Wish you were here, Pink Floyd plays normally. I noticed this behavior in some other songs.

Could anyone check this in their system?

**Comment by z-huang** [comment]
Maybe that's because you enable skip silence?

**Comment by muxina-credo** [comment]
That was indeed the problem @z-huang. The feature was turn on by default. Sorry about that, there was no real issue.
