### ISSUE TITLE
Import Spotify playlists

### ISSUE THREAD

**Issue by kaonashi696** [z-huang/InnerTune#518]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Import Spotify playlists with their link

### Why do you want this feature?

To import friends playlists or my old playlists that I have on Spotify

**Comment by z-huang** [comment]
There's no direct solution to import a Spotify playlist to YouTube Music, but you can try [tunemymusic.com](https://www.tunemymusic.com/).
