### ISSUE TITLE
playing random song when clicking on the song in queue

### ISSUE THREAD

**Issue by Nilsu11** [z-huang/InnerTune#519]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Mentions: I am on calyxos
1. Launch the app
2. Press play on a self created playlist
3. Get into queue
4. Toggle shuffle on
5. Press on any song besides the first

### Expected behavior

The title, i clicked on, plays

### Actual behavior

Random title from queue plays

### Music version

0.4.4

### Android version

Android 13

### Additional information

Every title from the library is in the playlist

**Comment by z-huang** [comment]
Thanks. I found this bug some time ago, but no one report for it until now. 😀

**Comment by z-huang** [comment]
Also, when shuffle is on, reordering the queue isn't working as expected.
