### ISSUE TITLE
Download album

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#520]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to to be able to download an album saved in my library that I have not downloaded yet.?? 

### Why do you want this feature?

I can only download track by track at the moment

**Comment by seasidesongs** [comment]
I have added full albums to my library that I have not downloaded the songs yet .
Is it possible to download the full album at a later date from the saved albums library 🤔🤔

**Comment by z-huang** [comment]
Do you mean auto download library albums?

**Comment by seasidesongs** [comment]
Sorry I mean that if I save an album but do not download it. Can I download it from my library later. The only way I can do it at the moment is track by track.
Regards

**Comment by z-huang** [comment]
Okay, so you want to "Download album", as the title says.

**Comment by seasidesongs** [comment]
Yes
