### ISSUE TITLE
Improve sound quality

### ISSUE THREAD

**Issue by aceknox** [z-huang/InnerTune#521]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Improve the sound quality and media art image quality

### Why do you want this feature?

Improve

**Comment by eightyy8** [comment]
You can change the audio quality in settings>player & audio (by default it's on auto, which changes quality by itself from the strength of your internet connection)

As for the media/images of the audio, it provides a high quality image, if it isn't, then it probably is just how the image from YouTube is.

**Comment by eightyy8** [comment]
But I do think YouTube thumbnails in comparison with YouTube music covers are displayed with artifacts and lower quality, while they have the possibility to improve.
