### ISSUE TITLE
Thumbnail placeholder

### ISSUE THREAD

**Issue by jacobel640** [z-huang/InnerTune#522]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

please set a thumbnail placeholder to each song/album/playlist/artist

### Why do you want this feature?

so it'll look good when offline

**Comment by z-huang** [comment]
For some implementing issue, this is not planned.
