### ISSUE TITLE
Easily return to the home screen

### ISSUE THREAD

**Issue by HRTK92** [z-huang/InnerTune#524]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to be able to click on the home tab to go to the home screen when I have artists, playlists, etc. open in the home tab.
Not just the home tab, but the other tabs as well.

### Why do you want this feature?

When you open the artist's information from the song details, you have to go back to the previous screen each time.

**Comment by z-huang** [comment]
Actually, I plan to hide the bottom nav when I'm not in top level destinations to have bigger space for content. Therefore, this feature cannot be implemented.
