### ISSUE TITLE
Playlist of top songs or most played songs

### ISSUE THREAD

**Issue by siggi1984** [z-huang/InnerTune#528]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In the playlists section, would it be possible to have an automatic playlist with the top 100 songs or songs that are played the most.

And many many thanks for your hard work on this great APP.

### Why do you want this feature?

To have his favorite titles in a playlist that also updates itself automatically.

**Comment by z-huang** [comment]
I plan to add such playlists in "Stats" (See #421). I will close this issue because it's already a todo in 0.5.0 and another issue named "Stats" will be more appropriate.
