### ISSUE TITLE
View album & playlist by clicking song's title

### ISSUE THREAD

**Issue by eightyy8** [z-huang/InnerTune#529]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Similar to spotify's incorporation, and the artist feature already incorporated into InnerTune; when the current song playing is put into full screen, you are able to access the song's parent album, playlist. This is not only convenient but it feels correct.

### Why do you want this feature?

Much easier access to an important part of where the song exists from. Rather than pushing your finger on the menu button that exists on the bottom of the screen, to then search through a list of options for it.

**Comment by z-huang** [comment]
It's just okay to open the menu and view the album.

**Comment by eightyy8** [comment]
> It's just okay to open the menu and view the album.

It's much easier to get to it? What's the problem with this, it's just an improvement... it doesn't interfere with anything. It is exactly the same as the artist name feature you have, it's not like you have to remove the other in order to implement it.

**Comment by eightyy8** [comment]
After all, that's what a feature is.

**Comment by z-huang** [comment]
I think clicking the song title to view album is not intuitive. Why should I be directed to the album page when I click the song title? I'm not clicking on the album text.

**Comment by eightyy8** [comment]
> Why should I be directed to the album page when I click the song title?

Because, like the artist, it will take you to where it is from, so for songs it will take you to the album the song is actually from. It makes sense to me?
