### ISSUE TITLE
Search function/filter function does not work properly

### ISSUE THREAD

**Issue by siggi1984** [z-huang/InnerTune#530]
> 

> 

> 

> ### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search function/filter function does not work properly

### Expected behavior

Well 😊 a filter function that works.

### Actual behavior

Something is displayed for All and for the rest Artist, Albums, etc.... Nothing is displayed.

See screen rec.

### Screenshots/Screen recordings

- _No response_

### Logs

https://user-images.githubusercontent.com/103368536/213910914-1e2cb68b-965c-44b8-9c20-65613c5945d7.mp4

### Music version

0.4.4.

### Android version

Android 9

### Additional information

Samsung Galaxy A8 (2018)

**Comment by siggi1984** [comment]
Uploading Screen-20230122-104413-720x1280.mp4…

**Comment by siggi1984** [comment]
Uploading Screen-20230122-104413-720x1280.mp4…

**Comment by siggi1984** [comment]
file:///home/siggi/Warpinator/recording_20230122_111947.mp4

**Comment by Me0wzz** [comment]
For me, everything works fine. Does your Region/IP support Youtube Music properly? If not, you should use Proxy/VPN instead.

**Comment by siggi1984** [comment]
> 

YouTube Music is supported in my region. What would I have to enter the proxy, do not know me with.sowas so aus, maybe that would help.

**Comment by airon90** [comment]
I have the same problem too and I am from Italy, which is supported by YTM.

**Comment by owencz1998** [comment]
Its working for me im in the UK

**Comment by JoeJoeTV** [comment]
Also have this issue in Germany.
Only the "All" tab shows results and the other tabs show nothing.

**Comment by NePoCz** [comment]
I can reproduce as well, same thing happens to me in Germany. I tried different proxies and Germany, Spain, France, Switzerland show the same problem while UK, US & Canada worked fine. All those that work seem to be english speaking countries, that is my only idea. But I do realise my testing was limited

**Comment by DarkCrypt** [comment]
Search function works good except on a particular artist, Silent Theory. The All tab and Artists tab throws error, all other tabs work.

**Comment by deepaksrivastav** [comment]
Encountered this issue in Germany as well. Reason:

`
response.contents?.tabbedSearchResultsRenderer?.tabs?.firstOrNull()?.tabRenderer?.content?.sectionListRenderer?.contents
`

has two items :
`
0 = {SectionListRenderer$Content@30449} Content(musicCarouselShelfRenderer=null, musicShelfRenderer=null, musicPlaylistShelfRenderer=null, musicDescriptionShelfRenderer=null, gridRenderer=null)


1 = {SectionListRenderer$Content@30531} Content(musicCarouselShelfRenderer=null, musicShelfRenderer=MusicShelfRenderer(title=Songs, contents=[Content(musicResponsiveListItemRenderer=MusicResponsiveListItemRenderer(fixedColumns=null, flexColumns=[FlexColumn(musicResponsiveListItemFlexColumnRenderer=.........
`

And in Youtube.kt, it picks ths first one which is empty

**Comment by z-huang** [comment]
Does the problem still exist?

**Comment by siggi1984** [comment]
>
