### ISSUE TITLE
Next song in library doesn't play

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#532]
When I click on a random song on my playlist, it's fine until the song ends. The next song pops up, but it doesn't play, it doesn't do anything. I have to then fast forward and rewind it so it will play.

**Comment by z-huang** [comment]
Does this happen for every song? Duplicate of #434?

**Comment by owencz1998** [comment]
Turn of skip silence and try that I had this issue

**Comment by EisregenHoho** [comment]
Same for me, but only on some specific albums kinda, the college dropout by Kanye for example. I just ignored it so far

**Comment by HiddenLeveI** [comment]
@owencz1998 that actually seemed to work. Thanks!

**Comment by HiddenLeveI** [comment]
@z-huang turning off skip silence seemed to fix it

**Comment by HiddenLeveI** [comment]
@EisregenHoho try turning off skip silence in settings

**Comment by EisregenHoho** [comment]
@HiddenLeveI i have it turned off, i never turn it on, same with volume normalization

**Comment by owencz1998** [comment]
@HiddenLeveI no worries mate 👍  also @EisregenHoho are u on the latest version or have u tried to force close the app and clear data and cache to see if that helps make sure u do a backup 1st if u do try mate

**Comment by HiddenLeveI** [comment]
@EisregenHoho I had audio normalization on but that may be pointless

**Comment by owencz1998** [comment]
That hasn't made any difference for me I keep mine on

**Comment by z-huang** [comment]
Duplicate of #434.
