### ISSUE TITLE
InnerTune not setting MediaMetadata#METADATA_KEY_ART

### ISSUE THREAD

**Issue by PranavPurwar** [z-huang/InnerTune#537]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play any music

### Expected behavior

The app should respect the MediaMetadata#METADATA_KEY_ART for external apps to use

### Actual behavior

The music thumbnail isn't set in MediaMetadata

### Music version

0.4.4

### Android version

Android 9

### Additional information

I was using Kizzy RPC and noticed this and the author said that InnerTune wasn't setting some metadata. I really hope you can fix it quickly!

**Comment by z-huang** [comment]
Is it fixed after migrating to media3?
