### ISSUE TITLE
Artist discography isn't showing up

### ISSUE THREAD

**Issue by yellowshouldhaveneverbeenaprimarycolor** [z-huang/InnerTune#538]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to artist profile
2. click on either 'singles' or 'albums'

### Expected behavior

Their discography should show up

### Actual behavior

Nothing is showing up

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/122972734/215348066-b0165506-265d-4a79-9720-e7936b921177.mp4

### Music version

0.4.4

### Android version

Android 13

**Comment by MudssirAhmed** [comment]
@z-huang I want to contribute on this project, Can you assign it to me if possible.

**Comment by z-huang** [comment]
I'm migrating this project to Jetpack Compose (#421) and the code has changed a lot. When I make it public, you are welcome to make pull requests.

**Comment by MudssirAhmed** [comment]
When you are making it live, I want to do some stuff with you. I'm too excited to dive in this project.

**Comment by z-huang** [comment]
As a reminder, I hope you mean contribution, not cooperation. I have my own thoughts on how this app should be, so not every PR will be accepted. However, I'm still happy to view PRs.
