### ISSUE TITLE
Download button unusable in options menu (three dots beside track)

### ISSUE THREAD

**Issue by aier9500** [z-huang/InnerTune#547]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open Innertune 
2. On the home page click on the three dots beside a track
3.  The download button is unusable

or

1. Open Innertune
2. Search for a track 
3. Click on the three dots beside track
4. The download button is unusable

### Expected behavior

When clicking the three dots from 

The download button should be available for use when i click on the three dots in the right side of a track either from home page or in search results.

### Actual behavior

Download button isn't available for use from home page and from search results through clicking the three dots. 

### Screenshots/Screen recordings

![Screenshot_20230131_204154_InnerTune](https://user-images.githubusercontent.com/124108048/215917783-b68096bc-0c6f-4b31-9072-d89c6d7e8dd5.jpg)

![Screenshot_20230131_210026_InnerTune](https://user-images.githubusercontent.com/124108048/215919281-ba0946b4-92c0-4a7e-b356-94accd3c6cdb.jpg)

### Music version

0.4.4

### Android version

Android 13 (One UI 5)

**Comment by aier9500** [comment]
Also, YouTube Music IS supported in my country.

**Comment by seasidesongs** [comment]
I am also having the same problem and I can get ytube too. Any idea on a solution 🤔🤔

**Comment by z-huang** [comment]
The download button is disabled because it's a todo. Add to library and you can download in the songs tab.

**Comment by seasidesongs** [comment]
Will it be possible to have a download button on the three dots in the saved albums section so that the whole album can be downloaded rather than having to download each song separately in the songs section 🤔🤔

**Comment by EisregenHoho** [comment]
@seasidesongs what i do is just put the album in a seperate playlist because you can click Download on the playlists

**Comment by seasidesongs** [comment]
Thanks. I have done that. But will it be possible to just download the album rather than having to create a playlist in a future release 🤔

**Comment by aier9500** [comment]
> The download button is disabled because it's a todo. Add to library and you can download in the songs tab.

can confirm, works.

**Comment by seasidesongs** [comment]
Hopefully we will be able to download albums directly rather than having to do it as a playlist or separate tracks in the songs section..

**Comment by seasidesongs** [comment]
Am looking for correct in saying that you are not planning to be able to download albums directly 🤔🤔

**Comment by z-huang** [comment]
I'm closing it because it's a todo listed in #421 and I don't want to keep too many issues regarding downloads.

**Comment by seasidesongs** [comment]
OK. Thanks
