### ISSUE TITLE
Allow autoplay queue to be separate from manual queue

### ISSUE THREAD

**Issue by aier9500** [z-huang/InnerTune#548]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Allow the autogenerated (autoplay) queue to be separate from manual queue where users manually queue their tracks. This can be added as an option that can be toggled on or off.

i.e. the manual queue is prioritized above the autogrenrated queue, so when the user's manually added tracks finish playing, the autoplay can kick in. If autoplay is currently in effect (there is already an autogenerated queue), when a user adds a track to queue, the song will come before the autoplay tracks, but after the "play next" track" (if there is one).

<img width="609" alt="image (1)" src="https://user-images.githubusercontent.com/124108048/215921423-7f18702b-9fe1-4aac-a638-48760041950e.png">

### Why do you want this feature?

This feature would make the queue more customizable in general. It would allow users to prioritize songs they manually added before the songs that were recommended. This system is used in YouTube Music, and several of my friends and I have regarded that it is a feature that would enhance the experience with the queue. I have not made a poll about this, but it is sure this would be useful to a good mass.

**Comment by z-huang** [comment]
To keep the code simple, I don't plan to make autoplay queue separate.

**Comment by aier9500** [comment]
Nevertheless, great app!
