### ISSUE TITLE
Lyrics Translation

### ISSUE THREAD

**Issue by xmha97** [z-huang/InnerTune#550]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Translate the Lyrics (like the Musixmatch app):
![Musixmatch](https://media.giphy.com/media/8jFmFygL2MwIo/giphy.gif)

### Why do you want this feature?

I want this feature to be able to understand foreign songs

### Additional information

Use this API:
https://simplytranslate.org/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.josias.dev/api/translate?engine=google&from=en&to=fa&text=Love
https://simplytranslate.manerakai.com/api/translate?engine=google&from=en&to=fa&text=Love
https://simplytranslate.pussthecat.org/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.northboot.xyz/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.tiekoetter.com/api/translate?engine=google&from=en&to=fa&text=Love
https://simplytranslate.esmailelbob.xyz/api/translate?engine=google&from=en&to=fa&text=Love
https://tl.vern.cc/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.slipfox.xyz/api/translate?engine=google&from=en&to=fa&text=Love
https://st.privacydev.net/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.riverside.rocks/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.namazso.eu/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.bus-hit.me/api/translate?engine=google&from=en&to=fa&text=Love
https://translate.priv.pw/api/translate?engine=google&from=en&to=fa&text=Love
https://st.tokhmi.xyz/api/translate?engine=google&from=en&to=fa&text=Love
https://st.odyssey346.dev/api/translate?engine=google&from=en&to=fa&text=Love

**Comment by z-huang** [comment]
Not planned because it's too "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)".
