### ISSUE TITLE
Unable to play sensitive content

### ISSUE THREAD

**Issue by ThomasSpedding** [z-huang/InnerTune#552]
When trying to play "jocelyn flores by xxxtentacion" (and other sensitive content, this is just one example) I am met with a sensitive content warning that I am not able to clear.

![Screenshot_20230203-145004_InnerTune](https://user-images.githubusercontent.com/32841560/216633334-e55fd5ae-4a04-4a48-9cbd-f4651bfbdefd.jpg)

**Comment by z-huang** [comment]
The error is from YouTube, and this app is unable to play this song.
