### ISSUE TITLE
Make shuffle persist even after selecting a new song from library

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#555]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want shuffle to persist, or continue shuffling after manually tapping on a song in the library.

### Why do you want this feature?

I listen to my entire library at times and just put it on shuffle. Then I feel like playing a certain song, I play it, but then I have to press the shuffle button again because I guess selecting the new song resets the queue.

**Comment by z-huang** [comment]
Why don't you use the shuffle button in the songs screen?

**Comment by Golbinex** [comment]
> Why don't you use the shuffle button in the songs screen?

This is simple to do on the phone, but in Android Auto it's harder to do during driving. I would at least appreciate if the shuffle button wasn't hidden under 3-dot button, but available on the Android Auto screen right away.
