### ISSUE TITLE
Artist is created multiple times in the library.

### ISSUE THREAD

**Issue by siggi1984** [z-huang/InnerTune#558]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

One and the same artist is created several times in the library.

I have this error with several artists.

### Expected behavior

Songs of an artist old all be created under his name.

### Actual behavior

When I add different songs of an artist, some artists are created multiple times.

### Screenshots/Screen recordings

<img width=200 src="https://user-images.githubusercontent.com/103368536/216786749-e9662a83-7ed9-44d8-bd43-fcf4b2aebf6b.jpg" />

### Music version

0.4.4

### Android version

Android 9

**Comment by siggi1984** [comment]
![Screenshot_20230204-205048_InnerTune](https://user-images.githubusercontent.com/103368536/216787070-e6eefb04-cbf6-4393-b301-675472407bdc.jpg)
![Screenshot_20230204-205147_InnerTune](https://user-images.githubusercontent.com/103368536/216787075-f2cb147f-2a11-4e91-b84b-5b2973ff3e98.jpg)

**Comment by z-huang** [comment]
Some songs don't have their artists linked, i.e., you can't click the artist text to view artists in YouTube Music web. InnerTune therefore creates a local artist, which leads to the problem.

**Comment by siggi1984** [comment]
Okay, not an error in the APP after all. The error lies with YouTube.
