### ISSUE TITLE
Option to sort inside a playlist

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#559]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Ability to sort a playlist by date added/A-Z/etc.

Currently you can only organizing them manually.

### Why do you want this feature?

Because it's useful to be able to play stuff you've most recently added.

Currently you can only organizing them manually.

**Comment by oathzed** [comment]
Can you please add the option to sort as "recently added" that's really useful to see which new songs you've added to a playlist so you can quickly play them. Thanks!

**Comment by z-huang** [comment]
Implemented.

**Comment by oathzed** [comment]
Thank you!

**Comment by oathzed** [comment]
Sorry one last thing doesn't have it :P.

Can you please add "date added" to downloaded songs?
