### ISSUE TITLE
Search option for Playlist

### ISSUE THREAD

**Issue by sri081995** [z-huang/InnerTune#560]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Presently there is no search option in Playlist.
By placing the search button can identify the song by just typing the name rather than scrolling.

### Why do you want this feature?

For searching the song it saves time.

### Additional information

Add search option.

**Comment by z-huang** [comment]
Duplicate of #166
