### ISSUE TITLE
InnerTune gets crashed

### ISSUE THREAD

**Issue by GET100PERCENT** [z-huang/InnerTune#566]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

![20230209_175819](https://user-images.githubusercontent.com/116144024/217857155-8c92fa54-dd5f-4e1a-9e8a-38e0f927b033.jpg)
After pressing the button , innertune gets crashed.

### Expected behavior

It should not crash.

### Actual behavior

It crashes immediately after the button on the bottom right side on the home screen  is pressed.

### Screenshots/Screen recordings

![20230209_181154](https://user-images.githubusercontent.com/116144024/217858085-a85e8777-d9d2-46a9-aa60-ed99e44d68f9.jpg)

### Music version

Latest debug build

### Android version

Android 7.1.1

**Comment by z-huang** [comment]
I need logs.
