### ISSUE TITLE
Selection of several titles

### ISSUE THREAD

**Issue by siggi1984** [z-huang/InnerTune#570]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Selection of multiple titles does not work in the new version

### Expected behavior

Select multiple tracks to add to a playlist or queue

### Actual behavior

Selection does not work. In version 0.4.4 it worked.

### Music version

Latest Debug-Version

### Android version

Android 9

**Comment by z-huang** [comment]
I've added multi-selection to todos in #421.
