### ISSUE TITLE
Quick scroll

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#571]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can we have the quick scroll back into the new version

### Why do you want this feature?

Very helpful

**Comment by owencz1998** [comment]
![Screenshot_20230210_143326_Gallery.jpg](https://user-images.githubusercontent.com/96526481/218117628-d8abf2da-bb46-4c97-9687-b65cf41896c8.jpg)

**Comment by z-huang** [comment]
I would like to have it, too. But unfortunately, it's in [Compose roadmap](https://developer.android.com/jetpack/androidx/compose-roadmap).

**Comment by owencz1998** [comment]
@z-huang oh I see 👀 hopefully we won't wait to long for them to release it
