### ISSUE TITLE
Increase swipe area

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#574]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Thank you so much for adding new features, the new version is great! InnerTune is getting more beautiful and functional every time! I would like to ask to increase the swipe area not only on the album cover, for example to include in the swipe area the name of the track.

![Screenshot_2023-02-10-18-46-56-780_com zionhuang music debug](https://user-images.githubusercontent.com/81887288/218151844-53b946f0-6959-46f5-b1f9-a55fd57425a3.png)

### Why do you want this feature?

All cool, really liked this version, but very often my finger does not reach the swipe area and the track is rolled down.

**Comment by z-huang** [comment]
Thanks. Actually, The area above the title, including blank space, is swipeable. Adding the little height of title isn't helpful, and it's more complex to achieve this.
