### ISSUE TITLE
Auto resume when bluetooth is connected 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#576]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is it possible to have a button to turn on and off auto resume when a Bluetooth has connected 

### Why do you want this feature?

Because when connecting to my work truck it auto resumes which i don't want it to do

**Comment by z-huang** [comment]
You should change the settings from Android Auto.
See https://support.google.com/youtubemusic/thread/136225516/how-do-i-stop-my-cars-bluetooth-from-auto-resuming-playback-of-my-music-when-i-restart-vehicle?hl=en
