### ISSUE TITLE
Youtube music area restriction.

### ISSUE THREAD

**Issue by Inspiredshadow** [z-huang/InnerTune#582]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I am in an area where youtube music is restricted so every time I need to use a proxy and searching for a functional proxy is hard. I used an app 'Vibemusic' available on GitHub and this app plays songs without a proxy or VPN. So i want you to do something like 'vibemusic' so innertune can play songs even in restricted area. 

### Why do you want this feature?

I want this feature because it's very hard to use proxy every time

**Comment by Sdarfeesh** [comment]
Try Piped/Invidious.

**Comment by z-huang** [comment]
Not planned to use Piped/Invidious API. Sorry, please find a proxy if you want to use this app.
