### ISSUE TITLE
Newpipe extractor for videos that are not tagged as Music

### ISSUE THREAD

**Issue by nikhilCad** [z-huang/InnerTune#583]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There are many songs on youtube, that are not in youtube music due to various restrictions. This particularly includes old theme songs. I believe adding Newpipe extractorwhich search all the videos that show up in a normal youtube search(not yt music) will help, and a separate tab for it in the search, can fix this.

This will also help countries without YT Music.

### Why do you want this feature?

Some songs are not in youtube music

### Additional information

-

**Comment by z-huang** [comment]
NewPipe Extractor API doesn't fit my need, that's why I deprecated it in newer versions.
