### ISSUE TITLE
Artist name problem with different languages for lyrics search

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#585]
![Screenshot_2023-02-20-01-08-25-422_com.zionhuang.music.debug.jpg](https://user-images.githubusercontent.com/110000352/219960309-56f694a6-3c34-46da-ba00-038c96c81926.jpg)
Japanese1
![Screenshot_2023-02-20-01-08-30-411_com.zionhuang.music.debug~01.jpg](https://user-images.githubusercontent.com/110000352/219960333-c5aaad45-36cb-4e04-8a93-81e3bde04b8e.jpg)
Japanese2

![Screenshot_2023-02-20-01-08-53-009_com.zionhuang.music.debug.jpg](https://user-images.githubusercontent.com/110000352/219960351-989e5056-b01a-4435-9e03-71a08aa262b8.jpg)
English1
![Screenshot_2023-02-20-01-10-34-222_com.zionhuang.music.debug.jpg](https://user-images.githubusercontent.com/110000352/219960367-003e0ef9-9e23-4208-b8bf-4535268222a7.jpg)
English2

**Comment by z-huang** [comment]
That's why I make it editable to try and find the correct lyrics.
