### ISSUE TITLE
Downloaded songs access

### ISSUE THREAD

**Issue by Inspiredshadow** [z-huang/InnerTune#586]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Can we get access to downloaded songs or can we play them in another player or can we share them. If yes,  how to move or share them.

### Why do you want this feature?

I want to move downloaded songs to a different location.

**Comment by z-huang** [comment]
See readme.
