### ISSUE TITLE
Now playing song in the queue

### ISSUE THREAD

**Issue by Inspiredshadow** [z-huang/InnerTune#587]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add an animation or something eye-catching to now playing song in queue

### Why do you want this feature?

To easily know what song is playing.

**Comment by z-huang** [comment]
It's already in the `compose` branch.
