### ISSUE TITLE
Some pauses should not be cut

### ISSUE THREAD

**Issue by airon90** [z-huang/InnerTune#588]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Listen to some songs which contain pauses on YouTube, e.g. [_Prison song_ by System of A Down](https://m.youtube.com/watch?v=s7ZsYe5Uwg0) or [_Sparire_ by I Cani](https://m.youtube.com/watch?v=XJ65l3UDJGw)
2. Listen to the same songs on Innertune 

### Expected behavior

Pauses should be played

### Actual behavior

Pauses are cut

### Music version

Latest compose Innertune and latest F-Droid version

### Android version

MIUI 13/Android 12

**Comment by nikhilCad** [comment]
Settings, Player and Audio, Skip Silence

**Comment by airon90** [comment]
I know that but I suppose that "Skip silence" feature should not skip *all* pauses

**Comment by lorhof1** [comment]
Another song where this issue occurs is "Pathetic House" by Toby Fox. I do not quite understand what skipping pauses is useful for, maybe it shouldn't default to on as it can be confusing

**Comment by z-huang** [comment]
Skip silence will skip "musical" silence when there's almost no sound. I've lower the silence threshold level and disable skip silence by default.
