### ISSUE TITLE
Error during adding liked songs to new Playlist

### ISSUE THREAD

**Issue by Inspiredshadow** [z-huang/InnerTune#591]
### Checklist

- [ ] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [ ] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to my library
2. Tap 3 dots before liked songs Playlist
3. Try this to add to a new Playlist

### Expected behavior

All songs should be added to new Playlist.

### Actual behavior

It shows me the error. 
java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.s.u(SourceFile:69)
	at z8.s.q(Unknown Source:12)
	at z8.i.u(SourceFile:31)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

### Music version

0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
Fixed in `compose` branch.
