### ISSUE TITLE
Share Playlist option

### ISSUE THREAD

**Issue by Inspiredshadow** [z-huang/InnerTune#592]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please provide an option to share the created Playlist or liked songs Playlist. 

### Why do you want this feature?

There should be an option to share Playlist

**Comment by z-huang** [comment]
Not planned/possible.
