### ISSUE TITLE
Error when downloading liked songs

### ISSUE THREAD

**Issue by christian179717** [z-huang/InnerTune#593]
When I'm trying to download liked songs an error occurred.
![grafik](https://user-images.githubusercontent.com/89655752/220950837-d2b3272d-0da4-4987-ba64-019b9e33943c.png)

Here is the stack trace:
```
java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.t.u(SourceFile:58)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)
```
If I download each song separately everything works fine.

App Source: F-Droid
App Version: 0.4.4.
Android Version 9

**Comment by z-huang** [comment]
That's a todo and will be fixed in 0.5.0.
