### ISSUE TITLE
Artists `Shuffle / Radio` always Plays same songs

### ISSUE THREAD

**Issue by NeeRaj-2401** [z-huang/InnerTune#599]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. open any artist screen
2. shuffle or start radio
3. repeat step 2

### Expected behavior

shuffle / start radio should start play some random song

### Actual behavior

always starts playing same song no matter how many time shuffle or new radio hits

### Music version

[latest debug](https://github.com/z-huang/InnerTune/actions/runs/4291348288)

### Android version

Android 9 and 12

**Comment by z-huang** [comment]
This behavior is correct - corresponds with YouTube Music web.
