### ISSUE TITLE
Disable dynamic theme

### ISSUE THREAD

**Issue by EisregenHoho** [z-huang/InnerTune#601]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So in the newest version i notice the app colors changing based on my album cover of the music im listening to, and i dont like that visually. I'd hope to see a toggle to disable that if it isnt too much of a trouble

### Why do you want this feature?

I dont like it visually

**Comment by jxparrow** [comment]
hey friend can u please tell me why i don't have dynamic theme i have latest version of the app please tell

**Comment by owencz1998** [comment]
@jxparrow 

This is a debug version of compose u need to install the version from the actions section  and change branch to compose

**Comment by owencz1998** [comment]
I'm not sure mate

**Comment by jxparrow** [comment]
Hey guys i am trying for months searching this but i couldn't figure out how to download latest beta or compose apk from github so that i can use Dynamic theme can someone please guide me how to download latest compose apk for Android and install

**Comment by EisregenHoho** [comment]
Oh man i love you sm dude, thanks for implementing it and thanks for the app, you are awesome
