### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by KayllonDouglas** [z-huang/InnerTune#602]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Well, I wanted to know if it was possible to implement Discord's Rich Presence in the app

### Why do you want this feature?

Sharing what I'm listening to with my friends (Obviously) and also that it's easier if they only interact with the rich presence without me having to provide a link to the music

**Comment by z-huang** [comment]
Out of scope, not planned.
