### ISSUE TITLE
Irrelevant track in quick picks

### ISSUE THREAD

**Issue by ThisIsMatin** [z-huang/InnerTune#605]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. open the app
2. see qick picks

### Expected behavior

i expect to see tracks from the genre/singer that i like in quick picks

### Actual behavior

i'm offered tracks by artists that i don't know at all!

### Music version

0.4.4

### Android version

Android 12

### Additional information

irrelevant and out of my taste tracks are suggested in quick picks
i have been using this app for a long time and i'm interested in the genre of metal, rock and djent, but in quick picks i'm offered tracks by artists that i don't know at all

**Comment by z-huang** [comment]
Thanks for your feedback. Can you swipe to refresh in the home screen and check if no quick picks are accurate? The app first finds the most played 5 songs and recent played 5 songs, and pick their related songs (provided by YTM) randomly to make the quick picks. I would like to hear more feedbacks to determine how to improve the algorithm.

**Comment by ThisIsMatin** [comment]
tbh i already did that but nothing happened

**Comment by W1zardK1ng** [comment]
Having same issue, when will the update arrive with the fix

**Comment by z-huang** [comment]
Is it better now? a10b5a7a7828ccf53a279b7b0ad627d3ac94b302

**Comment by z-huang** [comment]
You can download the apk directly in GitHub Actions.

**Comment by W1zardK1ng** [comment]
I tried the [a10b5a7](https://github.com/z-huang/InnerTune/commit/a10b5a7a7828ccf53a279b7b0ad627d3ac94b302) and now i could see only the new release albums.
also there is another issue with the app theme colour is changing every time i click on start a radio.

![Screenshot_20230701-211218](https://github.com/z-huang/InnerTune/assets/110819956/766b811c-15da-4e83-b925-2900d6be1eb2)

**Comment by z-huang** [comment]
You need to play some songs for quick picks to be available.

> there is another issue with the app theme colour is changing every time i click on start a radio.

Can't reproduce.

**Comment by W1zardK1ng** [comment]
yes you are correct, after playing a song quick picks appeared and it looks similar to the song i played.
But the colour changing issue is still there, please check the attached screen recording.

https://github.com/z-huang/InnerTune/assets/110819956/58cab344-44a7-4e5a-bc92-bc3928f1bbbd

**Comment by z-huang** [comment]
The color is changing because dynamic theme is on.

**Comment by W1zardK1ng** [comment]
Maybe i am wrong but as per my understanding dynamic theme should change the colour theme of the app only when the wallpaper is changed or wallpaper colours option is manually changed not by playing song radio.
Will be nice someone could clarify.

**Comment by z-huang** [comment]
The theme changes based on current song artwork.
