### ISSUE TITLE
"Save playlist" button in playlist page

### ISSUE THREAD

**Issue by h1toru** [z-huang/InnerTune#606]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

My youtube playlist is hard to find, I can only open it using share option in youtube app, but I can't save it because there's no button to save the playlist.

### Why do you want this feature?

I think it might've useful, especially for me. I had a lot of song that I liked, I don't want to waste my time adding 200+ songs to a playlist.

Actually, I liked the old version of InnerTune where I can visit a YouTube channel (not an Artist channel). It easier to save a playlist.

### Additional information

Playlist page:
![Screenshot_20230305-142721_InnerTune](https://user-images.githubusercontent.com/96276971/222947623-69b003f6-989e-495c-bc70-c5521afbb296.png)

**Comment by itsmmt305** [comment]
yess make it happen yesss!!

**Comment by itsmmt305** [comment]
yeah so to save that hassle... was this issue opened. just a tap.

**Comment by h1toru** [comment]
> not sure if this too late. I can help you to find your own playlists. first you need to open your playlist as public then you enter to your playlist and open your profile on the top of playlist page. then share your profile to Innertune. you could see your profile and your public playlists press and hold then add to library. you might see your playlists in playlists page within app.
> 
> edited: I can use this method only in YTmusic (YT doesn't work for me)

That's a good information, but not the answer since I'm not using YTmusic. The reason I use InnerTune is to replace YTmusic.
