### ISSUE TITLE
Bottom Navigation Functionality

### ISSUE THREAD

**Issue by bakinazik** [z-huang/InnerTune#608]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Returning to the home page (Shuffle) when the home button is tap more than once. It is currently only used for switching between pages.

### Why do you want this feature?

I have to close all the pages I went through to get back to the main page.

**Comment by z-huang** [comment]
Not planned.

**Comment by bakinazik** [comment]
All other apps have this feature. Its all i can say.
