### ISSUE TITLE
Is there a way to link/sync the app with my Samsung Watch4? :)

### ISSUE THREAD

**Issue by BryanChung** [z-huang/InnerTune#609]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want to be able to control music of the app via my smartwatch, Samsung Watch 4.

### Why do you want this feature?

For convenience. :)

**Comment by DarkCrypt** [comment]
I don't own a smart watch but I'd assume it works through Bluetooth.

**Comment by BryanChung** [comment]
Oh yeah, I tried it today for the first time and it was able to skip tracks! All good! :D
