### ISSUE TITLE
InnerTune impersonator on Google Play Store asking for money

### ISSUE THREAD

**Issue by zhon12345** [z-huang/InnerTune#610]
Hi there, I was browsing ViMusic's issue list and saw a report stating that someone is selling the app on the play store, and sure enough one of the other apps sold by the same dude was InnerTune. Here's a link:

https://play.google.com/store/apps/details?id=com.arven.downloader

I've reported it using the link below and I feel like this should be brought to light.
https://support.google.com/googleplay/android-developer/contact/takedown

While filing the report, I referred to [this comment](https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-1399222536) specifically the **Google play takedown form** section as it has clear instructions on how to fill in the takedown form.

**Comment by Poussinou** [comment]
[The fake developer](https://play.google.com/store/apps/dev?id=6976785119338149978) also has a clone of ViMusic [here](https://play.google.com/store/apps/details?id=com.onlinemusic.arvenapps)... I reported it as well.

**Comment by owencz1998** [comment]
Now a user has also done this to spotube 🙄really disrespectful to all the hard workers who have been providing us with brilliant free projects 😓

**Comment by Poussinou** [comment]
> Now a user has also done this to spotube 🙄really disrespectful to all the hard workers who have been providing us with brilliant free projects 😓

@owencz1998 do you have a link? I'm interested to have a look at this and maybe report it?

**Comment by owencz1998** [comment]
https://play.google.com/store/apps/details?id=oss.krtirtho.spoasde

**Comment by zhon12345** [comment]
> Now a user has also done this to spotube

It seems the same dude has also uploaded Aves Gallery too. 

https://play.google.com/store/apps/details?id=deckers.thibault.aves.libre

**Comment by rickdtc** [comment]
> Hi there, I was browsing ViMusic's issue list and saw a report stating that someone is selling the app on the play store, and sure enough one of the other apps sold by the same dude was InnerTune. Here's a link:
> 
> https://play.google.com/store/apps/details?id=com.arven.downloader
> 
> I've reported it using the link below and I feel like this should be brought to light. https://support.google.com/googleplay/android-developer/contact/takedown
> 
> While filing the report, I referred to [this comment](https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-1399222536) specifically the **Google play takedown form** section as it has clear instructions on how to fill in the takedown form.

https://play.google.com/store/apps/details?id=com.arven.musicplayer

Mf also impersonated symphony -https://github.com/zyrouge/symphony

**Comment by zhon12345** [comment]
> Mf also impersonated symphony -https://github.com/zyrouge/symphony

Wow, thanks for pointing that out, was trying to find the original app but could not figure out what it was.

**Comment by owencz1998** [comment]
Never ending 🤦‍♂️wished they made it harder for people to even upload thing to the Google playstore

**Comment by itsmmt305** [comment]
![Screenshot_2023-04-01-21-35-43-246_de baumann browser](https://user-images.githubusercontent.com/94820934/229301718-eb2d2272-a512-49e5-bba5-0e0cae4242fb.jpg)
wtf how the reviews messed up

**Comment by Urbexed** [comment]
> qu'en est-il de ceci : https://play.google.com/store/apps/details?id=com.zionhuang.music est légitime ? Aurora store me propose de mettre à jour l'application installée par izzyondroid mais échoué et de plus ici sur github je ne vois aucune indication que l'application est sur le play store ou qu'elle a changé de nom et aussi la version qu' elle veut mettre à jour n'est pas présent sur github

It's clearly not legit, play store detects it as already installed on my phone because I have innertune to install and I installed it from this github

**Comment by MadeOnPluto** [comment]
> > qu'en est-il de ceci : https://play.google.com/store/apps/details?id=com.zionhuang.music est légitime ? Aurora store me propose de mettre à jour l'application installée par izzyondroid mais échoué et de plus ici sur github je ne vois aucune indication que l'application est sur le play store ou qu'elle a changé de nom et aussi la version qu' elle veut mettre à jour n'est pas présent sur github
> 
> It's clearly not legit, play store detects it as already installed on my phone because I have innertune to install and I installed it from this github

That's because the guy didn't even bother changing the id.

**Comment by Urbexed** [comment]
> > > qu'en est-il de ceci : https://play.google.com/store/apps/details?id=com.zionhuang.music est légitime ? Aurora store me propose de mettre à jour l'application installée par izzyondroid mais échoué et de plus ici sur github je ne vois aucune indication que l'application est sur le play store ou qu'elle a changé de nom et aussi la version qu' elle veut mettre à jour n'est pas présent sur github
> > 
> > 
> > Ce n'est clairement pas légitime, le play store le détecte comme déjà installé sur mon téléphone car j'ai innertune à installer et je l'ai installé depuis ce github
> 
> C'est parce que le gars n'a même pas pris la peine de changer l'identifiant.

I know

**Comment by emh5945** [comment]
Innertune is licensed under the GPL, distributing it for money is not against the license

**Comment by zhon12345** [comment]
> Innertune is licensed under the GPL, distributing it for money is not against the license

Can you at least understand the license fully before actually commenting?

Yes the GPLv3 license allows distributing for money, but according to the GPLv3 license [line 34-38](https://github.com/z-huang/InnerTune/blob/dev/LICENSE#L34-L38) and I quote "you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code." which is not seen. 

Furthermore on [line 210-215](https://github.com/z-huang/InnerTune/blob/dev/LICENSE#L210-L215) states that changes to the original source code are to be documented but they are indeed not published.
