### ISSUE TITLE
This app so awesome,But not save all songs,this app can save YouTube music songs.please fix this issue.

### ISSUE THREAD

**Issue by octatrix008** [z-huang/InnerTune#614]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

First of all off mobile data
1.Go to Songs....
2.Play songs....
3.few songs can be played but not all songs played.....

### Expected behavior

Songs can be playable

### Actual behavior

This song not playable.

### Screenshots/Screen recordings

![Screenshot_2023-03-14-10-26-39-306_com zionhuang music](https://user-images.githubusercontent.com/121954708/224897396-5e33d7ec-661e-499a-9b07-e57cc72204f9.jpg)

### Logs

No

### Music version

TOP 7 Best phonk music🔥🔥🔥 TIKTOK TOP 7 MOST DANGEROUS TREND / VIRAL

### Android version

Android 9

### Additional information

![Screenshot_2023-03-14-10-26-39-306_com zionhuang music](https://user-images.githubusercontent.com/121954708/224897228-33b059b6-65b7-4b21-a7aa-c86ff7f16c74.jpg)

**Comment by owencz1998** [comment]
Try using the latest compose brance debug
