### ISSUE TITLE
"Auto add song to library" isnt working 

### ISSUE THREAD

**Issue by rickdtc** [z-huang/InnerTune#616]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play track
2. Wait for track to end
3. Check the Songs tab

### Expected behavior

The track should be present there with this option enabled 

### Actual behavior

The track did not appear there

### Music version

0.4.4

### Android version

Android 13 (One UI 5.0)

**Comment by rickdtc** [comment]
Checked the new debug, still happens, since the dev is back, I hope they see this

**Comment by z-huang** [comment]
Auto add to library is deprecated since we have history feature.

**Comment by rickdtc** [comment]
But how do I view cached songs?

**Comment by z-huang** [comment]
There's no need for viewing cached songs. If you want to play a song offline, download it.

**Comment by owencz1998** [comment]
Downloads are incredibly fast and doesn't use a crazy amount of storage you've done a awsome job @z-huang
