### ISSUE TITLE
Copycat app on playstore

### ISSUE THREAD

**Issue by zoroya1** [z-huang/InnerTune#619]
So, i am using Innertune from github since months, i have aurora store installed and to my surprise in updates tab it recommanded me update, i can't remeber using yt client app other then Innertune or Vimusic

Upon looking at pictures on app for which aurora store recommaned me it looks like same as Innertune, maybe someone copied your code and made an app identical to yours, i don't know how to prevent them from copying innetune maybe someone can approach this better

Here is the link of the app : https://play.google.com/store/apps/details?id=com.zionhuang.music
(I check you haven't mentioned play store link in repo, so it can't be yours, can it be ?)

It goes by the name of _Max music player_

**Comment by zoroya1** [comment]
It is sad to hear that you lost some playlist or settings, i hope you remember some songs and can make a new one, if there is option of automatic backup of innertune data, it might be helpful to us, but it is upto dev.
Everything is identical even the play store link has dev's name in it xD...
That person who copied the code only changed _Innertune_ name which we can see on main screen top left corner, apart from that every thing is same lol...
It is foss app so yes anyone can read the code and use, but i think one has to take permission of dev. for it or they should comply with License of the code...
Same thing also happened with _Vimusic_ and dev. of that app found some way to report that app or something like that, maybe Innertune dev and if someone guides, we can do something like that afterall it is not a good prectice to copy someone's hard work, install ads and give it new name without original author's permission....

What you can do (and what i have done) is long press app tab in the updates section, ```
add to blacklist
```, so that you won't get distracted by updates reminders again :)

**Comment by zoroya1** [comment]
It is sad to hear that you lost some playlist or settings, i hope you remember some songs and can make a new one, if there is option of automatic backup of innertune data, it might be helpful to us, but it is upto dev.
Everything is identical even the play store link has dev's name in it xD...
That person who copied the code only changed _Innertune_ name which we can see on main screen top left corner, apart from that every thing is same lol...
It is foss app so yes anyone can read the code and use, but i think one has to take permission of dev. for it or they should comply with License of the code...
Same thing also happened with _Vimusic_ and dev. of that app found some way to report that app or something like that, maybe Innertune dev and if someone guides, we can do something like that afterall it is not a good prectice to copy someone's hard work, install ads and give it new name without original author's permission....

What you can do (and what i have done) is long press app tab in the updates section,
`add to blacklist`, so that you won't get distracted by updates reminders again :)

**Comment by FadeDave77** [comment]
Maybe those of you with google accounts should post a review on the play store.

**Comment by itsmartashub** [comment]
Hey, I appreciate your compassion. Indeed, I've noticed that there aren't many FOSS applications with autobackup, but having it enabled by default would be quite helpful. Thus, I completely concur with you that this would be a useful addition.

Indeed, what they did was a complete fiasko. No way he included ads? Such no shame trying to profit on the labor of others. I won't be surprised if he was just chit-chatting with ChatGPT about how to launch on the Play Store someone else's app, but the prompts weren't great enough for gpt to advise him to also modify the apk name.

If we could something to do... Would post a review but like a non playstore user, I couldn't.
Right now, we could do anti-marketing for the copycat on the other social platforms, idk.

**Comment by zoroya1** [comment]
Sadly i also haven't signed in on gplay, using aurora store.
But i can post it on reddit so this issue reaches to more peoples 👍

**Comment by itsmartashub** [comment]
That's right, Reddit is the way.

**Comment by bushrang3r** [comment]
I'm having the same behavior when using Aurora store. I'm being asked to update an app called Max Music Player. It has the same domain name as that used for Innertune - com.zionhuang.music
It's NOT an exact copy of Innertune this time though. It's just a music player.
