### ISSUE TITLE
Queue is limited to 50-100 songs

### ISSUE THREAD

**Issue by candroid-man** [z-huang/InnerTune#622]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to a very long playlist (mine is 6+ hours)
2. Shuffle play the playlist
3. Look at the queue
4. Notice that it only says 50-100 songs in queue

### Expected behavior

The queue should be as long as the amount of songs in the current playlist

### Actual behavior

The queue is limited to 50-100 songs

### Music version

0.4.4

### Android version

13

**Comment by itsmmt305** [comment]
its a cache thing. workaround- if u go to the 51st or 101st song and play it, the next 50-100 songs are added.. reach the end like this. doing it will cache the song titles and then when u hit the first one again, all songs will load in the queue. although yes the app should load all songs but perhaps the dev capped it to avoid crashing idk.

**Comment by z-huang** [comment]
The playlist is provided by YouTube Music, not controlled by InnerTune.
