### ISSUE TITLE
Support BeatBump Project Import/Export/Sync

### ISSUE THREAD

**Issue by Nacho8347** [z-huang/InnerTune#628]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

https://github.com/snuffyDev/Beatbump

This project has a beautiful web frontend on pc for YouTube music. They have a way to sync playlists together but the problem for them is they don't have a mobile app. 

You have a beautiful application without a web interface so why not add support to each other and support their import/Export option or implement a way to sync likes and playlists together using their method.

### Why do you want this feature?

This gives the best of both worlds with Desktop and Phone support for using an alternative frontend for YouTube music.

**Comment by z-huang** [comment]
Not planned because it's too "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)".
