### ISSUE TITLE
Auto skip songs that are not playable instead of stop playing the queue

### ISSUE THREAD

**Issue by smarttommyau** [z-huang/InnerTune#633]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As title described

### Why do you want this feature?

As the playlist stop when there is a song that is no longer playable, which is very annoying.

**Comment by airon90** [comment]
IMHO it should be an option: I had some songs in my library which are not available anymore as the YouTube Music identifier of that songs have been changed and the saved songs were not available anymore. I need to know if a song has been skipped because of unavailability

**Comment by z-huang** [comment]
Not planned.
