### ISSUE TITLE
Ability to manually move the order of playlists in playlist tab

### ISSUE THREAD

**Issue by fsmorton** [z-huang/InnerTune#636]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In the playlists tab, the playlists can not be manually arranged. They can only be sorted by Name, Date added, and Song count. A 2 line icon at the right side of the playlist like songs in playlists have should be added, that when tapped allows the user to move the order of the playlists.

### Why do you want this feature?

Sometimes the orders that the playlists can be sorted by are not convenient. Some users would like to have certain playlists at certain spots in the list. For example, if I want my playlists sorted by recently added, but I also want a certain playlist at the bottom of the list, there is no way to do that right now.

**Comment by z-huang** [comment]
Not planned for being too "[advanced](https://github.com/z-huang/InnerTune/discussions/421#discussioncomment-6198050)".
