### ISSUE TITLE
[Feature Request] add option when press and hold cover in Album/Playlists page

### ISSUE THREAD

**Issue by Nonanne** [z-huang/InnerTune#639]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In _Album page and Playlists page_ could have action to **long press album cover/playlists thumbnail** for open options like other page too.

screenshot **options in other page (main page) when press** and hold album/playlist
![Screenshot_2023-04-09-16-37-42-753_com zionhuang music](https://user-images.githubusercontent.com/94383254/230765850-2d1719df-081e-471a-a6ce-92d7170a2d97.jpg)

**add options when press and hold this one** in details page (album/playlists page)
![Screenshot_2023-04-09_16-37-59_1](https://user-images.githubusercontent.com/94383254/230765839-43fb0b76-9553-4dd2-a6dc-0285223632e3.png)

### Why do you want this feature?

You can add album/playlists in their page and **no need to select all tracks** when you want to play/add/share/etc.

It very helpful for user to add own playlist (from YT) and **no need to find** it.

You can **play and see all tracks in queue** from album/playlists not just 50-100 first songs.

**Comment by thelazyoxymoron** [comment]
+1

This can function like a local bookmark of the online playlist which would be pretty handy.
