### ISSUE TITLE
Songs accidentally removed from the playlist when scrolling

### ISSUE THREAD

**Issue by BenjiSan** [z-huang/InnerTune#645]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.Go to Playlists
2. Select one list with many songs
3. Scroll down rapidly
4. Probably you remove some songs

### Expected behavior

You should be able to scroll down a playlist without accidentally removing any songs.
The scroll down should have some tolerance for swiping to the right to prevent to remove a song from the playlist. And maybe add a pop-up to undo the action. 

### Actual behavior

When you are in a playlist and you scroll down you can accidentally remove songs from the playlist. It happens so fast that you probably don't even notice it.

### Music version

0.4.4

### Android version

Android 12

**Comment by z-huang** [comment]
Can you provide a screen recording?

**Comment by ghost** [comment]
You should just keep the playlist locked it's not like you have to everyday change the order of songs
