### ISSUE TITLE
Casting to android tv

### ISSUE THREAD

**Issue by mengkudubusuk** [z-huang/InnerTune#646]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add casting feature to android tv

### Why do you want this feature?

I love this feature

**Comment by z-huang** [comment]
Not planned.

**Comment by DarkCrypt** [comment]
No plans for tv...

I found an old Spotify tv mod that's working on Android TV 10 if anyone wants to try it out.
