### ISSUE TITLE
Request: adjustable playback speed (tempo) and pitch

### ISSUE THREAD

**Issue by wolftune** [z-huang/InnerTune#648]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

As in NewPipe (and elsewhere, e.g. AntennaPod), it's great to have speed and pitch controls for playback. It would be a simple control with a "linked" checkbox for whether to tie speed and pitch together or use an algorithm to adjust them separately.

### Why do you want this feature?

For studying music or playing or singing along etc., it's nice to be able to control tempo and pitch of playback.

### Additional information

I think that programs like NewPipe and AntennaPod use some library for this feature, but I don't know the details.

**Comment by z-huang** [comment]
Not planned.

**Comment by z-huang** [comment]
Update: Pitch adjust is available.

**Comment by wolftune** [comment]
Hey, that's nice! Wouldn't the same algorithm offer tempo change?

**Comment by z-huang** [comment]
Done.
