### ISSUE TITLE
Song in a playlist downloading loop 

### ISSUE THREAD

**Issue by BenjiSan** [z-huang/InnerTune#650]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When I tray to download a song o multiple songs of a own playlist, the songs appears to be downloading but no, they stay in a loop (the animation of downloading persist). I think maybe the issue is relate to tha I imported my data from my tablet (where I have actually downloaded the songs) to my phone. 

### Expected behavior

When I select the option to download songs, they should download completely, not go into a download loop.

### Actual behavior

When I tray to download a song o multiple songs of a playlist, the songs appears to be downloading but no, they stay in a loop (the animation of downloading persist). I think maybe the issue is relate to that I imported my data from my tablet to my phone.  I tried removing a song from the playlist, added it again and hit download but the download loop persists.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/13210014/234137341-d1ca16df-a08c-4623-bf60-6fd7841b59d7.mp4

### Music version

0.4.4

### Android version

Android 11

**Comment by selurvedu** [comment]
In my case some song download correctly, and some – seemingly randomly – are stuck like this forever, even after quitting the application. In my case I have not imported anything from anywhere, I started using InnerTune from scratch.
