### ISSUE TITLE
Possible clone on Google Play

### ISSUE THREAD

**Issue by Pepsiman01** [z-huang/InnerTune#660]
Hello!
I just received a notification from the play store saying that InnerTune had a new update, but the update itself is a whole new app, this one: https://play.google.com/store/apps/details?id=com.zionhuang.music .They even kept the app name (com.zionhuang.music)

**Comment by owencz1998** [comment]
It's a clone 100% seems to be a on going thing with most apps on github

**Comment by DEEJINNG** [comment]
I was shocked seeing that lol 😅💔💔

**Comment by owencz1998** [comment]
Think this app is dead now anyways
