### ISSUE TITLE
Unable to play if "Take audio focus" is set as ignore

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#663]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Set "Take audio focus" as ignore
2. Open app
3. Play any music

### Expected behavior

Music plays

### Actual behavior

Music doesn't play

### Music version

0.4.4

### Android version

Android 11

**Comment by z-huang** [comment]
Where to set "Take audio focus"?

**Comment by Sdarfeesh** [comment]
> Where to set "Take audio focus"?

You need a permission manager to manage AppOps permissions to set "Take audio focus"
![Screenshot_20230615-230524988](https://github.com/z-huang/InnerTune/assets/50188628/3166dc7e-5698-453c-9674-49bbfe9dd4e3)

**Comment by z-huang** [comment]
Why would you want to ignore this permission? It seems reasonable that if the app doesn't have the permission to take audio focus, then it can't play music.

**Comment by Sdarfeesh** [comment]
> Why would you want to ignore this permission? It seems reasonable that if the app doesn't have the permission to take audio focus, then it can't play music.

Play music while other medias are playing
