### ISSUE TITLE
Import your own music

### ISSUE THREAD

**Issue by KaneryU** [z-huang/InnerTune#664]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There should be an option to import your own music. It would ask you for the Title, Artist and a cover picture (optional) upon uploading.

### Why do you want this feature?

I have some music that isn't on YouTube, I would upload it to the platform, but I have no idea who the original artist is.

**Comment by z-huang** [comment]
Not planned.
