### ISSUE TITLE
Setting the similarity level of songs on the radio

### ISSUE THREAD

**Issue by ikanakova** [z-huang/InnerTune#666]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It would be great if it was possible to adjust the similarity level of songs on the radio (kind of like the Autoradio craziness in the Nuclear app - see screenshot in Additional information).
Level of great similarity: really similar songs played, for example God`s Gonna Cut You Down by Johnny Cash -> songs by Johnny Cash or country classics (e.g. The Highwaymen, Willie Nelson, Waylon Jennings, Kris Kristofferson, Dolly Parton, Loretta Lynn etc.) will be in the radio queue.
Low similarity level: there will be rock songs in the radio queue (like now).

### Why do you want this feature?

Everyone can choose if they want to listen to a lot of the same or completely random songs on the radio.

### Additional information

![obrazek](https://github.com/z-huang/InnerTune/assets/38765251/94619a5a-2c45-4911-8a16-99b9d30061f1)

**Comment by z-huang** [comment]
Not possible.
