### ISSUE TITLE
Support Lyric from NetEase

### ISSUE THREAD

**Issue by JaxzKyd** [z-huang/InnerTune#667]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like support for additional lyric sources other than YT Music and Kugou. For example NetEase, which is free, or Musixmatch. 

### Why do you want this feature?

I want this feature because the current only synced lyric source provided by the app, Kugou, doesn't have as extensive of a database as NetEase or Musixmatch.

**Comment by z-huang** [comment]
Kugou is enough for my use, so I'll mark this issue as contribution only.
