### ISSUE TITLE
Standard widget for Android

### ISSUE THREAD

**Issue by GuiSousa135** [z-huang/InnerTune#668]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

InnerTune needs a standard widget, with more control and scaling options, like Spotify's widget, but better

### Why do you want this feature?

so music playback can be done via the desktop with more customization

### Additional information

![Screenshot_20230608-092057_Lawnchair](https://github.com/z-huang/InnerTune/assets/55188286/7b180a58-862f-4efb-b726-dc470f486f0a)

**Comment by z-huang** [comment]
Duplicate of #101

**Comment by GuiSousa135** [comment]
Maybe like this:

![Image](https://github.com/user-attachments/assets/a6fce940-9fb9-4918-9c01-fbb78fc6e827)
