### ISSUE TITLE
Remote Access Control

### ISSUE THREAD

**Issue by shravankumaruk** [z-huang/InnerTune#669]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I was thinking what if we can add a remote control using localhost via wifi itself or using private ip remotely like how using laptop we can control spotify etc..Just a thought dont be angry 💖Your app as of now is really good.

### Why do you want this feature?

This feature because if phone is far am working on laptop i can control via laptop like that.

**Comment by z-huang** [comment]
Out of scope!
