### ISSUE TITLE
Kaydırarak Müzik Değiştirmek 

### ISSUE THREAD

**Issue by Samsun5555** [z-huang/InnerTune#672]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Merhabalar,  Uygulama çok şahane ve kullanışlı.  Sizden bir isteğim olacak u. arım dikkate alırsınız
*Bir önceki ve bir sonraki parçayı değiştirmek için parmak ile sağa sola kaydırarak geçiş olmalı
* Tam ekranda ekran açık kalmalı. Ayarlardan bu durum  açıp kapatılabilmeli
* Türkçe dil desteği gelmeli

### Why do you want this feature?

Ekran kaydırarak müzik değiştirmek arabada çok pratik oluyor.

**Comment by z-huang** [comment]
Please use English so that everyone can understand.
