### ISSUE TITLE
[Feature request] Alphabetical Scrollbar

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#679]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Im not sure if jetpack compose has Alphabetical Scrollbar yet as we discussed a while back but maybe things have changed.

### Why do you want this feature?

Very helpful feature to have in all sections as possible.

### Additional information

Not sure if this is any help but maybe this link maybe helpful.

https://developer.android.com/jetpack/compose/touch-input/pointer-input/scroll

Sorry if this issue already is open somewhere but I couldn't find it.

**Comment by z-huang** [comment]
In [Compose Roadmap](https://developer.android.com/jetpack/androidx/compose-roadmap), scrollbars is still listed in backlogs, so it's not supported officially yet.

**Comment by owencz1998** [comment]
No worries bro 👌
