### ISSUE TITLE
Playlist download error

### ISSUE THREAD

**Issue by Kataki-L** [z-huang/InnerTune#683]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to playlists tab
2. Choose your playlist (mine was liked songs)
3. Tap on download button

### Expected behavior

Expected to start downloading the playlist

### Actual behavior

Instead of downloading, shows error log everytime

### Screenshots/Screen recordings

![Screenshot_2023-06-18-11-21-50-097_com zionhuang music](https://github.com/z-huang/InnerTune/assets/88727089/52caf89e-bb92-4d8e-b0ab-0002b1ba2983)

### Logs

java.lang.UnsupportedOperationException
	at k8.g.u(Unknown Source:5)
	at k8.g.e(SourceFile:10)
	at z8.t.u(SourceFile:58)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at rb.a$a.run(SourceFile:82)

### InnerTune version

0.4.4

### Android version

Android 12 miui14

**Comment by z-huang** [comment]
It's not implemented yet.
