### ISSUE TITLE
Songs loading Error

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#684]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open App
2. Click on already added song from Songs Tab ( imported from backup and restore tab )
3. See if it plays, (in my case, shows error stated in below screenshot)

### Expected behavior

It should have started playing the song.

### Actual behavior

Showed an error I don't understand!?!

### Screenshots/Screen recordings

![Screenshot_20230618-143235](https://github.com/z-huang/InnerTune/assets/136909951/49bd96d0-e857-45d4-83cc-d965aab6b69c)

### InnerTune version

0.4.4-debug

### Android version

Android 14

### Additional information

I will guide you through it, if this above information isn't enough to understand the issue..!

**Comment by z-huang** [comment]
Please clear the cache and try again.

**Comment by Vishcot** [comment]
> Please clear the cache and try again.

I have tried this multiple times, but not working...

This error is only coming from restored library list..
Loading songs from online tab is working fine!

(Even loading songs from online tab - already added into Library - not playing at all, showing same error mentioned in above screenshot)

**Comment by Anonymousperson0016** [comment]
I'm currently having this issue too. It all started when I backed up everything I have from the latest release of innertune to the debug version of it. I already tried clearing the cache too.

**Comment by Vishcot** [comment]
> I'm currently having this issue too. It all started when I backed up everything I have from the latest release of innertune to the debug version of it. I already tried clearing the cache too.

Yeah exactly similar experience!

**Comment by owencz1998** [comment]
It maybe because the download feature hasn't been added yet

**Comment by owencz1998** [comment]
If u can get the main apk and delete all downloads then keep the playlist backup and restore with downloads deleted and try that

**Comment by Vishcot** [comment]
> It maybe because the download feature hasn't been added yet If u can get the main apk and delete all downloads then keep the playlist backup and restore with downloads deleted and try that as I think it's searching for the download and not the stream.

Yeah it worked after deleting downloads and backing up! Issue resolved! Thanks 👍

**Comment by owencz1998** [comment]
No worries mate anytime
