### ISSUE TITLE
Search bar over lapping the content

### ISSUE THREAD

**Issue by someonespcl** [z-huang/InnerTune#691]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search anything in the search bar 

### Expected behavior

Either the search bar should be fade out or the content

### Actual behavior

Search bar is over lapping by that it doesn't looking nice

### Screenshots/Screen recordings

![Screenshot_2023-06-22-21-59-06-255_com zionhuang music debug](https://github.com/z-huang/InnerTune/assets/111456781/2c24f595-4d8c-4a1b-82c5-4fb38ef4f492)

### InnerTune version

Latest debug version

### Android version

Android 12

### Additional information

It is a simple layout issue so u can change it in next update, the issue is search bar over lapping the content which is not looking good

**Comment by z-huang** [comment]
For some implementation issue, I decide to make the search bar fixed.
