### ISSUE TITLE
Song doesn't play after removing the app in background

### ISSUE THREAD

**Issue by someonespcl** [z-huang/InnerTune#692]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

While playing a song minimize the app after that clear the app in background, the playing song also stops

### Expected behavior

It should be played even the cleared from background activity

### Actual behavior

Song stops

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/111456781/5cd38e87-d094-432c-86f1-6c918f3d8f89

### InnerTune version

0.4.4 debug

### Android version

Android 12

### Additional information

Please add background playing support to app

**Comment by z-huang** [comment]
This is working as expected. Don't clear the app if you want background playback.
