### ISSUE TITLE
Not working "add playlist" and "download" button (Debug version)

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#694]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. song page
2. open menu
3. you can see

### Expected behavior

The functions work properly.

### Actual behavior

![Screenshot_2023-06-23-19-02-54-428_com zionhuang music debug](https://github.com/z-huang/InnerTune/assets/110000352/f776271d-fd95-4e3c-a515-e9bfa06566b9)

I can't push these buttons.

### InnerTune version

0.44 Debug

### Android version

Android12

### Additional information

Is this bug?

**Comment by PranavPurwar** [comment]
same here

**Comment by PranavPurwar** [comment]
additional info: download button is also greyed out in v0.4.4 but when moving to playlists section and downloading, it works

**Comment by owencz1998** [comment]
Downloads hadn't been added yet as of switching to compose he's yet to add this

**Comment by z-huang** [comment]
The buttons are disabled because it's not implemented yet.

**Comment by PranavPurwar** [comment]
> The buttons are disabled because it's not implemented yet.

Even on release version v0.4.4 ?
![Screenshot_2023-06-23-21-27-18-539_com zionhuang music](https://github.com/z-huang/InnerTune/assets/75154889/498830ff-2ea1-4150-ac66-4ddb919e0f76)
Because the button **does** work when I switch to a saved playlist and click download
