### ISSUE TITLE
Add start radio option in android auto 

### ISSUE THREAD

**Issue by sarangwce** [z-huang/InnerTune#697]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Add start radio option in android auto 

### Why do you want this feature?

Will play new songs instead of repeating from playlists

**Comment by z-huang** [comment]
Not planned. You can start radio from your phone.
