### ISSUE TITLE
Imported playlist issue

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#698]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to your playlist you've imported.
Go to remove a song you no longer want.
Doesn't show delete or remove from playlist.

### Expected behavior

Should be able to remove any songs in the playlist.

### Actual behavior

No delete button shows.

### Screenshots/Screen recordings

![Screenshot_20230624_080753_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/96526481/f9de9e08-b6fb-433a-aff3-bd84d802536a)

### InnerTune version

5.0

### Android version

13

**Comment by z-huang** [comment]
You can now swipe to remove song.

**Comment by owencz1998** [comment]
Thanks buddy@z-huang
