### ISSUE TITLE
Please, add persistent "Settings" button next to the searchbar

### ISSUE THREAD

**Issue by Username1-a** [z-huang/InnerTune#699]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

App version: InnerTune v0.4.4 Debug #898
OS version: Android 13 QPR2

Before, in stable version v0.4.4 searchbar at least had 3-dot menu next to it with the only "Settings" button in it. 
In a newer debug versions the "Settings" button was moved to the first "Home" tab (which makes it accessible only from the first "Home" tab)

### Why do you want this feature?

It is very tedious to go to the "Settings" menu from the button on the first "Home" tab, especially since bottom nav bar (with the "Home" tab) is dynamically hidden while in queue view. 
Persistent, always present "Settings" button next to the searchbar would've make accessing "Settings" menu much easier

### Additional information

![Screenshot_20230624-164957_InnerTune~2](https://github.com/z-huang/InnerTune/assets/47947180/d25ee7df-cd24-48db-a39c-05daa1759419)
![Screenshot_20230624-165013_InnerTune~2](https://github.com/z-huang/InnerTune/assets/47947180/e274464a-df9e-4b45-b211-caf58bc6724a)
![Screenshot_20230624-165044_InnerTune Debug~3](https://github.com/z-huang/InnerTune/assets/47947180/1b8aabfa-7cae-4b59-8d79-c6213c0e38a8)
![Screenshot_20230624-165059_InnerTune Debug~2](https://github.com/z-huang/InnerTune/assets/47947180/2eba5f0a-d6a8-4ecd-a2eb-c8b531e7d9f9)
![Screenshot_20230624-165059_InnerTune Debug~3](https://github.com/z-huang/InnerTune/assets/47947180/abde8803-b634-4ffd-a93f-5891d6778bbb)

**Comment by z-huang** [comment]
Settings shouldn't be visited so frequently, so I think it's acceptable to place it only in the home screen.
