### ISSUE TITLE
Amoled black Appearance

### ISSUE THREAD

**Issue by Alphamars** [z-huang/InnerTune#704]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please kindly add amoled appearance in the dark theme. 

### Why do you want this feature?

It will make the quality of the display pop and also conserve battery for those amoled display screens.

**Comment by z-huang** [comment]
Already in the debug builds.
