### ISSUE TITLE
Artist page is broken

### ISSUE THREAD

**Issue by Ekki2015** [z-huang/InnerTune#708]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I search for a artist

### Expected behavior

Show the artist page

### Actual behavior

It should show the artist page

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/12226562/2df24aaf-1624-4b5e-b7fb-48558858cfc1

### InnerTune version

0.4.4

### Android version

Android 13

**Comment by yant0** [comment]
confirmed & still broken a50c3a8

**Comment by oathzed** [comment]
Weird, I'm actually getting this now on the latest debug build as well.

**Comment by z-huang** [comment]
Can you provide logs?

**Comment by oathzed** [comment]
> Can you provide logs?

I'll get logs for this issue and the song error issue sometime this week, sorry for the delay
