### ISSUE TITLE
Unknown Error (doesnt play)

### ISSUE THREAD

**Issue by yant0** [z-huang/InnerTune#710]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open any online song

### Expected behavior

Play the song

### Actual behavior

Doesnt play song

### Screenshots/Screen recordings

![Screenshot_20230628-085107](https://github.com/z-huang/InnerTune/assets/80298071/cf43850f-5527-45bd-8f7d-7906386d4e77)

### InnerTune version

Commit a50c3a8

### Android version

12

**Comment by z-huang** [comment]
Can you provide logs?

**Comment by yant0** [comment]
Fixed in latest commit idk what happened

**Comment by PeaceEnjoyer** [comment]
![Screenshot_20241003-164019](https://github.com/user-attachments/assets/d7c6a7ca-a760-4bc8-a669-6b4a2f1c5c93)
Happened again, same situation, play a song, shows error.
