### ISSUE TITLE
Playlist Sync Bugged

### ISSUE THREAD

**Issue by NeeRaj-2401** [z-huang/InnerTune#713]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. import playlists having more songs (i my case around 500-600)
2. tap on sync

### Expected behavior

should be synced

### Actual behavior

the number of songs in playlist gets reduced rather than playlist sync

### InnerTune version

dev debug version

### Android version

12

**Comment by z-huang** [comment]
Any example?

**Comment by NeeRaj-2401** [comment]
@z-huang  Probably This would help

https://github.com/z-huang/InnerTune/assets/88180887/a2fbe765-0218-4a43-abe8-df6461d5c1d3

**Comment by z-huang** [comment]
You should wait until the sync completes before navigating up.

**Comment by NeeRaj-2401** [comment]
@z-huang can we have some sort of loader, indicator or notification for the time being playlist is synced.
this will help to avoid such confusing scenarios.

**Comment by z-huang** [comment]
Done.
