### ISSUE TITLE
Download all at once option 

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#714]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I/We want to download all songs from library at once! 

### Why do you want this feature?

Its easy and helpful to download songs at once

**Comment by owencz1998** [comment]
So what the playlist has now u want in the library.

**Comment by yant0** [comment]
Might be a bit overkill

**Comment by z-huang** [comment]
This will come along with #695.
