### ISSUE TITLE
Chromecast Support 

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#717]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Chromecast Support

### Why do you want this feature?

Will be helpful in casting songs on TV and Speakers that had cast option

**Comment by DarkCrypt** [comment]
No plans for tv...

I found an old Spotify tv mod that's working on Android TV 10 if anyone wants to try it out.
