### ISSUE TITLE
Adding album doesn't add songs or artist

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#718]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search "Seven lions"
2. Go to his page and add an album to library
3. Now go to albums, it will be there
4. Songs from album won't be in the songs tab, and he won't be in the artist tab

### Expected behavior

Songs from the album should be on your songs tab and he should be in the artist tab

### Actual behavior

He isn't in the artist tab, and the songs aren't added the the songs tab. Funily enough seven lions shows in search when you search your library

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/221da4d7-0dec-4d1a-aab1-a4bb37e3aaac

### InnerTune version

Latest debug

### Android version

Android 13

**Comment by z-huang** [comment]
This is working as expected.
