### ISSUE TITLE
Random artist showing in library artist search

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#720]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have a fresh version of innertune installed
2. Search "s" in library search, nothing shows
3. Play a song from the artist home
4. Search "s" again in library search
5. Random artists show

I have no artists in my library

### Expected behavior

No artists that are not in your library should show

### Actual behavior

Random artists show

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/63e33363-89c6-4b82-9479-b2cb37efac08

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
Thanks for reporting!

**Comment by oathzed** [comment]
> Thanks for reporting!

No problem! Thanks for fixing :)
