### ISSUE TITLE
The option to be able to search inside playlists 

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#721]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Library search works for songs added to our library, but if I want to search inside a playlist I have added that's not an option. Playlists have hundreds or even thousands of songs, it would be nice to be able to search a title inside a playlist, be that the "liked playlist" or any playlist you've added.

### Why do you want this feature?

It really important to be able to search for a song you only remember part of the title

**Comment by cluac7** [comment]
Any updates on this? Or maybe make a button to add all songs from a playlist to library so you can just do a normal library search? Thanks so much for the app btw its awesome.
