### ISSUE TITLE
Some songs don't play, gives error

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#723]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search seven lions
2. Go to community playlist
3. Select "best of seven lions"
4. Play "Don't leave" top song
5. Go to player big size
6. Press error
7. Song will start playing

### Expected behavior

For the song to play right away and not give an error

### Actual behavior

Song doesn't play and gives an error, then you have to press error and song begins to play

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/460a1c69-3a04-4786-b00b-2d739f30dcc5

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
Can you provide logs?

**Comment by oathzed** [comment]
> Can you provide logs?

How do I obtain the logs?

**Comment by z-huang** [comment]
Please search how to use `adb` to obtain logs.

**Comment by oathzed** [comment]
> Please search how to use `adb` to obtain logs.

Copy, I'll give it a shot, thanks

**Comment by owencz1998** [comment]
This is the same issue I'm facing with some songs but unfortunately I'm on holiday atm so can't get logs

**Comment by z-huang** [comment]
Maybe that's because I changed the player cache directory. Try to do a backup, clear app data & cache, and restore your backup. Notice that downloads won't be included in the backup and will be cleared if you clear app data.

**Comment by owencz1998** [comment]
Already tried this also checked piped to see if it can grab the song and it can just seems to be this app can't get the song
