### ISSUE TITLE
A lot of the categories/explore are missing on homepage

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#724]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to home
2. Refresh
3. Only 1 section shows

### Expected behavior

For everything to show like stable build

### Actual behavior

Not much shows on debug build

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/beed3406-4c79-4b76-8a85-deeb81de47a5

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
See #712. If you want other sections, please create a separate issue.
