### ISSUE TITLE
Stuttering scrolling on artist page

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#725]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to seven lions artist page
2. Scroll up and down

### Expected behavior

No stutter

### Actual behavior

Slight stuttering

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/45ad18f3-5b60-439d-a0e0-dda8b17e60b1

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
I think it's not a big deal.
