### ISSUE TITLE
New version 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#726]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi is it possible to have the explore section on the latest release and also to have a tab on the downloaded songs as date added

### Why do you want this feature?

Easier access and more information

**Comment by z-huang** [comment]
> The title of this issue accurately describes the feature request.

**Comment by seasidesongs** [comment]
On the latest debug release please
Great work Sir
Going to buy you a coffee 👍👍

**Comment by z-huang** [comment]
You can now sort downloaded songs by date added.
As for the explore section, track in #712.

**Comment by seasidesongs** [comment]
Great. Would it also be possible that when i have added an album to the library the related  artist and tracks are added to the respective   tabs
