### ISSUE TITLE
Re 0.4.4 debug version 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#727]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Would it also be possible to have the about artist info at the bottom of the artists page 

### Why do you want this feature?

For further information

**Comment by z-huang** [comment]
Not planned.

**Comment by seasidesongs** [comment]
No problem
