### ISSUE TITLE
Re version 0.4.4 debug version 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#728]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

 i added an album  to the library and downloaded it 

### Expected behavior

I would expect that the album that i  have added to my library that artist and the songs to appear in the artist and songs tab but both are blank?? 

### Actual behavior

Both artists and songs tab are blank?? 

### InnerTune version

04.4 debug

### Android version

Android 13

**Comment by z-huang** [comment]
Adding an album to library will only make it show in the albums tab.

**Comment by seasidesongs** [comment]
How do i add my favourite artists to the artist tab 🤔🤔

**Comment by seasidesongs** [comment]
When i add an album to version 0.4.4 the  artist shows in the artists and the songs appear in the songs tab. Can this also be instigated in 0.4.4 degub version 🤔🤔

**Comment by seasidesongs** [comment]
Debug **

**Comment by seasidesongs** [comment]
Can downloaded songs also have a date added tab in the 0.4.4 debug version as it has in the 0.4.4 release
Many thanks
