### ISSUE TITLE
Sometimes artist images don't show in stats tab

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#731]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Add some artists
2. Play some songs
3. Go to stats tab
4. Some artist won't have images
5. Press them
6. See they have an image
7. Go back
8. No image

### Expected behavior

For images to show if they have one on their page

### Actual behavior

Sometimes an image won't show

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/52545913/4aa7f207-f893-4d5a-a578-dc2080a64c51

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
Thanks for reporting!
