### ISSUE TITLE
A way to save playlist from playlist page

### ISSUE THREAD

**Issue by SomeoneSK** [z-huang/InnerTune#732]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want the option to copy playlist from playlist page

### Why do you want this feature?

I want to copy and download my youtube music playlist.

### Additional information

By sharing the playlist from Youtube Music app, I can open the playlist in InnerTune, but I can not copy the whole playlist at once. I could select all songs and add them to new list, but selecting is buggy and there are hundreds of songs.

**Comment by z-huang** [comment]
Already done in dev branch.
