### ISSUE TITLE
 Tracks are deleted from the playlist very easily and without warning or the ability to cancel the action.

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#735]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Normal everyday use of app

### Expected behavior

More thoughtful removal of tracks from the playlist. Perhaps you could make the swipe longer and add a notification that the track is removed from the playlist and an option to undo the action. It would also be cool to make it possible to block removal of tracks from the playlist as a separate option.

### Actual behavior

Tracks are deleted from the playlist very easily and without warning or the ability to cancel the action.

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/81887288/795ff80b-1a78-43c7-9322-fc442750643b

### InnerTune version

Latest dev build 

### Android version

Tested on A11, A12, A13

### Additional information

Iss very easy to delete swipe tracks from the playlist. Just move your finger slightly to the side and the track is deleted without warning and the ability to undo the action.

**Comment by z-huang** [comment]
Added undo snackbar.

**Comment by z-huang** [comment]
The `velocityThreshold` is hardcoded in the library and can't be set by my side. See https://issuetracker.google.com/issues/252334353.

**Comment by z-huang** [comment]
> Also, problems like that could've been solved if swiping away/removing and rearranging/sorting the tracks in the playlist would be possible only when entering some sort of playlist editing mode (like, an "Edit" button)

Playlist lock added (#749).
