### ISSUE TITLE
Incorrect state of the play button after the last track in a playlist or an album has finished playing

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#738]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open an album or a playlist
2. Scroll through or wait until the last song has played to the end
3. Note the play button and the EQ animation on the track cover

### Expected behavior

Correct state of the play button after the last track has finished playing

### Actual behavior

When the last song in an album or playlist has finished playing, the play button remains in the playback state, not in the stop playback state, and the EQ animation on the track cover is still playing.

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/81887288/5641ec4c-aa39-4dbd-9dd1-ebf2f5057e26

### InnerTune version

Latest DEV Debug build

### Android version

App tested on A11, A12 and A13

### Additional information

This is not a critical bug and does not affect the overall performance of the application. It is possible that the incorrect display of the EQ animation when the last track in an album or playlist ends is due to the incorrect state of the play button.

**Comment by z-huang** [comment]
Fixed again.
