### ISSUE TITLE
Artists. Albums songs tabs

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#740]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Would it also be possible that when i have added an album to the library the related artist and tracks are added to the respective tabs

### Why do you want this feature?

This is already on the official release but not on the debug version

**Comment by z-huang** [comment]
Some people may want the album songs to show in the album tab only, so I didn't force album songs to show in songs tab. As for adding related artists, bookmarking artists may be a better approach (#542).

**Comment by seasidesongs** [comment]
Bookmarking Artists to appear in the artists tab would be great..
Thanks

**Comment by seasidesongs** [comment]
In the three dots section for the artists next to start radio.. Shuffle and share 👍👍

**Comment by z-huang** [comment]
> In the three dots section for the artists next to start radio.. Shuffle and share 👍👍

Will be done after #542.
