### ISSUE TITLE
Date added descending and ascending are actually swapped it seems

### ISSUE THREAD

**Issue by oathzed** [z-huang/InnerTune#744]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Add a playlist that you have on YouTube music, it's sorted date added descending  (so recently added stuff is first)
2. Add a song to that imported playlist, it will add it to the end of the playlist not the top.

### Expected behavior

For it to add the song to the top of the playlist if it's sorted by date added (newest first)

### Actual behavior

Adding song to a date added descending sort will add it to the bottom not the top

### InnerTune version

Latest debug 0.4.4

### Android version

Android 13

**Comment by oathzed** [comment]
Hey man, this still inlsnt working as intended. Check the video below.
I have that chill playlist sorted as date added (recently added songs go to the top), I import that playlist, I sort the playlist by date added (newly added songs at the top). I add a song to that playlist, it goes to the bottom of the playlist not the top.

Cheers :)


https://github.com/z-huang/InnerTune/assets/52545913/cdefde6b-7f79-4637-ac2e-920339e3301c

**Comment by oathzed** [comment]
@z-huang

**Comment by z-huang** [comment]
It's working as expected. The added song has the largest date added value, so it appears first if you sort by date added descending.

**Comment by oathzed** [comment]
> It's working as expected. The added song has the largest date added value, so it appears first if you sort by date added descending.

Ahh got yeh. Then importing playlists is not working as expected? The playlist I have added is coming in as descending, "Rustica - wilborn" is the most recently added song on YouTube music, so if I sort that by date added descending, it gets flipped and those songs are now at the bottom. That's now how it is on YouTube music
