### ISSUE TITLE
App size suddenly increases ~ 40 mb

### ISSUE THREAD

**Issue by rickdtc** [z-huang/InnerTune#745]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

This needs more testing but it's happening for me for sometime, I think it happens after you reboot.
Anyway, 
1. Install app freshly, it's all ok - 
<img width=200 src="https://github.com/z-huang/InnerTune/assets/74096544/e286d0da-3ede-4ab7-87e3-a79a503d37a5" />

2. Use it for sometime, reboot, boom - 
<img width=200 src="https://github.com/z-huang/InnerTune/assets/74096544/5340083b-cddc-41b0-8c1a-ff0e235724f9" />

### Expected behavior

App size should prolly stay same.

### Actual behavior

App size suddenly Increases about 40 mb.

### InnerTune version

0.4.4-debug

### Android version

Android 13 (One UI 5.1)

**Comment by owencz1998** [comment]
That would mostly be due to music being cached and you creating a playlist and ect

**Comment by rickdtc** [comment]
Then it would have got stored in data section or cache, why did the actual app size change?

**Comment by z-huang** [comment]
Maybe it's growing because of installing profiles (https://developer.android.com/topic/performance/baselineprofiles/overview) or being a debug build.

**Comment by rickdtc** [comment]
Just asking, if there is anyway to stop this?
