### ISSUE TITLE
Not displayed lyrics with including newlines

### ISSUE THREAD

**Issue by Denpun1** [z-huang/InnerTune#746]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

(Example)
ーーーーーーー
[XX:XX.XX]apple
banana

ーーーーーーーー

"apple" is displayed
"banana" isn't displayed

### Expected behavior

"banana" is displayed

### Actual behavior

"banana" isn't displayed

### Screenshots/Screen recordings

<img width=200 src="https://github.com/z-huang/InnerTune/assets/110000352/7257fb13-f298-41c7-8083-1150fcf0ec2c" />
<img width=200 src="https://github.com/z-huang/InnerTune/assets/110000352/bf9bf2df-1860-4a48-b238-265f3d519bc2" />
<img width=200 src="https://github.com/z-huang/InnerTune/assets/110000352/3f05b559-8989-4b69-94f3-3db0062a184a" />
<img width=200 src="https://github.com/z-huang/InnerTune/assets/110000352/43e3d8bd-26b7-4d05-942c-f296ce84fdf0" />

### InnerTune version

0.44 Debug

### Android version

Android12

**Comment by z-huang** [comment]
Synced lyrics can't have newlines. Every line should be like `[XX:XX.XX] text`.
