### ISSUE TITLE
Podcasts are not rendering in correctly

### ISSUE THREAD

**Issue by emkay5771** [z-huang/InnerTune#759]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1) search for podcast (WVFRM, for example)
2) click on podcast listing

### Expected behavior

Loads page for podcast

### Actual behavior

Endlessly loads

### InnerTune version

0.5.0

### Android version

Android 13

**Comment by z-huang** [comment]
Any screenshots/screen recordings?

**Comment by emkay5771** [comment]
> Any screenshots/screen recordings?


https://github.com/z-huang/InnerTune/assets/52011243/627b0656-0691-4308-ae6a-4cd2c1f3a6bb

**Comment by z-huang** [comment]
Podcast seems to be available only in the US, so I can't reproduce. However, it's reasonable that InnerTune won't support podcast. This app only focus on music.

**Comment by emkay5771** [comment]
Does this change the plan in any sense? https://9to5google.com/2023/07/13/youtube-music-podcasts-international/
