### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by noClaps** [z-huang/InnerTune#76]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The app should have lyrics for songs, when available. It can be present on the music player screen, and accessible either by tapping the cover ([Retro Music implementation](https://github.com/RetroMusicPlayer/RetroMusicPlayer)), or in a section below the player (YT Music/Spotify implementation).

### Why do you want this feature?

Being able to see the lyrics is a feature present in most music players.

### Additional information

There's another music player, [ViMusic](https://github.com/vfsfitvnm/ViMusic), that displays lyrics to songs. Maybe you can use a similar approach to them to get lyrics? Another option is to use Genius, similar to how [spotdl](https://github.com/spotDL/spotify-downloader) do it.

**Comment by z-huang** [comment]
> Maybe you can use a similar approach to them to get lyrics?

Yes, it's feasible.

**Comment by Reffler** [comment]
I also look forward for this feature! I'm loving the app so far

**Comment by z-huang** [comment]
This will be added along with the player redesign.

**Comment by z-huang** [comment]
Overall feature completed. Additional features to be implemented:
1. Add an option to align lyrics left/center/right
2. Add an option to disable KuGou lyrics provider in privacy settings
3. Add 163 music lyrics provider (if there's many songs that KuGou doesn't have lyrics for)
4. Switch lyrics provider
5. Edit lyrics
6. Keep screen on when lyrics enabled
7. ...

If interested, please try the debug version and report bugs.

**Comment by xmha97** [comment]
Thanks, everything works fine, but how can I copy the lyrics files? (.lrc)

**Comment by z-huang** [comment]
The lyrics are stored as string in the database, so you won't find them in the app's file directory. Maybe I can export them with SAF.

**Comment by z-huang** [comment]
Note: scrolling of the LyricsView isn't smooth enough and needs tweaking.

**Comment by z-huang** [comment]
Now it should be smooth. Feedback welcomed.
