### ISSUE TITLE
"Download all" in album and playlist removes downloaded song

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#762]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download any song in the album/playlist
2. Double click "Download all"

### Expected behavior

Download should be stopped without removing downloaded songs

### Actual behavior

Download stopped and downloaded songs are removed

### InnerTune version

0.5.0

### Android version

Android 11

**Comment by z-huang** [comment]
Like Spotify, you can only download/remove all downloads of a playlist/album.
