### ISSUE TITLE
Square Design Thumbnail Even for Videos added to Library 

### ISSUE THREAD

**Issue by Vishcot** [z-huang/InnerTune#767]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Square Design Thumbnail Even for Videos added to Library just like Vimusic, will enhance the overall look and feel of the player, and saturate thumbnail design of Now Playing..(If Possible)

### Why do you want this feature?

Will look good and beautiful in Now Playing Page and even in Add to Library list, would be a lovely gesture to enhance player section if possible...

**Comment by Vishcot** [comment]
![Screenshot_20230708-002612](https://github.com/z-huang/InnerTune/assets/136909951/81f25656-3362-4108-9a51-58e11c14b0ed)

**Comment by owencz1998** [comment]
Or maybe a option for thumbnail roundness adjustment and set it by numbers so people have a choice.

**Comment by z-huang** [comment]
Video thumbnail is rectangle, so some parts will be cut if cropped to square. Also, we can distinguish between songs and videos by the shape of the thumbnail.
