### ISSUE TITLE
Unknown item type

### ISSUE THREAD

**Issue by Anirban3214** [z-huang/InnerTune#770]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Click on search button 
Search any song
And hit enter

### Expected behavior

![Screenshot_20230708-115606](https://github.com/z-huang/InnerTune/assets/131134012/4c6e3bd5-41db-4d99-8ed2-ab2fc61c57e2)

### Actual behavior

![Screenshot_20230708-114845](https://github.com/z-huang/InnerTune/assets/131134012/24fb5a9e-195f-46ce-b428-5029df285afd)

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/131134012/8daffff7-2d09-4d37-87b7-f9e76752efd5

### InnerTune version

0.4.4

### Android version

Android 11

**Comment by z-huang** [comment]
You're not using the latest version (0.5.0).
