### ISSUE TITLE
Update removed my downloaded songs

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#774]
The newest update uninstalled all my songs now I have to do it all again

**Comment by owencz1998** [comment]
Maybe because he changed the downloads directory may of changed this or if u was using the old version and now using 5.0 this could be the case

**Comment by selurvedu** [comment]
I was unable to manage my previously downloaded songs after this update. There is a new section in InnerTune settings to manage the cache and downloads size, but that showed zeroes, like I have no songs, while in Android settings InnerTune was taking 2 gigabytes of storage.

Actually they were still being stored in `/storage/emulated/0/Android/data/com.zionhuang.music/files`. I didn't want to clean them up manually, and there were some old leftovers of the settings that no longer exist in `/data/data/com.zionhuang.music`, so I decided to wipe InnerTune.

I backed up my library via InnerTune settings, then wiped the application storage via Android settings and then restored from backup. Now when I download a song, it shows up correctly in the storage management settings. I can also simply let it cache while listening and then be cleaned up automatically when my cache reaches the limit.

Of course, it's unfortunate that I had to do all of that manually. There should have been an automatic migration mechanism, or at least a warning / explainer about how to migrate.

**Comment by z-huang** [comment]
> Of course, it's unfortunate that I had to do all of that manually. There should have been an automatic migration mechanism, or at least a warning / explainer about how to migrate.

I apologize for that. I was in a hurry to release a new version and forgot about that. Your migration method is totally correct.
