### ISSUE TITLE
You guys removed the highlighting feature

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#775]
In the past, I could hold down to highlight a song, then scroll down to highlight the rest and then download all, I can't do that now.

**Comment by owencz1998** [comment]
This will maybe be added back this is due to a rewrite of the app but u still have the download all button on playlists section

**Comment by owencz1998** [comment]
> This will maybe be added back this is due to a rewrite of the app but u still have the download all button on playlists section 

When people copy what u say and ignore 🙄

**Comment by selurvedu** [comment]
This also makes it impossible to convert the queue into a playlist or add all of it or a part of it to an existing playlist.

**Comment by z-huang** [comment]
Duplicate of #695
