### ISSUE TITLE
Icons move down when the name of the item consists of one line

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#776]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open song
2. Open menu

### Expected behavior

Perhaps they shouldn't move out.

### Actual behavior

Icons of the menu items are moved if the name consists of two lines

### Screenshots/Screen recordings

![IMG_20230708_201057](https://github.com/z-huang/InnerTune/assets/81887288/c6bb3adc-83d5-45ed-95a9-b82104d2d16a)

### InnerTune version

Latest DEV Debug build

### Android version

App tested on A11, A12 and A13

### Additional information

This is absolutely not a critical visual bug, but I still think I should report it.

**Comment by z-huang** [comment]
It's not a bug.😀
