### ISSUE TITLE
Genre-Adaptive Subtitle and Music Visualization

### ISSUE THREAD

**Issue by AWATV** [z-huang/InnerTune#781]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to propose a new and exciting feature that can greatly enhance the user experience of your music player. I suggest adding visualization of subtitles and music, similar to the "Dive" feature in another player like awa.fm.

Visualization of subtitles and music is an essential attribute of modern music players, as it allows users to dive deeper into the music experience. Imagine that while listening to their favorite songs on your player, users can also enjoy visual effects that correspond to the music and subtitles. This creates an atmosphere where sound and visual representation perfectly blend together, enriching and intensifying the impact of each composition.

Here is an example of how the feature of subtitles and music visualization could look in AWA.fm player:

https://github.com/z-huang/InnerTune/assets/111561766/3d119282-41df-43e3-83c9-c61ebda32804

https://github.com/z-huang/InnerTune/assets/111561766/4ba4ffe7-b6eb-4467-805c-0d53a192ea7a

Adding this feature to your player would enable users to immerse themselves further into the music, creating a more emotional and visually appealing experience. It would also help your player stand out among competitors and attract more users who seek innovative features and enhanced capabilities in music applications.

I believe that incorporating subtitles and music visualization, akin to the "Dive" feature in awa.fm, would be a significant advantage for your player and allow users to enjoy music on a whole new level. I hope you will consider this proposal and take it into account when planning future updates for your player.

### Why do you want this feature?

I want to incorporate the visualization of subtitles and music into the music player because I am impressed by this feature in awa.fm. It adds an extra level of interaction and immersion to the music experience. When I use awa.fm and see how the visualization of subtitles and music corresponds to the mood and rhythm of the song, it creates a stunning visual representation and enhances the emotional impact of each composition. I would love to see the same capability in your player to further enjoy music and feel its energy through visual effects.

**Comment by z-huang** [comment]
Thanks for the very complete description of the feature. However, this feature is too fancy and hard to implement, so I won't add it, sorry.
