### ISSUE TITLE
Ability to add music to playlist from playlist section

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [z-huang/InnerTune#782]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently this is the process for adding a song to a playlist

1. Find the song you want to add
2. Tap the three icons to open the options
3. Select "Add to Playlist"
4. Select the playlist to add it to

With this feature, it would turn to this

1. Go to the playlist you want to add the song to
2. Tap the search bar and find the song you want to add
3. Tap the "Add" button, to which it will be added to the playlist you're on

Bellow is a example that can be found on Spotify;
![image](https://github.com/z-huang/InnerTune/assets/70731807/3c258f32-0549-4edd-9ebb-e13ac2526969)

### Why do you want this feature?

I believe this would make importing of music into a playlist a lot more coinvent for users, especially if the user is moving a lot of songs onto a playlist. For example, I'm wanting to port some of my Spotify playlists manually into InnerTune, which includes playlists that have a lot of songs, which would take while to completely port over. While it would still take a bit of time, this feature would make that process a lot quicker.

**Comment by Jambo199** [comment]
Agreed

**Comment by z-huang** [comment]
Sorry for the late reply. I've been busy these days.
You can click "..." on the song and add it to playlist directly. Is there any misunderstanding?
