### ISSUE TITLE
Tapping Search Result Allows Continue of Searching

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [z-huang/InnerTune#783]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I am a bit tired, so I apologize if the title or the explanation of what I'm requesting isn't the best. Anyways, to continue your search currently, you need to tap the search icon on the top right corner. I believe this is something that is unintuitive to the average users experience using platforms and applications that allow the user to simply tap the search result to resume searching. It's kind of like tapping a Mac/Macbook thinking it has a touchscreen. Many people _expect_ it to have it, but it doesn't. 
 
![image](https://github.com/z-huang/InnerTune/assets/70731807/ed4decee-3d8f-41d0-8898-4ae98cd27111)
![image](https://github.com/z-huang/InnerTune/assets/70731807/441aa6bc-4007-4ff9-92fc-8e72705cf9ce)

### Why do you want this feature?

As stated before, it's something that most users I'd say would expect a search system to work, and adding it to the application would ultimately lead to a more frictionless experience for the user. Also it would make the user not look silly in the process accidentally tapping the search result instead of the search icon since they're just so used to being able to tap the search result to resume searching.

**Comment by z-huang** [comment]
Please update to the latest version (0.5.0).

**Comment by ThatOneUnoriginal** [comment]
When will 5.0 be released on F-Droid? Installed the application through that and it still indicates the latest version is 4.4
