### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [z-huang/InnerTune#786]
ref: https://monitor.f-droid.org/builds/log/com.zionhuang.music/16#site-footer

diff log is small: [inner1.log](https://github.com/z-huang/InnerTune/files/11999148/inner1.log)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/382706e88fb147a242b200537d124d878c42c9d3

/LE: using Java17 instead does not fix it

**Comment by licaon-kter** [comment]
Was `InnerTune_v0.5.0.apk ` build from https://github.com/z-huang/InnerTune/commit/65bb45264448047a76b0c32c61b38fdbd81367b4 as the Tag points?

**Comment by z-huang** [comment]
Yes. Sorry, I can't understand from the log why the build failed.🧐

**Comment by licaon-kter** [comment]
Can you make a clean build, no caches dependencies, run gradle clean before building, etc?

**Comment by z-huang** [comment]
I've invalidated caches, run `gradlew clean`, and built signed apk. Here it is: [app-release.apk.zip](https://github.com/z-huang/InnerTune/files/12003700/app-release.apk.zip)

**Comment by obfusk** [comment]
That one's reproducible :)

**Comment by obfusk** [comment]
So if you replace the APK with that one, the F-Droid build should succeed next time.

**Comment by z-huang** [comment]
Okay, thank you very much!

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/a50564d817525ccc3c672883a9ffd57a9380b679
