### ISSUE TITLE
Make Piped Instance Configurable

### ISSUE THREAD

**Issue by matchboxbananasynergy** [z-huang/InnerTune#801]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It seems that currently, the Piped instance used in InnerTune is hardwired and not configurable, as per https://github.com/z-huang/InnerTune/commit/e13e423c1c2d29f7424747f9fe6b1441158c47f5.

Would it be possible to make it configurable?

### Why do you want this feature?

 Instances can have downtime, or people can prefer to use a different one, maybe even their own instance.

### Additional information

LibreTube, which is a YouTube alternative frontend that utilizes Piped has an instance picker that has a few selections available, as well as the option to use a custom one, so maybe the code there could be re-used?

**Comment by z-huang** [comment]
Piped API will only be used when playing age-restricted songs. The Piped instance will be down, but it's temporary. So, I think it's not that urgent to make it configurable.
