### ISSUE TITLE
play next doesnt work sometimes

### ISSUE THREAD

**Issue by itsmmt305** [z-huang/InnerTune#806]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

>be using app since long time. even in bg. without swiping from recents
>play a song/queue of songs
>choose a song to play next or add to queue

### Expected behavior

the app shud play the song next or add it to queue

### Actual behavior

no alteration in the queue whatsoever

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/94820934/627f9a36-59ed-4cbf-87eb-6124e6f69954

### InnerTune version

0.5.0

### Android version

Android 12 | MIUI 13

### Additional information

i never remove the app from recents. its running in bg all the time
such problems usually happen only after re-envoking app from recents after long. if i close it and restart app everything works fine.

**Comment by owencz1998** [comment]
This is more and likely due to skip silence this can sometimes cause the next song not to play so try disabling in settings and try again.

**Comment by itsmmt305** [comment]
i don't have skip silence turned on

**Comment by owencz1998** [comment]
Oh then that's strange
