### ISSUE TITLE
Can't move downloaded music

### ISSUE THREAD

**Issue by Stu75e** [z-huang/InnerTune#810]
Where are downloaded music stored? In new version(0.5.0)

We had this possibility in previous versions

**Comment by owencz1998** [comment]
Don't think we have access anymore in 5.0

**Comment by Stu75e** [comment]
In the previous version, there was a better category for music, now it is not, the new feature is also the music text, which can be implemented better, like aplayer(https://github.com/rRemix/APlayer).

**Comment by z-huang** [comment]
See #774.
