### ISSUE TITLE
Music pauses and unpauses like crazy hooked up to aux.

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#811]
So I have a google pixel with a USB C port only and I drive an older car, so I use an aux cord then a USB C adapter to listen to music. Ever since this new update, when I plug my phone in, the songs keep pausing and unpausing non stop as if I was hitting the button over and over. I'm assuming that its the new update, as apps like NewPipe don't cut out like that at all and this app never had this problem before.

**Comment by z-huang** [comment]
Still happening?

**Comment by HiddenLeveI** [comment]
It was so I just bought a different brand name adapter, and it seemed to fix the issue. I still don't think my adapter was the issue because newpipe could play fine on there, but a different adapter did seem to fix it. It was strange.

**Comment by z-huang** [comment]
Since you've found ways to fix the issue, I'll close the issue. After all, I have no idea where to find the bug.
