### ISSUE TITLE
bring back innertune downloaded songs storage acces to file manager

### ISSUE THREAD

**Issue by Eldyj** [z-huang/InnerTune#813]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In previous updates I could find "innertune" tab in aosp file manager (crdroid 7 android 11 one)
After 0.5 I can't see it in file manager anymore
Maybe that's because music storage was moved from ~/android/data/package name/files to some else place
After backuping and clearing app data in settings and restoring settings from backup in innertune I still not have this tab (this reset method was found in other issues)

### Why do you want this feature?

When I have access to innertune downloaded songs storage I can copy them to any other place and use for whatever I want
Main purpose of that for me is copying music from phone to USB flashdrive by otg cable

### Additional information

Here is what I have in section where older innertune was in my file manager
![Screenshot_20230713-222703680 (1)](https://github.com/z-huang/InnerTune/assets/103959122/3e0cb6ac-134b-49ff-a5f7-681d86d98b9a)

**Comment by z-huang** [comment]
You can no longer access downloaded songs. After all, InnerTune is a music player, not a downloader. However, the download experience is improved.
