### ISSUE TITLE
Add Piped as an alternative backend.

### ISSUE THREAD

**Issue by rozari0** [z-huang/InnerTune#816]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So currently piped API is only used for age-restricted tracks, but In my country, Yt music isn't available. I have to use a proxy all time but proxies just die after someday. So it would be nice if you can add piped API as an alternative backend.

### Why do you want this feature?

.

**Comment by z-huang** [comment]
Not planned.

**Comment by MuubNito** [comment]
> Not planned.

Just to be sure, are there any reasons?
