### ISSUE TITLE
Downloaded songs doesn't show up on songs tab or anywhere else.

### ISSUE THREAD

**Issue by Anonymous2716** [z-huang/InnerTune#820]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Download a song when listening online from `Home` tab.

### Expected behavior

The song should show up In any tabs like songs , artist tab but it doesn't. I have relaunched the app multiple times after clearing from recent but no change.

### Actual behavior

this issue appeared After i upgraded the app. the songs show up as downloaded in the Home tab which is only available when there is an internet connection. 

Previously cached / downloaded songs shows up in those tabs from previous version of the app.

And the songs show up in `History` section.

This happens only on this version. `0.5.0` izzyOnDroid repo. Previous versions were fine. 

 

### Screenshots/Screen recordings

Don't think you need one.

### Logs

Currently I don't had adb access I'm on android 9. i will post logs if I have access soon . 

### InnerTune version

*0.5.0*

### Android version

*Android 9*

### Additional information

I haven't finished testing with the latest debug version yet. In order to reproduce this behavior. 

Also for me the new version  became too sluggish. Which I blame the compose. I guess you cannot do much about it but letting you know. Probably bcs my phones chipset is not powerful. Phones from recent years shouldn't have this issue.

**Comment by z-huang** [comment]
Downloaded songs won't be automatically added to library. You have to add it to library manually.
