### ISSUE TITLE
Innertube debug 0.5.0

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#821]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Opening the app

### Expected behavior

For the app to open 

### Actual behavior

Crashes when opened.
Says it has a bug

### InnerTune version

Debug 0.5.0

### Android version

Android  12 

### Additional information

None

**Comment by owencz1998** [comment]
Yeah iv just downloaded the latest and now it crashes.

**Comment by owencz1998** [comment]
Thanks for doing that @netrunner-exe
