### ISSUE TITLE
button to force refresh album cover

### ISSUE THREAD

**Issue by itsmmt305** [z-huang/InnerTune#822]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

i guess the app sometimes stores a lower res album art for a song when theres unstable internet connection? and displays it even though it also has a higher res image for another song from the same album but that is not displayed. like see here -

https://github.com/z-huang/InnerTune/assets/94820934/322c2756-8091-4c60-a290-f2039ba600fb

### Why do you want this feature?

there shud be a toggle for rechecking/refreshing album art for each app. or even all metadata. 

### Additional information

meh

**Comment by z-huang** [comment]
Can't reproduce. The app always uses the highest quality thumbnail.

**Comment by owencz1998** [comment]
Clear image cache then play the song again may fix this or remove the song and readd it to your playlist.
