### ISSUE TITLE
Option to follow an artist and in the "New release albums" showing the albums of the followed artist

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/InnerTune#824]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

If there could be an option to follow favorite artist and in the "New release albums" the released albums of our fav artist can be showed

### Why do you want this feature?

In the "New release albums" there are albums i dont want to see or will never listen to, so having albums of fav artists will be much more useful

**Comment by seasidesongs** [comment]
Z-huang said that this will be instigated once the log in element has been added 👍👍

**Comment by dainvincible1** [comment]
> Z-huang said that this will be instigated once the log in element has been added 👍👍

thank you
