### ISSUE TITLE
Searching for songs not working

### ISSUE THREAD

**Issue by Joel198500** [z-huang/InnerTune#825]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to search
Search for a song and then it says unknown item type

### Expected behavior

It should let me search for the song

### Actual behavior

N

### InnerTune version

0.4.4

### Android version

Android 12

**Comment by z-huang** [comment]
Please update to 0.5.0.
