### ISSUE TITLE
Paused music in the background, after some time the play button no longer works

### ISSUE THREAD

**Issue by BluePixel4k** [z-huang/InnerTune#828]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Pause the song after some seconds
3. Move the app into the background
4. Leave the phone 10 minutes untouched
5. Open the app from the background
6. Press play again

### Expected behavior

The song should play again.

### Actual behavior

The play button toggle the state, but the song doesn't play. 

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/77979781/2925bcc9-50d6-455c-8a53-06e60eb8c6ab

### Logs

07-16 12:38:25.236  1811 12088 I InputDispatcher: Channel [Gesture Monitor] swipe-up (server) is stealing touch from [18077b0 com.zionhuang.music/com.zionhuang.music.MainActivity (server), [Gesture Monitor] edge-swipe (server)]
07-16 12:48:23.870  2843  2843 D MediaDataManager: Updating 0|com.zionhuang.music|888|null|10227 timedOut: true
07-16 12:49:20.418  6128  6128 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music
07-16 12:49:20.418  6128  6128 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@d35afed, com.zionhuang.music, 4009)
07-16 12:49:20.426  6128  6128 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music
07-16 12:49:20.426  6128  6128 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@d35afed, com.zionhuang.music, 4009)
07-16 12:49:20.430  6179  6179 V MusicFXControlPanelReceiver: Package name: com.zionhuang.music
07-16 12:49:20.430  6179  6179 V MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@d308ac7, com.zionhuang.music, 4009)

### InnerTune version

0.5.0

### Android version

Android 13

**Comment by M3DZIK** [comment]
I had the same thing, but I also got an error something like "No such file or directory: <something like id, some random characters>".

**Comment by z-huang** [comment]
Should be fixed. Please check.

**Comment by BluePixel4k** [comment]
Thank you, with the latest debug version the bug is gone 👍
