### ISSUE TITLE
Automatic Backup

### ISSUE THREAD

**Issue by anxiouslelimo** [z-huang/InnerTune#833]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

An option to automatically backup on schedule or changes in library. Eg: If i like a new song or add a song to playlist/library an automatic backup is triggered. The backup folder should delete old backups and should keep only last x backups.

### Why do you want this feature?

This would greatly enhance the backup feature and make sure that the backups always stay up to date without user intervention.

**Comment by siggi1984** [comment]
Too bad, would be a great feature.

**Comment by z-huang** [comment]
Backup and restore are used when you're transfering phone data, so I don't think automatic backup is needed.

**Comment by simpel2** [comment]
Id like to add another thumbsup to this recommendation.

I am building my song database on Innertune right now, and if for some reason my phone is lost/stolen or an update wipes the app, all of my liked songs etc are gone.

Im not an experienced developer but it should not be hard to implement. Ie create a new export to a select directory every day, erase old ones after a week. Other FOSS projects such as Aegis, Authenticator pro and Simple Calendar already implemented this.

Examples:
https://github.com/SimpleMobileTools/Simple-Calendar/pull/2027/commits

Hope you reconsider!

**Comment by aayushrautela** [comment]
> Backup and restore are used when you're transfering phone data, so I don't think automatic backup is needed.

Automatic backup is a must have. Phones are prone to breakage/getting stolen and loosing whole song library is such a pain.
