### ISSUE TITLE
0.5.0 debug version 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#836]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Moods and genres
To have this section on the front screen and not on a separate tab
And to maybe swop with quick picks

### Why do you want this feature?

Easier access to the mood and genres sections. Not a fan of the quick picks section.. Any other opinions guys 🤔🤔

**Comment by owencz1998** [comment]
I think it should stay as a tab but add more like once login is completed it says like hi owen (users name) and have my recommendations and more like it knows my favourite artists and more sections that yt has on its home screen but more organised than yt music.

**Comment by Alphamars** [comment]
I would suggest a discover tab, where you can see new artist and new music. Similar albums and playlist you might like.
Just a way to know new music. Thanks

**Comment by seasidesongs** [comment]
Would it be possible to revert to the old layout with the new releases moods and genres to the top section
I am not a fan  of the quick picks section. Sorry. Could we also add a bookmarking option for my favourite artists
Fantastic work
Many thanks

**Comment by z-huang** [comment]
> Would it be possible to revert to the old layout with the new releases moods and genres to the top section
> I am not a fan of the quick picks section.

Quick picks is an important feature for this app. Though it's not ripe enough, I'll improve it gradually. So, I insist on putting it at top.

> Could we also add a bookmarking option for my favourite artists

Working in progress.

**Comment by seasidesongs** [comment]
Many thanks. The mood and genres text overlaps at the bottom and it would be great to have it at the top above quick picks maybe..
