### ISSUE TITLE
Allow for playlists to be exported

### ISSUE THREAD

**Issue by SamIsNotStupid** [z-huang/InnerTune#838]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Allow for playlists to be easily exported in the commonly used m3u format or csv. Playlists can currently be imported into innertune but not exported.

### Why do you want this feature?

Sharing playlists is a useful feature in general, and my personal reason for wanting it is so I can share playlists easier with friends or transfer my data from one mp3 player to another.

**Comment by DementedDuckling** [comment]
I second this. Would be easier to decide to use an app if you had the reassurance you wouldn't be data locked. Innertune is a great app but this is really a deciding feature.

**Comment by z-huang** [comment]
InnerTune can't export media files, so it's impossible to export to m3u. It can only export to a csv file with song ids, but no apps accept this format.
