### ISSUE TITLE
Home screen issue with login 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#839]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Home screen

### Expected behavior

Show the albums and able to chicken on title to show more 

### Actual behavior

Just the title also when clicking on the title it doesn't show anything .

### Screenshots/Screen recordings

<img width=200 src="https://github.com/z-huang/InnerTune/assets/96526481/5141ae06-c9ab-44b2-b142-df35100ad949" 
/>

<img width=200 src="https://github.com/z-huang/InnerTune/assets/96526481/1a5c622d-340c-451b-994c-5fd5da1df9df" />

### InnerTune version

Debug

### Android version

12

**Comment by z-huang** [comment]
Please use latest debug version and provide logs so that I can investigate.

**Comment by owencz1998** [comment]
I'm using the latest and ill try and get the logs when I'm back from work unless someone else has the issue.

**Comment by TheTrashCrafter** [comment]
Not sure if this helps, but it works for me.

**Comment by owencz1998** [comment]
I'm not sure but it happens rather I login to my account or it's after a restore after a backup

**Comment by owencz1998** [comment]
@z-huang I can confirm it's when I login mate

**Comment by TheTrashCrafter** [comment]
@owencz1998 I'm logged in and it works.

**Comment by owencz1998** [comment]
Ha how strange mine only works as long as I dont login

**Comment by owencz1998** [comment]
@z-huang 

https://github.com/z-huang/InnerTune/assets/96526481/5880f33f-f645-4d92-9be7-2a2bbcf017f5

**Comment by z-huang** [comment]
Can you provide a screenshot of browsing https://music.youtube.com/explore with a browser and with your account logged in?

**Comment by owencz1998** [comment]
Shows normal for yt music and  btw I'm on a new device s23 ultra but this was happening on a z fold 3 previously.

![Screenshot_20230724_063839_YouTube Music.jpg](https://github.com/z-huang/InnerTune/assets/96526481/9cf12463-c4a6-4626-973b-76c0aa0d9626)

**Comment by z-huang** [comment]
Please check.

**Comment by owencz1998** [comment]
Fixed the mood and genres but not the new album release section dude

![Screenshot_20230724_112019_InnerTune Debug.jpg](https://github.com/z-huang/InnerTune/assets/96526481/4c3693f0-0b0f-41fa-a932-47bc572c0b8f)

**Comment by z-huang** [comment]
> Can you provide a screenshot of browsing [music.youtube.com/explore](https://music.youtube.com/explore) with a browser and with your account logged in?

"with a browser". The screenshot you provided was taken from ytm app.

**Comment by owencz1998** [comment]
@z-huang still works fine on my browser 

![Screenshot_20230724_153936.jpg](https://github.com/z-huang/InnerTune/assets/96526481/b43c3a0f-e5ac-44d3-a9c5-f9008122639e)

![Screenshot_20230724_153927.jpg](https://github.com/z-huang/InnerTune/assets/96526481/8eea8df6-6d48-4e2b-9714-a68542c98ea2)

**Comment by owencz1998** [comment]
@z-huang Any idea on this dude

**Comment by z-huang** [comment]
I have no idea. We need someone who can reproduce this issue to dig into the cause.

**Comment by owencz1998** [comment]
Ahh no worries dude just odd it happens when I login and that genres works after u fixed that part lol

**Comment by owencz1998** [comment]
@z-huang also it stops me from seeing albums and singles till I'm logged out can this issue be reopened so anyone can see this many thanks 

https://github.com/z-huang/InnerTune/assets/96526481/df41e954-43d7-4fb7-9bb4-84c549c3923a

https://github.com/z-huang/InnerTune/assets/96526481/d08db720-23b9-4da2-80e1-93732a70d7d6

**Comment by z-huang** [comment]
I found another way to fix it. Please check.

**Comment by owencz1998** [comment]
Fixed 😁😁😁thanks so much @z-huang

**Comment by owencz1998** [comment]
Ahh this is now happening to any song I try and stream 

https://github.com/z-huang/InnerTune/assets/96526481/07e3fa9b-7f9d-4282-a2ff-5df15dd006b8

**Comment by owencz1998** [comment]
Oh never mind I closed the app and opened it and its working again a couple of times I've clicked a song but nothing responded had this issue before u fixed the login system but now and then I have to restart the app as iv clicked on a song to and sometimes it skips like 5 songs but plays a completely different artist.
