### ISSUE TITLE
Predictive Back Gesture

### ISSUE THREAD

**Issue by TheTrashCrafter** [z-huang/InnerTune#841]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

The new Predictive Back in Android 14

### Why do you want this feature?

It would be a nice addition to the already very good looking Material Design.

**Comment by z-huang** [comment]
Temporarily not planned.

**Comment by z-huang** [comment]
Hey, it's done!

**Comment by z-huang** [comment]
Previously, my phone is on Android 11, so I cannot experience predictive back. Now I just flashed my phone to PixelOS on Android 14 and it looks great!
