### ISSUE TITLE
Data saver mode

### ISSUE THREAD

**Issue by NeeRaj-2401** [z-huang/InnerTune#842]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

1. An universal option in settings to skip the image loading in entire app. Instead use some preset images such as cover

2. Low sound quality  ( we already have this option, so no need )

### Why do you want this feature?

Skipping images  will save unnecessary data usage.

### Additional information

Useful in case of limited data availability.

**Comment by subham2024** [comment]
Request for disabling of image loading across the app.
And any other data saving feature other than low sound quality.
