### ISSUE TITLE
Unknown Item Type Error after searching any songs

### ISSUE THREAD

**Issue by rajmusic123** [z-huang/InnerTune#843]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the App
After searching any songs getting the Error message as "Unknown Item Type" and no results are displayed.

### Expected behavior

Post searching any songs. Songs lists should be displayed which we can select and play it.

### Actual behavior

Getting Unknown Item Type Error post searching any songs.

### InnerTune version

0.4.4

### Android version

Android 12

### Additional information

 Getting Unknown Item Type Error post searching any songs.

**Comment by owencz1998** [comment]
Please update to 5.0
