### ISSUE TITLE
Showing wrong cover image after switching to lyric view and switching back to cover image view

### ISSUE THREAD

**Issue by Angy-Kitty** [z-huang/InnerTune#846]
### Checklist

- [x] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Click the show lyrics button on the bottom left side of the screen
3. Press the show lyrics button again to show the cover image of the song

### Expected behavior

Show the cover image of the currently playing song 

### Actual behavior

Shows cover image of the first song that user selected.

### InnerTune version

0.5.0

### Android version

Android 10 QKQ1.190910.002

### Additional information

Only happens sometimes.

**Comment by quazar-omega** [comment]
I also noticed that if you reduce the player and bring it back (swipe down and up) the correct album art is shown again

**Comment by z-huang** [comment]
Fixed. Please check.
