### ISSUE TITLE
Moon icon crashes Innertune.

### ISSUE THREAD

**Issue by N3kowarriorCZenchilada** [z-huang/InnerTune#847]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open InnerTune
Start song from songs page
Click on song
Click on moon icon under cover image

### Expected behavior

I dont know because app crashes. But some feature should activate probably :)

### Actual behavior

InnerTune crashes and any playing music stops.

### Logs

[alogcat.2023-07-19-00-18-14+0200.txt](https://github.com/z-huang/InnerTune/files/12089389/alogcat.2023-07-19-00-18-14%2B0200.txt)

### InnerTune version

5.0

### Android version

Android 13

### Additional information

Lineage os 20.0, Oneplus 7 pro, Root

**Comment by DarkCrypt** [comment]
The moon icon is a sleep timer.

**Comment by z-huang** [comment]
The language you're using isn't translated properly. What's your language?

**Comment by N3kowarriorCZenchilada** [comment]
Its Czech, language used in Czech Republic and partly is compatible with slovakia.

**Comment by N3kowarriorCZenchilada** [comment]
I can help you do the translation but i dont have knowledge nor the patience to go thru the site you linked. So if there were easier way to do it let me know.

**Comment by z-huang** [comment]
Fixed. Please check.
