### ISSUE TITLE
Certain songs or albums don't appear in tablet

### ISSUE THREAD

**Issue by SilverShroud4** [z-huang/InnerTune#851]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Enter InnerTune
2. Search certain song or album (ex. Hamilton)
3. Song or album doesn't appear

### Expected behavior

The certain songs and albums should appear

### Actual behavior

The certain songs and albums don't appear

### InnerTune version

0.50

### Android version

Android 13

### Additional information

Works on my phone. (Galaxy S20 FE 5G on Android 23 using InnerTune 0.50)
Tablet: Galaxy Tab S6 Lite

**Comment by z-huang** [comment]
The request to YouTube is the same whether you use a phone or a tablet. Without additional information, I can't do anything.
