### ISSUE TITLE
Contribute translations to the project through a platform that hosts translations

### ISSUE THREAD

**Issue by ShareASmile** [z-huang/InnerTune#853]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

For the project to be very complete in terms of languages.

Reference [z-huang' s-comment ](https://github.com/z-huang/InnerTune/pull/508#issuecomment-1408819604)
 Believing things are stable.^

### Why do you want this feature?

 I believe that choosing a place for people to be able to contribute will help to further enrich the application, for this there are platforms such as: weblate, transifex, codeberg, poeditor...
It also avoids having too many unnecessary project forks.

### Additional information

For more information on deciding WHICH SERVICE to use, read following discussion

mumble-voip/mumble#4641
&
https://github.com/recloudstream/cloudstream/issues/247

**Comment by maboroshin** [comment]
~~Available in Crowdin~~ (Crowdin has closed): https://crowdin.com/project/innertune (The actual pull request is taken from Crowdin. See also PL : https://github.com/z-huang/InnerTune/pull/954)

Related: https://github.com/z-huang/InnerTune/issues/22

**Comment by ShareASmile** [comment]
> Available in Crowdin : https://crowdin.com/project/innertune (The actual pull request is taken from Crowdin.

Thank you, i already noticed that.

Actually, I opened this issue to discuss which translation service to use for the project amongst the options available prior to the decision & making process of decision making for that to be easier & well-informed, but it's up to the owner whether discussing with open source community prior to such important step being taken. About Crowdin being selected for this awesome project, as a translator of open source apps(which i prefer), i am not simply for it, it is [worse amongst the other options as i have used so far](https://github.com/recloudstream/cloudstream/issues/247#issuecomment-1356458738)

**Comment by z-huang** [comment]
Well, I haven't said anything and I didn't close this issue. That means I'm not yet finished with this thing. I'm trying both Crowdin and Weblate and see which one is better. (Crowdin has a better UI I think.)
