### ISSUE TITLE
Offline search

### ISSUE THREAD

**Issue by SomeoneSK** [z-huang/InnerTune#857]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want to search songs from my downloaded songs or from my entire library even when I'm offline. 

### Why do you want this feature?

To quickly play a specific song when I'm offline.

### Additional information

Right now it just shows the loading placeholder forever.

**Comment by z-huang** [comment]
Tracking in #721.
