### ISSUE TITLE
Add all songs from playlist to library

### ISSUE THREAD

**Issue by SomeoneSK** [z-huang/InnerTune#858]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I want a button thats adds all songs from a playlist to my library.

### Why do you want this feature?

I am importing lists from YT music and I want them in my library to see songs by artists, see albums, etc...

**Comment by GourSE** [comment]
Also wanting this

**Comment by Kurasami** [comment]
Yep agreed. This would be absolutely huge. It'd allow us to keep valid playlists online and effectively "push" changes to Innertune on our devices.

**Comment by z-huang** [comment]
Now you can use multi-select to achieve this.
