### ISSUE TITLE
Security Keys Not Supported For Google Account Login

### ISSUE THREAD

**Issue by xi6ei** [z-huang/InnerTune#860]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Login using a Google Account that has a security key for 2FA / enrolled in Google's Advanced Protection Program (where security keys / FIDO2 is mandatory).

### Expected behavior

Login should be available with security keys.

### Actual behavior

A pop-up says "This browser does not support security keys." You'll have to use an alternative method to login.

### InnerTune version

0.5.0 debug

### Android version

13

### Additional information

Not a dev so I'm not sure if this requires an external browser (I'm thinking how apps like Bitwarden implement it).

**Comment by z-huang** [comment]
Android WebView doesn't support FIDO2, so I think it's impossible. An external browser may not be feasible because we need to get the cookies.
