### ISSUE TITLE
I would like to translate the app to Polish language

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [z-huang/InnerTune#866]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I offer to translate the app to Polish language

### Why do you want this feature?

I really like the app and would love to help it spread with my translation offer. ;) I don't want anything in return, just as a hobby.

**Comment by z-huang** [comment]
You can make a pull request. See readme.
