### ISSUE TITLE
Package issue

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#868]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Download latest debig

### Expected behavior

Update 

### Actual behavior

![Screenshot_20230722_205351_Package installer](https://github.com/z-huang/InnerTune/assets/96526481/f0d9a438-5578-40cd-b606-53379082f19f)

### InnerTune version

Debuh

### Android version

12

**Comment by Lurux** [comment]
You probably installed the app from a different source previously, you'll need to uninstall that first.

**Comment by owencz1998** [comment]
I got it from here tho
