### ISSUE TITLE
Move the tempo and pitch settings to a separate pop-up menu

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#874]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Adjusting the tempo and pitch are useful settings, especially for listening to podcasts, etc. but still for normal everyday use they are usually not used that often.  I think it would be a good idea to move them to a separate item in the pop-up menu, right after the equalizer. When you click on the icon of this item, a pop-up window appears, sort of like when we press the sleep timer button and you can place these settings in it, for example, and make sector-by-sector adjustment with a slider, same how time is adjusted in the sleep timer. (just as an idea, good for now too)

### Why do you want this feature?

It seems to me that with this placement of these settings, they will not take up usable space as they are now, plus they are not used as often as other items in this player menu.

**Comment by seasidesongs** [comment]
Is there much demand for this feature 🤔🤔

**Comment by owencz1998** [comment]
Yeah I think it's a pointless feature.
