### ISSUE TITLE
Artists linked to tracks albums and playlists.. 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#877]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Most other music streaming apps link the artist tab to the tracks.. Albums and playlist sections in the library. Please can you possibly link them all together again like the old version. So that we know which songs we have saved for each artist.. This surely is one of the most important features that is currently missing.. 

### Why do you want this feature?

The artists section is the main hub for all songs.. Albums and playlists in the app..

**Comment by seasidesongs** [comment]
Is it going to be possible to implement this as in my opinion this is the most important improvement that could be made
Many thanks

**Comment by Kurasami** [comment]
I personally don't even understand what you're asking as the proposal is so badly defined. If this previously was the case, how about including a screenshot to how it used to be?

Furthermore, you waited only 4 days before making a second comment asking for clarification. This isn't Reddit. If you want a feature added and it's so important, you're free to work on it and submit it yourself. Otherwise provide as clear as possible explanation and reasoning for why it's a necessary feature and why someone should develop it for you, for free.

**Comment by Kurasami** [comment]
If you tap on the arrow to the side, you can see the songs you have in your library in a clearer view too. See:

![Screenshot_2023-07-28-13-53-21-971_com zionhuang music-edit](https://github.com/z-huang/InnerTune/assets/77334270/47461dd3-117e-4bcf-b178-af2ba0a80255)

and now:

![Screenshot_2023-07-28-13-53-47-250_com zionhuang music-edit](https://github.com/z-huang/InnerTune/assets/77334270/a615b9eb-6a24-4068-ae20-8afeaa251937)

**Comment by z-huang** [comment]
Added filters in library artists screen to make it easier to find artists.

**Comment by seasidesongs** [comment]
Many thanks.
I still believe that the old version layout was better. That all the songs for the albums and playlists saved showed in the artists section too. Rather than just single songs that have been saved it for the artists section.. 🤔🤔
Would you reconsider your decision or see what other guys think

**Comment by seasidesongs** [comment]
Apologies.. Because the old version is no longer available I cannot provide a screenshot. Z-huang might be able to provide this information. Showing the old set up 👍👍

**Comment by seasidesongs** [comment]
Great. Thanks 👍👍

**Comment by seasidesongs** [comment]
I have enclosed screen shots of the old version that enabled you to see all of tbe tracks for each respective artist that were saved in an album or playlist as well as individual tracks. This in my opinion would be very helpful.

**Comment by seasidesongs** [comment]
Think this is it 
![Uploading Screenshot_20230809_175256_InnerTune.jpg…]()

**Comment by seasidesongs** [comment]
![Screenshot_20230809_175305_InnerTune](https://github.com/z-huang/InnerTune/assets/122130215/e0937f27-cba4-4e63-9614-d82e3278bb5f)

**Comment by seasidesongs** [comment]
![Screenshot_20230809_175229_InnerTune](https://github.com/z-huang/InnerTune/assets/122130215/20ef42d5-cc96-4246-9d2a-51b2e4948509)

**Comment by seasidesongs** [comment]
Artists 
![Screenshot_20230809_175256_InnerTune](https://github.com/z-huang/InnerTune/assets/122130215/72fcbada-4b9a-4fbf-871f-d075a25b33c3)

**Comment by seasidesongs** [comment]
Re the screen shots above. These are from version 0.4.4.
Is it possible to instigate this in the latest version.. I believe that this would be much more useful. This would better than book marking artists and then only having saved tracks rather than the saved albums and playlists for each respective artist
Great work to date.. And more coffees to be purchased for you Sir 👍👍

**Comment by z-huang** [comment]
Sorry, I won't change it back. People may not want all album/playlist songs to be added to the library. If I interpreted your meaning wrong, please explain what you mean again clearly.

**Comment by seasidesongs** [comment]
Of course. So for instance when I add an album to the library. All of the songs in the album would also show up in the artist section. My opinion is that i would not find it very useful to have artists saved / bookmarked with just random songs saved.. 
Regards

**Comment by seasidesongs** [comment]
Or maybe the option to chose how the library is set up. So that you can chose if you want the albums and playlists included in the artists section

**Comment by z-huang** [comment]
So, you want the artist songs screen to show all zir songs from library, albums and playlists. But it currently shows the songs only from library. Just add songs to library if you want them to show in the artist songs screen. As I said, people may not want all album/playlist songs to be added to the library.

**Comment by seasidesongs** [comment]
Many thanks.. Is it worth doing a poll to see if people would want this feature.. Any thoughts guys 🤔🤔

**Comment by seasidesongs** [comment]
Actually i wll buy you 20 coffees if you bring the feature back 🤣🤣
