### ISSUE TITLE
Speed and pitch 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#878]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Is there any need for this feature.i just want to play my songs at the normal speed 

### Why do you want this feature?

I do not that think that there is much demand for this feature

**Comment by airon90** [comment]
> Is there any need for this feature.i just want to play my songs at the normal speed

The fact that you want to play songs at the normal speed doesn't imply that people who wants to play songs or podcast at another speed or pitch aren't allowed to do that.
