### ISSUE TITLE
Unknown error message 

### ISSUE THREAD

**Issue by seasidesongs** [z-huang/InnerTune#880]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

When i try and stream a track that has not been downloaded i get an unknown error message.. And the track will not play 

### Expected behavior

The track should play 

### Actual behavior

The track does not play

### InnerTune version

0.5.0 debug

### Android version

Andoid 13

**Comment by Kurasami** [comment]
No one is going to be able to debug this without even a screenshot or video, or log dude.
