### ISSUE TITLE
Support Discussion

### ISSUE THREAD

**Issue by decipher3114** [z-huang/InnerTune#882]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Creation of a support group on Telegram/Discord for better communication and support.

### Why do you want this feature?

Everything is not appropriate to be discussed in the GH issues.

**Comment by owencz1998** [comment]
I've already offered this but sadly he won't do it tho it's easier to upload screenshots or even videos without the limits that github has and also you can connect github to discord using Webhooks and possible more moderators so they can help remove duplicate issues and feature requests.

**Comment by decipher3114** [comment]
I can try taggin' him to pull his attention.

@z-huang, Please check this out. It has become necessary as a huge number of people can efficiently report issues in Telegram or Discord Discussion.

**Comment by owencz1998** [comment]
I wouldn't bother he won't change his mind but it's his choice and I respect that u may as well close this issue
