### ISSUE TITLE
No shuffle on Android Auto

### ISSUE THREAD

**Issue by Elaborendum** [z-huang/InnerTune#888]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open any saved playlist and begin playing it, tap the full list of songs. There's no shuffle button.

### Expected behavior

In past versions, there was a shuffle option available when playing a playlist.

### Actual behavior

No shuffle button.

### InnerTune version

0.5.0

### Android version

Android 12

### Additional information

I'm not sure if this actually counts as a bug or just something missed during the rewrite. The addition of a shuffle button is included on the 0.4.4 release notes, but 0.5.0 doesn't mention any removal.

**Comment by zachvlat** [comment]
I reopen this because its not implemented. Except if I m missing something...

**Comment by moralesnery** [comment]
I'm on 0.5.3 and there's no shuffle option in any list when using Android Auto. It's there if you use the app in your phone.
