### ISSUE TITLE
需要通过共享链接批量导入播放列表的功能

### ISSUE THREAD

**Issue by daniloy** [z-huang/InnerTune#891]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

需要通过共享链接批量导入播放列表的功能

### Why do you want this feature?

用youtube music 很长时间了，列表里有很多歌曲，想一次导入播放列表，这样会方便很多。

### Additional information

无

**Comment by z-huang** [comment]
English please.
