### ISSUE TITLE
How can I access downloaded songs from files?

### ISSUE THREAD

**Issue by HiddenLeveI** [z-huang/InnerTune#893]
After the big update, I can no longer see my downloaded songs in my files, they're only in the app. Is there a way to change this? I was hoping to copy and transfer songs over to my PC.

**Comment by z-huang** [comment]
You won't be able to access them. InnerTune is a music streaming app, not a music downloader.

**Comment by HiddenLeveI** [comment]
But then how do I have songs downloaded?
