### ISSUE TITLE
Add support for Proxy Authentication

### ISSUE THREAD

**Issue by wongwengtim** [z-huang/InnerTune#897]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To support proxy with username/password for either HTTP/SOCKS proxy.

### Why do you want this feature?

At this moment, InnerTune does not support proxy with username/password for either HTTP/SOCKS proxy. I would like to add username/password auth for my proxy to prevent port scanning.

**Comment by z-huang** [comment]
Duplicate of #278
