### ISSUE TITLE
Searching is not working in "unavailable region" with YT Music Premium, as searching doesn't carry login cookies

### ISSUE THREAD

**Issue by wongwengtim** [z-huang/InnerTune#899]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Login a YouTube Premium account with latest debug version
2. Search for music

### Expected behavior

Return all results, since YT Music Premium member can access YT Music in "unavailable" region.

### Actual behavior

Return no/very few results. (Shuffle/Music Playback works).
I recommend a global switch for user in unavailable region with YT Premium, to contain login cookies in every request (so no proxy will be required for them).

### InnerTune version

0.5.0-debug (2bc8a40)

### Android version

Android 13

### Additional information

This commit also breaks some recommendation in Home tab.

Btw add support for proxy with auth (username/password) is also appreciated.

**Comment by wongwengtim** [comment]
[dev@2bc8a40](https://github.com/z-huang/InnerTune/commit/2bc8a401ef7d049f709f1c1a8212c8c1c0541c01) The problem is related to this commit.

**Comment by z-huang** [comment]
> If you're in region that YouTube Music is not supported, you won't be able to use this app unless you have proxy or VPN to connect to a YTM supported region.

**Comment by wongwengtim** [comment]
I can confirm that I'm able to access YTM with Premium account before this commit. And this is one of the benefits for Premium account (access from unavailable region).

> Premium memberships & travel
> > YouTube Music Premium:
If you're a YouTube Music Premium or a YouTube Premium member, you get access to your paid membership benefits and your music library in the YouTube Music app. You will have access even if you're in a country/region where YouTube Music isn't available.

**Comment by z-huang** [comment]
Due to privacy concerns, the app will only use login cookies when necessary (e.g. accessing playlists and getting streams). Also, the response alters when logged in, which makes trouble in parsing. Therefore, I'd rather give up support for regions that YTM is not supported. You can either use proxy or contribute code to solve the problems such as #839.
