### ISSUE TITLE
Edit Tabs

### ISSUE THREAD

**Issue by FarisArabia** [z-huang/InnerTune#903]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

hello, this feature was in the older version of InnerTune but seemingly it has been removed but it basically allows me to hide certain tabs or pages i don't care for, would be really helpful, bonus if removing all tabs hide the bottom bar and keeps the songs tab.

### Why do you want this feature?

convenience 

### Additional information

None

**Comment by M00NJ** [comment]
I used this feature as well and would like to see it again. It was added by Bnyro in #289 and got removed when the ui was rewritten in compose.
