### ISSUE TITLE
"Selection Brightness" freezes when using mouse scroll.

### ISSUE THREAD

**Issue by MuubNito** [z-huang/InnerTune#904]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Get a Mouse and use it on a phone / virtual machine.
2. Go to a search query or a playlist. (This is probably on everything with a list selection)
3. Put the mouse cursor on a grid.
4. Scroll up/down. You will have 2 grids appearing as selected, even though only the mouse cursor one is.

### Expected behavior

The bright grid should only be the one the mouse is on.

### Actual behavior

You will have 2 grids appearing as selected, even though only the mouse cursor one is.

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/122548283/016f0a06-7703-4f2b-8b3b-4220b7b51a08

### InnerTune version

0.5.0

### Android version

Android 13

**Comment by z-huang** [comment]
Not a big deal.
