### ISSUE TITLE
Make the Favorite Playlist like a normal one

### ISSUE THREAD

**Issue by christian179717** [z-huang/InnerTune#905]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

So you can download the whole playlist with one button or add it to the queue

### Why do you want this feature?

It's very difficult to download every song alone

**Comment by siggi1984** [comment]
yes that would be really great.

**Comment by z-huang** [comment]
Liked and downloaded songs are merged into songs tab with filters, so what you need is multiple selection (#695).
