### ISSUE TITLE
SponsorBlock integration? 

### ISSUE THREAD

**Issue by mridiot0** [z-huang/InnerTune#906]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hey I was if you have any plan to integrate sponsorblock features in the app. Like if I play songs from YouTube sometimes its irritating the like and subscribe notifier. And the skip silence feature doesn't work on that. So may be if you could enable [SponsoreBlock](https://sponsor.ajay.app/) in the app that would be amazing. 

### Why do you want this feature?

This causes problems in listening the music.

**Comment by Kurasami** [comment]
I would absolutely happily pay a large donation for this feature. I already use Sponsorblock with NewPipe.

**Comment by z-huang** [comment]
YouTube Music songs don't have non-music parts. There's no need for SponsorBlock.

**Comment by z-huang** [comment]
Duplicate of #495

**Comment by mridiot0** [comment]
Yes, there are videos that are from YouTube needs SponsoreBlock as they have channel intro/outro or some talking parts (no music).
