### ISSUE TITLE
Some missing features 

### ISSUE THREAD

**Issue by Dahal50** [z-huang/InnerTune#907]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

This is a best client for ytm right now but it misses some of the general features like:-
1. Sign in
2. Related tab like in yt music original
3. The UI is not that good but the last version has good UI .if there was UI like original app to find best music recommendations that would be great
4. Some of useless tab like artists,songs etc should be kept in one tab 
5. The video will not play so option to switch between song and video is needed

### Why do you want this feature?

Just these are general features to be added

### Additional information

If you can manage these features then it would be great
I was trying to switch from yt music Vanced but it lags in such normal features
Hope you solve these issues and make best ytm client.
Thanks in advance 🙂

**Comment by z-huang** [comment]
> This issue contains only one feature request.

Hey, please pay respect to the checklist.
