### ISSUE TITLE
Song stops playing in between

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/InnerTune#908]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play FE!N by Travis Scott for sometime then the song stops. 
I don't know if this will happen for everybody or not but it happens for me.

### Expected behavior

The song shouldnt stop playing

### Actual behavior

The song stops playing

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/127825700/5cfa0930-607f-4b3d-aef8-7d6ae7bcceb0)

### InnerTune version

0.5.0

### Android version

Android 11

**Comment by z-huang** [comment]
Maybe fixed. Please check the latest commit.
