### ISSUE TITLE
Add ability to show more than 3-4 songs in search results

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#912]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Make it possible to show more than three songs in search results. 

### Why do you want this feature?

I think it would be nice to make it possible to show more than three songs in the search results by adding **>**

### Additional information

![IMG_20230801_090715](https://github.com/z-huang/InnerTune/assets/81887288/47932100-2c9c-4d9c-9d0c-b18694472770)

**Comment by z-huang** [comment]
There's a difficulty recognizing the filter that the section corresponds to. Also, you already have the filters at the top to show more results.
