### ISSUE TITLE
It's not possible to remove songs from a playlist

### ISSUE THREAD

**Issue by christian179717** [z-huang/InnerTune#915]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Add a song to a playlist, try to remove it, either via the menu (long press) or swipe left or right.

### Expected behavior

Song should be removed

### Actual behavior

No option to remove

### InnerTune version

0.5.0

### Android version

Android 9

**Comment by owencz1998** [comment]
Swipe remove works

**Comment by owencz1998** [comment]
@christian179717

**Comment by christian179717** [comment]
https://github.com/z-huang/InnerTune/assets/89655752/9d393cfb-980d-4df0-9e63-a061873526e4

**Comment by christian179717** [comment]
Aah, okay thank you, but I think that this is a very inconvinient way.

**Comment by owencz1998** [comment]
> Aah, okay thank you, but I think that this is a very inconvinient way.

I think it's the best way as you can accidentally swipe and delete by having the lock your unable to make a mistake though I would like there to be a delete button but maybe only shows if the lock is turned on
