### ISSUE TITLE
Cue should be constant

### ISSUE THREAD

**Issue by christian179717** [z-huang/InnerTune#916]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

If you paused the playback and close the app the running cue is deleted. Before the last update that wasn't.

### Why do you want this feature?

If you have made a cue and want to listen to this about a long time, this makes it unpossible.

**Comment by nvllz** [comment]
@z-huang it's still a problem. Despite the 'persistent queue' setting, it's almost always gone for me after closing the app.
