### ISSUE TITLE
No stream available 

### ISSUE THREAD

**Issue by owencz1998** [z-huang/InnerTune#921]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search for the song and play it.

### Expected behavior

Should play the song

### Actual behavior

No stream available 

### Screenshots/Screen recordings

![Screenshot_20230803_152258_InnerTune Debug](https://github.com/z-huang/InnerTune/assets/96526481/bf3cfc75-8b89-406a-84bb-99bd6c4c9c04)

### InnerTune version

Debug latest 

### Android version

13

### Additional information

Happens to a lot of songs I search for sometimes it's a hit or miss.

**Comment by owencz1998** [comment]
@z-huang this is getting worse hardly any of my songs work anymore mate

**Comment by z-huang** [comment]
Does it work if you clear app data?

**Comment by owencz1998** [comment]
I can give it ago I tried with the clearing cache but if I backup I'm worried it will carry the issue within the backup but this also happens in both debug and full release

**Comment by owencz1998** [comment]
Something must of gone funny after testing so many versions lol but I've done something and now it's working so far lol 😆

**Comment by owencz1998** [comment]
Ahhh nah I'm still getting the no stream issue on songs that used to work.😔

**Comment by owencz1998** [comment]
@z-huang this is also happening and some songs don't stream.

https://github.com/z-huang/InnerTune/assets/96526481/6c099fd9-4798-4eae-9f8e-1767592dd457

**Comment by Donald-Win** [comment]
> @z-huang this is also happening and some songs don't stream.
> 
>  Screen_Recording_20230804_085810_InnerTune.Debug.mp4

I have been having this same issue

**Comment by Kurasami** [comment]
Works fine for me. It's likely a bad connection. Try downloading the song and then playing it.

**Comment by owencz1998** [comment]
Found the issue overtime a backup file will have something backed up and causing a issue maybe after updating its still backing up a issue so I've made a new backup and now it's fine.
