### ISSUE TITLE
To show new albums of bookmarked artists in the "new release album" section

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/InnerTune#927]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

To show new albums of bookmarked artists in the "new release album" section

### Why do you want this feature?

In youtube music we get notified when the artist im following releases a new album. So if the "new release albums" section shows new albums of bookmarked artists it'll be very helpful

**Comment by z-huang** [comment]
There's no direct API to do so.
