### ISSUE TITLE
Crash on searching in all genre

### ISSUE THREAD

**Issue by PranavPurwar** [z-huang/InnerTune#929]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search for the term `i get the bag luka` on innertune in `All` places.

### Expected behavior

The search should be successful without any crashes.

### Actual behavior

The app crashes

### InnerTune version

v0.5.1

### Android version

Android 9

### Additional information

If I quickly change the filter to `SONGS` before it loads, there is no crash, might be an issue with item rendering. Other searches seem to work fine. Not sure if this is a very specific bug, but I think it may be frequent in the future as more and more users use InnerTune.

**Comment by z-huang** [comment]
Thanks for reporting. If you search this query in YouTube Music, it gives you the same song twice, which results in the crash.
