### ISSUE TITLE
queue editing issues

### ISSUE THREAD

**Issue by itsmmt305** [z-huang/InnerTune#931]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

edit a queue. make sure the position number of now playing song is altered.

### Expected behavior

the song playing at the moment should not change

### Actual behavior

the new song now at the position number of now playing song starts playing and playback is hindered.
i.e. song gets **replaced**

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/94820934/1fd7eecd-03c7-448b-95e3-883c782c631c

### InnerTune version

0.5.0+

### Android version

Android 12 | MIUI 13

### Additional information

listen to imagine dragons theyre real good like FIIREEE fr ong their old albums... dude! oml! im like in heaven listening to smokes+mirrors. GO GO LISTEN!!

**Comment by z-huang** [comment]
Try the latest commit.
