### ISSUE TITLE
When logged in - display nickname and email in the settings instead of an empty space

### ISSUE THREAD

**Issue by netrunner-exe** [z-huang/InnerTune#932]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When logged in - display nickname and email in the settings instead of an empty space.

### Why do you want this feature?

It seems to me that it will look much better than just an empty space. 

Current:
![Screenshot_2023-08-04-14-28-19-070_com zionhuang music debug](https://github.com/z-huang/InnerTune/assets/81887288/0468ae68-2c21-4076-b394-380b86a157c6)

Proposed:
![IMG_20230804_143320](https://github.com/z-huang/InnerTune/assets/81887288/1ca67b51-f58a-4f73-b826-9d2976229233)

**Comment by z-huang** [comment]
Can you find any network request error from the logs? (keyword: ktor)
The app does make a request to get your name and email after logged in. I think there're different outputs from youtube that makes response parsing fail.

**Comment by wongwengtim** [comment]
Not sure if this helps. No error log from io.ktor.client.network.sockets. I captured the possible request/response from browser.

![image](https://github.com/z-huang/InnerTune/assets/32707423/84d82b60-4f06-4389-a7e6-895d1f86a3d8)

![image](https://github.com/z-huang/InnerTune/assets/32707423/3f25f287-c73f-41a4-afe4-51c40481dae0)

**Comment by owencz1998** [comment]
@z-huang was that meant to be fixed as I've still got the issue even after updating 😅 

![Screenshot_20230806_134905_InnerTune Debug.jpg](https://github.com/z-huang/InnerTune/assets/96526481/c2eca17a-df33-4dd0-8f72-999b0922792d)

**Comment by z-huang** [comment]
Go into the webview, wait for the webpage to load, and return. You're name and email will show.

**Comment by owencz1998** [comment]
@z-huang So click on login again and wait for the website to load

**Comment by wongwengtim** [comment]
@owencz1998 Clear app data and try again.

**Comment by owencz1998** [comment]
@wongwengtim just tried but didn't fix the issue

**Comment by z-huang** [comment]
@owencz1998 If that isn't the case, I need logs because there may be other problems.

**Comment by owencz1998** [comment]
No worries ill see if I can get software to run again due to laptop issues

**Comment by z-huang** [comment]
If you can't get your name and email shown, please provide logs.

**Comment by wolf-yuan-6115** [comment]
> If you can't get your name and email shown, please provide logs. I want to solve this before releasing 0.5.2.

Hello, I have same issue and 2FA is enabled on my account. It might be the reason.

**Comment by z-huang** [comment]
I also have 2FA enabled, but it works well...

**Comment by wolf-yuan-6115** [comment]
> I also have 2FA enabled, but it works well...

I just tried with my other account without 2FA, still the same issue. But after logging into both accounts, it just stays at the YouTube music homepage, is that normal?

**Comment by MLZ94** [comment]
[logcat.txt](https://github.com/z-huang/InnerTune/files/12498015/logcat.txt)
@z-huang i got this issue too so here is a logcat (taken with basic "adb logcat". if you prefer something else let me know and i'll give it too).

here is then steps i did
- launche adb logcat (phone was on innertune home menu, and it's already logged in to an account)
- open innertune settings
- open connectivity settings (the page to log in into the account. not sure what's the english string for it)
- click on the account avatar (the name is not displayed)
- let web view show yt music menu
- come back to innertune settings 
- the name is still not displayed
- end logcat capture


let me know if you want further details

**Comment by MLZ94** [comment]
yeah actually that's the part you need, i'll avoid spreading my entire logcats. let me know if you still need more details

**Comment by z-huang** [comment]
There's no `email` field in your response, so the app can't get your email. Can you provide the response of `account_menu` from your web browser?

![image](https://github.com/z-huang/InnerTune/assets/32707423/3f25f287-c73f-41a4-afe4-51c40481dae0)

**Comment by z-huang** [comment]
Current fix is to ignore the missing email.

> There's no email field in your response, so the app can't get your email. Can you provide the response of account_menu from your web browser?

This is still required to fully fix the bug.

**Comment by owencz1998** [comment]
Same for me it's showing username 1 step closer lol yay

**Comment by MLZ94** [comment]
> There's no `email` field in your response, so the app can't get your email. Can you provide the response of `account_menu` from your web browser?
> 
> ![image](https://user-images.githubusercontent.com/32707423/258575354-3f25f287-c73f-41a4-afe4-51c40481dae0.png)

How do i get this screen ?

**Comment by MLZ94** [comment]
> Current fix is to ignore the missing email.
> 
> > There's no email field in your response, so the app can't get your email. Can you provide the response of account_menu from your web browser?
> 
> This is still required to fully fix the bug.

Can you elaborate about the steps i need to follow to give you the informations you want ?

**Comment by z-huang** [comment]
- Open your browser, go to `music.youtube.com`
- Press `F12` to open developer tools
- Select `Network`
- Select the request of `account_menu`
- Select `Response`
- Copy the text below and send it to me

<img width="800" alt="screenshot" src="https://github.com/z-huang/InnerTune/assets/39427017/78fd9676-337d-467c-a3bd-8d4be1edf886">

**Comment by MLZ94** [comment]
> * Open your browser, go to `music.youtube.com`
> * Press `F12` to open developer tools
> * Select `Network`
> * Select the request of `account_menu`
> * Select `Response`
> * Copy the text below and send it to me
> 
> <img alt="screenshot" width="800" src="https://user-images.githubusercontent.com/39427017/265251243-78fd9676-337d-467c-a3bd-8d4be1edf886.png">

I emailed you the output to zionhuang1107@gmail.com for privacy reasons. Tell me if you need something else.

**Comment by wolf-yuan-6115** [comment]
> * Open your browser, go to `music.youtube.com`
> 
>     * Press `F12` to open developer tools
> 
>     * Select `Network`
> 
>     * Select the request of `account_menu`
> 
>     * Select `Response`
> 
>     * Copy the text below and send it to me
> 
> 
> <img alt="screenshot" width="800" src="https://user-images.githubusercontent.com/39427017/265251243-78fd9676-337d-467c-a3bd-8d4be1edf886.png">

I think I found the problem, if you have an account **that have created a channel**, email won't come up because it's showing your channel handel.

Screenshots:

Account with channel created, and have configured a channel username:
![image](https://github.com/z-huang/InnerTune/assets/58245644/1188e2d9-bc6b-4510-90a5-b225def11f3b)

Account without a channel, no username set:
![image](https://github.com/z-huang/InnerTune/assets/58245644/e04f37b4-30c5-493d-ad77-5198c472bf75)

Same account as above one, after creating channel:
![image](https://github.com/z-huang/InnerTune/assets/58245644/3f30a678-8d3a-400a-9188-ba52cb9829a0)

**Comment by MLZ94** [comment]
> > * Open your browser, go to `music.youtube.com`
> >   
> >   * Press `F12` to open developer tools
> >   * Select `Network`
> >   * Select the request of `account_menu`
> >   * Select `Response`
> >   * Copy the text below and send it to me
> > 
> > <img alt="screenshot" width="800" src="https://user-images.githubusercontent.com/39427017/265251243-78fd9676-337d-467c-a3bd-8d4be1edf886.png">
> 
> I think I found the problem, if you have an account **that have created a channel**, email won't come up because it's showing your channel handel.
> 
> Screenshots:
> 
> Account with channel created, and have configured a channel username: ![image](https://user-images.githubusercontent.com/58245644/265251806-1188e2d9-bc6b-4510-90a5-b225def11f3b.png)
> 
> Account without a channel, no username set: ![image](https://user-images.githubusercontent.com/58245644/265251833-e04f37b4-30c5-493d-ad77-5198c472bf75.png)
> 
> Same account as above one, after creating channel: ![image](https://user-images.githubusercontent.com/58245644/265251896-3f30a678-8d3a-400a-9188-ba52cb9829a0.png)

That's right. For my account which has a channel, it's showing the channel handle as channelHandle instead of my full email. It would be fine if the app try to catch both and returns the one that is not null
