### ISSUE TITLE
When i click on a song it plays another song

### ISSUE THREAD

**Issue by dainvincible1** [z-huang/InnerTune#936]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://github.com/z-huang/InnerTune/assets/127825700/0f95954e-351c-4529-89a4-b6d037a6996f

### Expected behavior

It should play the song i chose to play

### Actual behavior

when i choose to play a song, it plays another song

### InnerTune version

0.5.1

### Android version

11

**Comment by z-huang** [comment]
Several users have reported this bug, but I can't reproduce it in two phones. Is there any steps to produce this bug?

**Comment by dainvincible1** [comment]
> Several users have reported this bug, but I can't reproduce it in two phones. Is there any steps to produce this bug?

for me this happens when i play a song from "history" or "stats" section or when i search the song which is there in the "history" or "stats" section. but when i play the song from "songs" it plays perfectly.

**Comment by dAtA-TRoN** [comment]
I encountered the same bug yesterday when trying to manually select a different song in a current playlist. It couldn't be selected and just kept jumping to the next song no matter how many times I tried it.

**Comment by dainvincible1** [comment]
> I encountered the same bug yesterday when trying to manually select a different song in a current playlist. It couldn't be selected and just kept jumping to the next song no matter how many times I tried it.

yeah same here...even the song i search, it keeps changing. i tried uninstalling the app but it didnt work 😢

**Comment by z-huang** [comment]
I think it's the horizontal pager that cause the bug. Try the latest commit.
