### ISSUE TITLE
Someone put this on Playstore snd took credit for it

### ISSUE THREAD

**Issue by xplshn** [z-huang/InnerTune#937]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

https://play.google.com/store/apps/details?id=com.zionhuang.music

### Expected behavior

When you enter play store and do a report, do it under the premise the app violates YouTube's and Playstore's TOS. And not that he used your work, otherwise, they'll also file a report against you.

### Actual behavior

https://play.google.com/store/apps/details?id=com.zionhuang.music

### Screenshots/Screen recordings

Hate this template bs

### Logs

Noneed

### InnerTune version

all

### Android version

kskm

**Comment by owencz1998** [comment]
Please close this as this is already known
