### ISSUE TITLE
Configured Proxy is not used for Account Login

### ISSUE THREAD

**Issue by wongwengtim** [z-huang/InnerTune#938]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

The configured proxy is not used for account login. This makes it impossible to obtain cookies after logging into the account in unsupported region. Using a system-wide VPN can complete the login once, but since there is no way to know when the cookies need to be refreshed, it's causing additional trouble in subsequent use.

### Expected behavior

The configured proxy was used.

### Actual behavior

The configured proxy was not used. It redirects me to YTM Google Play app after logged in.

### Screenshots/Screen recordings

![image](https://github.com/z-huang/InnerTune/assets/32707423/e46a240d-a94e-43fc-8366-24622540d358)
![image](https://github.com/z-huang/InnerTune/assets/32707423/9eb6ba73-833d-48be-90d2-b10ddfde4a37)

### InnerTune version

0.5.1-release

### Android version

Android 13

**Comment by z-huang** [comment]
There seems to be no easy workaround. Leave it as contribution only and not planned.
