### ISSUE TITLE
Add the "Explore" section back to version 0.5.0

### ISSUE THREAD

**Issue by Simipfaffi** [z-huang/InnerTune#942]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hi, although I find the new random function of the dice button interesting, I would like to have back the "exploration area" where you could choose between genres and moods.  I found it good for searching for new styles and songs. As far as I know, it was also the only way to find playlists created by YouTube Music itself. That's why I ask that it be reintroduced. For example, it could be placed in the area where the three buttons "History", "Stats" and "Settings" are now. There you could simply add a button called "Explore". I hope that my wish can be implemented. I also believe that many other users would like to have this function again.

With kind regards Simon

### Why do you want this feature?

I found it good for searching for new styles and songs. As far as I know, it was also the only way to find playlists created by YouTube Music itself. That's why I ask that it be reintroduced.

**Comment by dainvincible1** [comment]
in the latest version there is a genre and mood section

**Comment by Simipfaffi** [comment]
Hi, thanks for the reply :-)

Where can this function be found then?

**Comment by dainvincible1** [comment]
> Hi, thanks for the reply :-)
> 
> Where can this function be found then?

update it to the latest version 0.5.1 then open home then page scroll down and you'll find genre and mood section

**Comment by Simipfaffi** [comment]
ok thanks. The version is not yet available in F-Droid for me. Then I thank you for the answers. InnerTune is a great app. Since the Explore function does exist, I think the new update is wonderful. Keep up the good work :+1:

**Comment by dainvincible1** [comment]
> ok thanks. The version is not yet available in F-Droid for me. Then I thank you for the answers. InnerTune is a great app. Since the Explore function does exist, I think the new update is wonderful. Keep up the good work 👍

thank the dev for making such a good app, im just a fan of the app
