### ISSUE TITLE
Notification player control and widget request 

### ISSUE THREAD

**Issue by tanmaytez** [z-huang/InnerTune#947]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There is no next and previous buttons to change track in from notification itself.. Okay I understood that I'm the only one experiencing this but look after it. I'm using realme x50 pro running on Android 12

And also provide a decent widget for playback control, it'll be a lot useful!

### Why do you want this feature?

Widget and ability to change track from notification 

### Additional information

<img width=200 src="https://github.com/z-huang/InnerTune/assets/132748284/5785ee22-1798-4ec7-a838-ceab953bbdb2" />

You can see it here

**Comment by dainvincible1** [comment]
mine has next and previous options
![image](https://github.com/z-huang/InnerTune/assets/127825700/b2b067ee-41c0-4af6-b35d-eff5291426b1)

**Comment by TheTrashCrafter** [comment]
Seems like an issue with your OEM. On AOSP (and Pixel of course) it works.

**Comment by tanmaytez** [comment]
Oh..

**Comment by tanmaytez** [comment]
What does it mean by won't fix and not planned?..

**Comment by TheTrashCrafter** [comment]
@tanmaytez It means that the issue won't get fixed. Probably because it seems like a problem with your version of Android, and not InnerTune.

**Comment by z-huang** [comment]
> What does it mean by won't fix and not planned?..

The code of the notification is written following Android media3 library. It seems that the bug is caused by the OEM. I don't have a realme device and I can't find out why it's not showing all the buttons. Sorry that I can't provide full support.

**Comment by dainvincible1** [comment]
> > What does it mean by won't fix and not planned?..
> 
> The code of the notification is written following Android media3 library. It seems that the bug is caused by the OEM. I don't have a realme device and I can't find out why it's not showing all the buttons. Sorry that I can't provide full support.

i use a realme device and all the buttons are showing in mine

**Comment by DarkCrypt** [comment]
> Do you know any good alternative for this app?

@tanmaytez 
Yep, check my [stars](https://github.com/DarkCrypt?tab=stars).
