### ISSUE TITLE
Implement 256kbps quality 

### ISSUE THREAD

**Issue by max5354** [z-huang/InnerTune#948]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It will be great if you implement 256kbps audio quality. Other apps like ytm rvx, Blackhole, ViMusic already have 256kbps quality for free. You can take reference from that apps. If possible than plz introduce/implement 255kbps quality. Innertune is only stable app now cause blackhole have some glitches, vimusic's developer drop development, also ytm rvx is discontinued. So it's bestest best idea to implement 256kbps quality. I hope you will implement it

### Why do you want this feature?

Cause other apps also providing 256kbps for free

**Comment by z-huang** [comment]
You have created this request so many times. It's not possible to have 256 kbps quality unless you're logged in with a YouTube Premium account. Please don't create such issue anymore~
