### ISSUE TITLE
Import of the whole music library from YouTube Music, not just playlists

### ISSUE THREAD

**Issue by QuinceTart10** [z-huang/InnerTune#949]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When logged in, add the option to sync/import the [songs tab in the YouTube Music library](https://music.youtube.com/library/songs) to the InnerTune library.

### Why do you want this feature?

I don't have my music library in a playlist, but I have it in the songs tab of my library and InnerTune doesn't have the option to import it at the moment, so this feature would finally let me migrate.

**Comment by Kurasami** [comment]
How would this be possible? Youtube saves your songs in playlists. If you don't save playlists in Youtube, how do you expect them imported to Innertune?

To get around your current situation. Add all your songs to a new playlist and then import them.

**Comment by QuinceTart10** [comment]
If I wanted to add all my songs to a playlist, how would I do it? Because I have hundreds of songs in my library and doing it manually would be the most tedious task ever, so I need an automated way to do it.

**Comment by z-huang** [comment]
Move to #1409
