### ISSUE TITLE
Synchronize history with Youtube Music

### ISSUE THREAD

**Issue by caJosue0060** [z-huang/InnerTune#950]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would like to share a suggestion to further improve the user experience. I have noticed that the app is out of sync with YouTube Music watch history. This means that the songs that I play on the YouTube platform are not reflected in the recommendations and suggestions of the application.

It would be very helpful if YouTube Music history support could be implemented. By synchronizing both platforms, users could enjoy a more cohesive and personalized experience.
It would be great to be able to find all our songs and playlists in one place and receive recommendations based on our global tastes and preferences.

### Why do you want this feature?

Besides, what's the point of having a login system, with Google, if it doesn't have a real utility?

**Comment by Kurasami** [comment]
This isn't going to happen. Innertune isn't an official or even authorized app to connect with Youtube music.

I don't know where you see any "login with Google" in Innertune. There isn't any. Innertune and Youtube Music are totally separate applications that do not connect to or share data with each other at all. That is for a reason.

If you want to synchronize things between Youtube Music and Innertune then the current only supported way is to take a backup from Google One and import the .csv file to get your playlists into Innertune. This is already an extremely good feature and allows you to port your playlists over. So long as you manage them on Youtube/Youtube Music you can import them to Innertune but not the other way around.

Lastly, if you are using both apps, just use Youtube Music. There is no purpose to use Innertune, especially if you are paying for Youtube music.

**Comment by corrupteddrive** [comment]
Yeah I also think likes and library should be synced, the app is a bit too locally focused and I think it should tie-in with YouTube Music a bit more.

**Comment by z-huang** [comment]
Synchronization is not planned, but I can add a page to view your YTM history.

**Comment by 7heMech** [comment]
Maybe optional sync?

**Comment by z-huang** [comment]
Move to #1409
