### ISSUE TITLE
Lyrics Translator

### ISSUE THREAD

**Issue by Sanuu7** [z-huang/InnerTune#952]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Translate songs lyrics like Japanese to English

### Why do you want this feature?

To understand songs
It feels good to know what your hearing

**Comment by Kurasami** [comment]
Doubt you'll see this added. Even other apps don't have this. It's a huge ask and would require massive amounts of API calls to a translation service and in real-time.

**Comment by Kurasami** [comment]
I have never seen a feature in Spotify that actually allows me to translate lyrics from one language into another. Even if Spotify does have this, is also an app with billions of dollars behind it. For that amount of API calls to a translation service, you'd need to pay money.

**Comment by Sanuu7** [comment]
There is a feature in Spotify.... And I'm not a developer bro so I don't know anything I just requested what I had in my mind

> I have never seen a feature in Spotify that actually allows me to translate lyrics from one language into another. The app _does_ have lyrics, but I've never seen real-time translated lyrics.
> 
> Even if Spotify does have this, is also an app with billions of dollars behind it. For that amount of API calls to a translation service, you'd need to pay money.

There is the feature to translate the lyrics. And I'm not a developer I just wanted to request a feature that I had in my mind. He can remove my issue if its not possible for him

**Comment by Sanuu7** [comment]
![Uploading Screenshot_2023-08-16-01-36-12-69_0438eb925998df20b3482ec25499d226.jpg…]()

**Comment by Sanuu7** [comment]
![Screenshot_2023-08-16-01-36-12-69_0438eb925998df20b3482ec25499d226](https://github.com/z-huang/InnerTune/assets/128639063/9d15011f-cba0-46e9-bb55-92aa73179a80)

**Comment by Kurasami** [comment]
Seems they're using Musicxmatch. That's a proprietary service which Spotify is paying them for by the looks of it. Looks to be the first of its kind and it also seems to be full of translation errors too.

That said, they have some of their code here: https://github.com/musixmatch/musixmatch-sdk 

However, their privacy policy and terms aren't very privacy friendly at first glance. It's also not clear if Spotify built the translation service on top of Musixmatches service. It definitely wasn't something made in a day.

Looks like each person would need their own API key and to accept the terms of their fingerprinting. We already have the option to turn off existing lyrics data sharing in Innertune. 

Anyway. Whilst it might be nice, I wouldn't ever expect it to find its way into this open source app. Seems like a legitimate thing to request but one would have to really do some reading before even considering getting into bed with this service.

**Comment by z-huang** [comment]
Thanks to ML Kit, this is possible. :) However, only 58 languages are supported. Since it's powered by Google, you won't get it in the foss version.

**Comment by Sanuu7** [comment]
> 

Thanks for your time and consideration to implement this

**Comment by z-huang** [comment]
One disadvantage is that the apk size grows too big (66MB). I have to create separate apks for different cpu architectures to redice size (25MB).
