### ISSUE TITLE
Ignore battery optimization?

### ISSUE THREAD

**Issue by VadosG** [z-huang/InnerTune#956]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

When you remove an app from the list of recent apps, or, sometimes in standby mode, InnerTune stops working. In some other similar applications this issue is solved by an option, enabling which the application does not stop working spontaneously. The same option is needed in InnerTune.

### Why do you want this feature?

Because clearing recent apps interrupts InnerTune, even when it's playing. Also interruptions in standby mode.

### Additional information

Confirmed on Android 7.1.2 and Android 10

**Comment by Kurasami** [comment]
There is already the option to disable/ignore battery optimization. If you aren't seeing it, then you need to update your Android version or get a new phone.

You also didn't state what version of the app you are using. Please don't delete parts of the issue template.

**Comment by VadosG** [comment]
0.5.1

> then you need to update your Android version or get a new phone.

> Android 10

That's just brilliant, nothing to add...
