### ISSUE TITLE
Duplicates the same song multiple times

### ISSUE THREAD

**Issue by Eliya-Manoj** [z-huang/InnerTune#957]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Create a playlist
2. Add a song 
3. Add same song again and again
4. Playlist adds same song multiple times

### Expected behavior

Ignore duplicate 

### Actual behavior

Creates duplicate (* times)

### Screenshots/Screen recordings

![6242228987980004921_121](https://github.com/z-huang/InnerTune/assets/90308888/4f6f11dc-d53f-4471-b188-107b30711e9b)

### InnerTune version

0.5.1

### Android version

Android 12

**Comment by z-huang** [comment]
I think you need #156.
