### ISSUE TITLE
Synchronise Youtube Music playlists with Innertune playlists

### ISSUE THREAD

**Issue by pakhrom** [z-huang/InnerTune#958]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Youtube Music playlists should be added to the Innertune playlists and Innertune playlists should be added to YouTube Music playlists. If the name of the YouTube Music playlist matches the name of the Innertune playlist, they should be merged. YouTube Music playlist "Your Likes" should be merged with the "Favorites" playlist of Innertune. The synchronisation feature should be optional, so users can turn the synchronisation off, or turn the synchronisation on only on "Your Likes" playlist etc.

### Why do you want this feature?

The login support is pretty limited, allowing only to listen to the playlists saved on your YouTube account. By adding the synchronisation it would be more convenient to the user to listen to the same playlist on PC in browser and on the phone in Innertune

**Comment by aayushrautela** [comment]
+1, would make it an even better app.

**Comment by Gian-Fr** [comment]
It would allow innertune to be a perfect replacement for yt music on android, like Sp-Mp does

**Comment by Kurasami** [comment]
There is never going to be any 2-way sync TO Youtube, but I can agree that being able to import everything directly from Youtube Music would be a blessing.

**Comment by z-huang** [comment]
As I said here https://github.com/z-huang/InnerTune/issues/88#issuecomment-1302152845, the purpose of the login feature is to make migration from YTM to InnerTune easier. I don't want to tie too much in YTM. Also, synchronization isn't an easy thing to implement.

**Comment by Dixip52** [comment]
yeah, import playlists like freetube does (with XML file from takeout.google.com) could be pretty cool
