### ISSUE TITLE
selecting song skips to wrong song

### ISSUE THREAD

**Issue by edl2** [z-huang/InnerTune#960]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. press song

### Expected behavior

play song selected

### Actual behavior

skips multiple songs forward and plays that song. this has happened pretty frequently recently. 

### Screenshots/Screen recordings

https://github.com/z-huang/InnerTune/assets/95947898/1ae6deb1-c3f5-4e19-9266-659ba4e1e726

### InnerTune version

5.1

### Android version

android 13

**Comment by z-huang** [comment]
Have you tried the latest commit?

**Comment by awucado** [comment]
im experiencing this issue too

**Comment by awucado** [comment]
> im experiencing this issue too

im on the latest commit

**Comment by corrupteddrive** [comment]
Also experiencing this issue.

**Comment by moonystars** [comment]
im having the same problem. it started today. it usually only happens when I search for songs though, doesn't happen in playlists. its also been happening both with and without me using a VPN

**Comment by z-huang** [comment]
Not sure but it may be fixed by the latest commit.

**Comment by z-huang** [comment]
Tell me if it still happens.
