### ISSUE TITLE
Search Online Does Not Work 

### ISSUE THREAD

**Issue by Najio100** [z-huang/InnerTune#967]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open Search with proxy HTTP enabled 
2. Search opens blank pages on every search

### Expected behavior

Search, should work.

### Actual behavior

Empty page just 

### InnerTune version

0.4.4

### Android version

11

### Additional information

I use http proxy because i am in a blcked country

**Comment by owencz1998** [comment]
You need need to update to 0.5.1

**Comment by Kurasami** [comment]
> ### Checklist
> * [x]  I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
> * [x]  I've checked that there is no issue about this bug.
> * [x]  This issue contains only one bug.
> * [x]  The title of this issue accurately describes the bug.
> 
> ### Steps to reproduce the bug
> 1. Open Search with proxy HTTP enabled
> 2. Search opens blank pages on every search
> 
> ### Expected behavior
> Search, should work.
> 
> ### Actual behavior
> Empty page just
> 
> ### Screenshots/Screen recordings
> _No response_
> 
> ### Logs
> _No response_
> 
> ### InnerTune version
> 0.4.4
> 
> ### Android version
> 11
> 
> ### Additional information
> I use http proxy because i am in a blcked country

You are using an ancient version of the app dude. Update, and then please close this issue.
