### ISSUE TITLE
Bixby routine actions

### ISSUE THREAD

**Issue by Donald-Win** [z-huang/InnerTune#968]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Currently when setting a routine in "Modes and Routines" (Bixby routines) on a samsung phone under "Open an app or do an app action" it gives the options for "Open innertune", "Search", "Songs", "Albums", and "Playlists".

All of these options work and Innertune opens to the selected view when activated but I was hoping it would be possible to introduce a setting where a selected  Playlist, album or song is played.

### Why do you want this feature?

My main usage of "routines" is to start music playing through my headset when riding my motorcycle. It would be convenient to have the music start automatically as I am usually already wearing my gloves and have my phone in my bag or pocket and have to remove them to manually start the music.

My helmet headset and even my motorcycle have controls to play and pause etc but cannot start anything unless it is already "pre loaded". Sometimes it works as there is already music loaded from previous use but it would be good If I could have something load via routines.

My problem could also be solved in somehow having some form of automatic playlist population on opening.  I'm not sure which would be easiest to implement but would be happy with any solution that works.

I know this is a limited usage case so I understand it would not be a priority for you but please consider it.

Thanks for the awesome app.

### Additional information

![Screenshot_20230815_164722_Modes and Routines](https://github.com/z-huang/InnerTune/assets/140929208/ede4853d-8273-4158-865d-9eccd14bfa2e)

**Comment by Kurasami** [comment]
Bixby is only able to open an app to a specific public view. In this case those that you see (eg. Playlists). You'd still further need to select the playlist that you want to play. Bixby can't go any further with the command in being able to play specific playlists in the app. That's not a limitation of Innertune but a limitation of Bixby and all apps for privacy purposes.

**Comment by Donald-Win** [comment]
Thanks for the info @Kurasami. I wasn't aware that that was the limitation.

Just wondering if you or anyone else may know if it can be accomplished through the "play music" option. When I select that currently, the only option I have is my file browser.

![Screenshot_20230816_120232_Modes and Routines](https://github.com/z-huang/InnerTune/assets/140929208/b2484805-509c-455d-a56d-028b3f400717)
![Screenshot_20230816_120453_Modes and Routines](https://github.com/z-huang/InnerTune/assets/140929208/c0971ce1-9580-4335-9d78-80229fde6699)

**Comment by Donald-Win** [comment]
Seems like not possible. Closing request
