### ISSUE TITLE
Unexpected error when app is closed while a song is playing

### ISSUE THREAD

**Issue by tinducvo** [z-huang/InnerTune#969]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. While the song is playing, close the app

### Expected behavior

Songs can load and play

### Actual behavior

Songs cannot be loaded or played until restarted. This only happens if the app is closed while a song is playing.

### Screenshots/Screen recordings

![Screenshot_20230815-112003~2](https://github.com/z-huang/InnerTune/assets/6686958/3c4131e7-1313-4dc7-944c-caef22685bad)

### InnerTune version

0.5.1

### Android version

13

### Additional information

Love the app.

**Comment by Kurasami** [comment]
Doesn't happen to me on my device. I can play a song. Swipe the app away to close it and open it again and immediately start playing something.

Your bug doesn't really make any sense. Why are you closing the app whilst a song is playing?
When the app opens again, any song should be playable.

What phone are you using? I have a Xiaomi 13 Ultra, Xperia 1V and Xiaomi 11T Pro. This doesn't happen on any of them.

**Comment by tinducvo** [comment]
I just want to close the app. A normal user wouldn't expect to have to pause the song before closing the app.

Could it possibly be because closing the app without pausing interrupts file / cache writing? 

This is on the Pixel 7 with the latest patch. I'll test on my XZ2 Compact when I get time. 

Thank you for caring and responding so promptly.

**Comment by Kurasami** [comment]
I'm still a bit confused here. You can just close the app whilst it's playing?

If I want to close the app. I just tap the drawer/recents button and swipe it away.

Do you mean that you want to be able to tap "back" out of the app whilst the song is playing? If I do that, the app still keeps playing in the background. But that is the intention. If you want to actually fully close the app, swipe it out of the recents drawer. In which case, when you open it again - you should be able to immediately play something else.

**Comment by tinducvo** [comment]
By close, I meant swipe it from the recent drawer like this:

**Comment by Kurasami** [comment]
I think the reason for this is because your phone isn't actually closing the app. It's freezing it's state in memory. Basically it's hibernating the app.

My phone is actually completely killing the app when I swipe it away. Your phone is holding the application state. That is, it's actually restoring it when you open it. In which case Innertune bugs out because the player state has changed.

It's likely a feature of the Pixel. Probably to make apps load faster after having been closed. There's likely nothing you can do about it.

**Comment by tinducvo** [comment]
When I prevent the app app from running in the background with "restricted" battery usage mode, "unexpected error" goes away, but the app closes within minutes when I'm outside of it.

That could indicate it's a pixel specific state problem, but I just tested on my Xperia XZ2 and it also gets "unexpected error on fast home internet.

**Comment by z-huang** [comment]
I need logs.

**Comment by z-huang** [comment]
It should be fixed, please check.

**Comment by tinducvo** [comment]
Confirming that the debug build of aaba0ba resolved this issue.
