### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by max5354** [z-huang/InnerTune#97]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

add sleep timer.

### Why do you want this feature?

I think it's useful.

**Comment by airon90** [comment]
I don't think it could be useful such a feature in a music app. I'd suggest you to use another app to close automatically the app after some time

**Comment by TGRush** [comment]
> I don't think it could be useful such a feature in a music app. I'd suggest you to use another app to close automatically the app after some time

I disagree,

With an app designed to be easy to use to anyone, one very common usecase would be listening to music for sleep.

exporting the music isnt easy either _(filenames dont match songs)_, and running `sleep 30m && killall com.zionhuang.music` in a Terminal drains battery as a Wakelock is needed.

**Comment by z-huang** [comment]
Yeah, this feature can be added.

> exporting the music isnt easy either (filenames dont match songs)

See #117.

**Comment by ganchair** [comment]
I sadly have to use Spotify to fall asleep since its has a sleep timer. I wish InnerTune will get this feature since its radio/recommendations are way better than Spotify.

**Comment by christian179717** [comment]
@z-huang has it been inplemented? I cannot find it

**Comment by z-huang** [comment]
Check out the debug builds.
