### ISSUE TITLE
Clear music queue

### ISSUE THREAD

**Issue by tinducvo** [z-huang/InnerTune#970]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Ability to clear the entire song queue instead of individual songs. Could be implemented as a button on the playlist manager bottom bar, where the shuffle button resides.

### Why do you want this feature?

Very slow to remove unwanted autogenerated / manually added albums when I change my mind about what songs I want to listen to.

### Additional information

![Screenshot_20230815-120009](https://github.com/z-huang/InnerTune/assets/6686958/292730d3-31f7-4591-af8e-2b96756f5273)

**Comment by tinducvo** [comment]
Also, it'd be if someone could clarify the difference between "shuffle" / "start radio" on the artist page? I considered opening another issue, but it's somewhat related to this issue.

They both seem to:
- endlessly add songs to the queue. **Issue**: possible to stop without "clear music queue" button addition?
- slightly shuffle the current playing song. When clicked, the current song barely changes. **Issue**: should shuffle affect the current song too?
- shuffle the rest of the songs

**Comment by z-huang** [comment]
1. You can clear the queue by swiping down the bottom sheet.
2. Shuffle and start radio are taken from YouTube Music directly.

**Comment by tinducvo** [comment]
Thank you. I now know what "shuffle" and "start radio" do.

Could you clarify what you mean by swiping the bottom sheet though?
