### ISSUE TITLE
Login Support Missing?

### ISSUE THREAD

**Issue by Kurasami** [z-huang/InnerTune#972]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Was this removed? I see other users commenting about it, I also see it listed in the Readme.md and there is even a comment from almost 1 year ago that says the feature exists.

I cannot find it in Settings > Content. There is simply only the following options:

![signal-2023-08-15-230806_002](https://github.com/z-huang/InnerTune/assets/77334270/9730b4c3-eb2e-4528-a3ee-1ac6b6f3068f)

### Expected behavior

#88 

```Now you can login from Settings->Content->Login. Search suggestion works again. Also, if you have YouTube Premium, you can enjoy high quality streams (>200kbps)! Thanks @LuanRT for testing. However, the suggestions in the home page will be the same if you only use InnerTune, for InnerTune doesn't send your playing history back to YouTube.

Though theorically we can do almost everything YTM can do after logged in, I only plan to make migration from your Google account to InnerTune easier.

As for personal music suggestions, I plan to redesign the home tab to make it more useful.

Note: InnerTune provides a webview for you to log in, and the only thing InnerTune does is to save the cookies so as to make authenticated requests to YouTube Music. You can log out by entering the webview and log out. Your password will NEVER be saved. Feel free to experience the feature!

_Originally posted by @z-huang in https://github.com/z-huang/InnerTune/issues/88#issuecomment-1302152845_
```

### InnerTune version

0.5.1

### Android version

Android 13

### Additional information

Can't see it in any versions of the app I use. Not 0.50, 0.5.1 in either of my devices. Not sure how other people are seeing it?

**Comment by tinducvo** [comment]
When you check about, is it 0.5.1? I found F-Droid had 0.5.0 instead of 0.5.1

**Comment by Kurasami** [comment]
Hah you were right. It was only 0.5.0. I updated and there it is. I'll have give it a try out. It'll be a huge feature to be able to make my playlists on YouTube and then just import them to Innertune so I can listen on mobile devices.
