### ISSUE TITLE
Reordering in playlists bugged

### ISSUE THREAD

**Issue by Syntax-Err5** [z-huang/InnerTune#977]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [x] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open a playlist
2. Attempt to reorder a song
3. The song is moved incorrectly

### Expected behavior

The song should move to the desired position

### Actual behavior

The song is not moved to the correct position

### InnerTune version

0.5.1

### Android version

ColorOS 13, based on Android 13

### Additional information

It looks like, when I move a song, the app moves the song that is below the song I tried to move, the same amount of spots. It doesn't happen on the queue.

I also created a second playlist with 45 songs but couldn't reproduce the bug.

**Comment by Syntax-Err5** [comment]
Screen Recording:

https://github.com/z-huang/InnerTune/assets/123362106/9757cbde-e9ff-405e-8dbc-5a4e5303ebab

**Comment by z-huang** [comment]
It seems that the database is corrupted. The reason is probably that you're performing reorderings too often, without waiting for the database to save the result. Delete the playlist and create a new one. Remember to wait a second between two moves.
