### ISSUE TITLE
Ability to view music video

### ISSUE THREAD

**Issue by corrupteddrive** [z-huang/InnerTune#979]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

In the official YT Music app there is the option to switch between audio and video on some songs. But there is no ability to watch a music video in InnerTune and I think it would be a great feature. It can just be audio-only by default and just have the option for video for the people (such as me) who want it. 

### Why do you want this feature?

The ability to watch music videos within the app would be very convenient

**Comment by z-huang** [comment]
To keep it simple, this is not planned. I can live without music video.
