### ISSUE TITLE
Equalizer Settings Option

### ISSUE THREAD

**Issue by chkrforoldcompatbility** [z-huang/InnerTune#983]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Put option to allow device equalizer setting

### Why do you want this feature?

It's important and Essential for a music PLayer

**Comment by z-huang** [comment]
Already exists in the "..." button of the player.
