### ISSUE TITLE
Sync Playlist Between InnerTune and YouTube

### ISSUE THREAD

**Issue by stepersy** [z-huang/InnerTune#990]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

It would be useful to be able to synchronize YouTube Playlists to SimpMusic. That way you can see them in the library. And when you create a new playlist, it is synchronized across all devices with YouTube Music.

### Why do you want this feature?

It would be very useful to never lose your playlists and to be able to have them on all your devices at the same time!

### Additional information

You can see an example from SpMp.
https://github.com/toasterofbread/spmp

![261931412-48c4f58b-0d63-44c9-a744-d1f343d9ab76](https://github.com/z-huang/InnerTune/assets/94073410/ab02d025-30db-4200-975d-3a8b779bd6bf)

**Comment by Bwangster12** [comment]
Yeah, I'm actually a little confused as to how signing in and seeing your account works with playlists and like songs in Innertune.  I assumed once I signed in and my youtube music playlist sync, it appear in my inner tune playlists but that clearly isn't the case.

**Comment by zerobun** [comment]
> Yeah, I'm actually a little confused as to how signing in and seeing your account works with playlists and like songs in Innertune. I assumed once I signed in and my youtube music playlist sync, it appear in my inner tune playlists but that clearly isn't the case.

You can actually to account - - > select a playlist - - > press the box with arrow button (playlist gets imported = now you can add songs to this playlist and sync them, to sync them you hold the imported playlist in ur playlist tab and press sync

**Comment by zerobun** [comment]
Oh it seems I made a mistake, it seems when you sync it doesn't sync ur inner tune playlist to the yt playlist, but it syncs the YouTube playlist to your InnerTune 🧍.

I honestly think it should be opposite or rather we jus edit out YouTube playlist in the first place.

**Comment by CHanoey145** [comment]
> Oh it seems I made a mistake, it seems when you sync it doesn't sync ur inner tune playlist to the yt playlist, but it syncs the YouTube playlist to your InnerTune 🧍.
> 
> I honestly think it should be opposite or rather we jus edit out YouTube playlist in the first place.

Important feature please add this feature so it gets synchronized in all devices

**Comment by demirdegerli** [comment]
> Oh it seems I made a mistake, it seems when you sync it doesn't sync ur inner tune playlist to the yt playlist, but it syncs the YouTube playlist to your InnerTune 🧍.
> 
> I honestly think it should be opposite or rather we jus edit out YouTube playlist in the first place.

This is a must.

**Comment by gmankab** [comment]
> You can actually to account - - > select a playlist - - > press the box with arrow button (playlist gets imported = now you can add songs to this playlist and sync them, to sync them you hold the imported playlist in ur playlist tab and press sync

can you please make a button that will synchronise everything authomaticaly

**Comment by z-huang** [comment]
Move to #1409
