### ISSUE TITLE
Liked Songs and Downloaded songs not showing

### ISSUE THREAD

**Issue by Angy-Kitty** [z-huang/InnerTune#992]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to "Playlists" tab

### Expected behavior

The tab should display the "Liked Songs" and "Downloaded Songs" Playlists

### Actual behavior

The "Liked Songs" and "Downloaded Songs" Playlists do not show up.

### Screenshots/Screen recordings

![IMG_20230822_192423](https://github.com/z-huang/InnerTune/assets/123874131/da7db07b-862a-4685-9858-c541f4193dff)

### InnerTune version

0.5.2

### Android version

Android 10 QKQ1.190910.002

### Additional information

The latest DEBUG version does not work on my device.

**Comment by z-huang** [comment]
They're moved to songs tab as filters.
