### ISSUE TITLE
[Feature request] Combine "Songs", "Artists" and "Albums"

### ISSUE THREAD

**Issue by Guanran928** [z-huang/InnerTune#994]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

![Screenshot_2023-08-24-02-46-38-828_com zionhuang music-edit](https://github.com/z-huang/InnerTune/assets/68757440/ef40cc45-1422-4831-aae6-05eeeb14c0c4)
Combine "Songs", "Artists" and "Albums" to a separate tab named "Library".

### Why do you want this feature?

There is already 5 tabs in the bottom tab bar.
It would make sense to merge the same kind of tabs into a separate category to make the bottom tab bar cleaner.

**Comment by z-huang** [comment]
5 items in the bottom navigation bar isn't too much. The document of material design says at most 5 items can be put in the bottom nav. Google Maps and Oto Music also have 5 at the bottom.
Also, it looks like you're using 0.5.0. 0.5.2 is available.

**Comment by Guanran928** [comment]
> Also, it looks like you're using 0.5.0. 0.5.2 is available.
Oops, I guess F-Droid haven't updated their repo (or maybe it might be my mirror), since I did not see an available update, thanks for reminding me though.

**Comment by d4f5409d** [comment]
It'd also be a great proposal to somehow include liked artist better in the UX like quick picks from them on the home screen or somehow letting us quickly start songs from them.

**Comment by d4f5409d** [comment]
Bruh moment
