### ISSUE TITLE
White flashing when pause/unpause song from notification

### ISSUE THREAD

**Issue by github-user93** [z-huang/InnerTune#997]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I'm using Redmi note 7 pro, android 10, miui 12.5.1
When i pause/unpause a song from notification, it flashes.

video - https://youtu.be/SWm4n3-3K6I

only other app it happens with is SimpMusic.
https://github.com/maxrave-dev/SimpMusic/issues/63

### Expected behavior

Should not flash

### Actual behavior

White flashes

### InnerTune version

0.5.2 debug

### Android version

Android 10

**Comment by z-huang** [comment]
I'm also using MIUI 12.5, but don't have this issue. Android emulator doesn't have this issue, too. Maybe there're some settings that cause this?
